import 'package:flutter/material.dart';
import 'package:math_derust/data/db.dart';
import 'package:math_derust/session.dart';
import 'package:rive/rive.dart';

/*
TOPICS
1. Solve linear, compound, absolute value, quadratic and rational inequalities.
2. Evaluate and use functional notation to include difference quotients.
3. Analyze functions to include domains, ranges, restrictions and symmetry.
4. Sketch graphs of common functions and their transformations
5. Perform basic operations on functions to include compositions and inverses.
6. Use the theory of polynomial equations to find zeros.
7. Graph polynomial and rational functions to include intercepts and asymptotes.
8. Analyze exponential and logarithmic functions to include domains, ranges, asymptotes and their graphs.
9. Evaluate exponential and logarithmic expressions.
10. Solve exponential and logarithmic equations and associated applications.
11. Analyze and graph equations of conic sections to include vertices, foci, and asymptotes.
12. Solve applications involving conic sections.
13. Solve non-linear systems using substitution and elimination techniques.                                                                                                 q   
*/

class IntAlgPage extends StatefulWidget {
  const IntAlgPage({super.key});

  @override
  State<IntAlgPage> createState() => _IntAlgPageState();
}

class _IntAlgPageState extends State<IntAlgPage> {
  DbHelper db = DbHelper.instance;
  List<Map<String,dynamic>> questions = [];

  List<Map<String, dynamic>> newProblems = [
    // Topic 1: Solve inequalities (linear, compound, absolute value, quadratic, rational)
    // (20 problems)
    {
      'name': 'T1P1',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve the inequality: 2x - 3 < 7',
      'answers': 'x < 5; x < 3; x > 5; x > 3',
      'correct': 'x < 5',
    },
    {
      'name': 'T1P2',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve the inequality: -x + 4 ≥ 10',
      'answers': 'x ≤ -6; x ≥ -6; x ≤ 6; x ≥ 6',
      'correct': 'x ≤ -6',
    },
    {
      'name': 'T1P3',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve the absolute value inequality: |x - 5| < 3',
      'answers': '2 < x < 8; 3 < x < 7; 2 ≤ x ≤ 8; 3 ≤ x ≤ 7',
      'correct': '2 < x < 8',
    },
    {
      'name': 'T1P4',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve the quadratic inequality: x² - 4x < 0',
      'answers': '0 < x < 4; x < 0 or x > 4; 0 ≤ x ≤ 4; x ≤ 0 or x ≥ 4',
      'correct': '0 < x < 4',
    },
    {
      'name': 'T1P5',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 4,
      'content': 'Solve the rational inequality: (x + 2)/(x - 3) > 0',
      'answers': 'x < -2 or x > 3; -2 < x < 3; x > -2 and x < 3; x > 3',
      'correct': 'x < -2 or x > 3',
    },
    {
      'name': 'T1P6',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: 3 - 2x ≥ 1',
      'answers': 'x ≤ 1; x ≥ 1; x < 1; x > 1',
      'correct': 'x ≤ 1',
    },
    {
      'name': 'T1P7',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: |2x + 1| ≥ 5',
      'answers': 'x ≤ -3 or x ≥ 2; x ≥ -3 and x ≤ 2; x < -3 or x > 2; x ≤ -2 or x ≥ 3',
      'correct': 'x ≤ -3 or x ≥ 2',
    },
    {
      'name': 'T1P8',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: x² - 9 ≥ 0',
      'answers': 'x ≤ -3 or x ≥ 3; -3 < x < 3; x > -3 and x < 3; x = -3 or x = 3',
      'correct': 'x ≤ -3 or x ≥ 3',
    },
    {
      'name': 'T1P9',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: (2x - 1)/(x + 4) < 0',
      'answers': '–4 < x < ½; x < –4 or x > ½; x > –4 and x > ½; x < –4 and x < ½',
      'correct': '–4 < x < ½',
    },
    {
      'name': 'T1P10',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: 5 - x > 2',
      'answers': 'x < 3; x > 3; x < 2; x > 2',
      'correct': 'x < 3',
    },
    {
      'name': 'T1P11',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: -2x + 1 ≤ 7',
      'answers': 'x ≥ -3; x ≤ -3; x ≥ 3; x ≤ 3',
      'correct': 'x ≥ -3',
    },
    {
      'name': 'T1P12',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: 3x + 2 > 2x + 5',
      'answers': 'x > 3; x < 3; x > 2; x < 2',
      'correct': 'x > 3',
    },
    {
      'name': 'T1P13',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: 4 - |x| < 0',
      'answers': '|x| > 4; |x| < 4; x > 4; x < -4',
      'correct': '|x| > 4',
    },
    {
      'name': 'T1P14',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: x/2 - 3 ≥ 0',
      'answers': 'x ≥ 6; x ≤ 6; x ≥ 3; x ≤ 3',
      'correct': 'x ≥ 6',
    },
    {
      'name': 'T1P15',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: 7 - 2|x - 1| ≤ 3',
      'answers': 'x ≤ -1 or x ≥ 3; -1 < x < 3; x ≤ 1 or x ≥ 3; x ≥ -1 and x ≤ 3',
      'correct': 'x ≤ -1 or x ≥ 3',
    },
    {
      'name': 'T1P16',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: (x - 2)(x + 3) < 0',
      'answers': '-3 < x < 2; x < -3 or x > 2; x ≤ -3 or x ≥ 2; -3 ≤ x ≤ 2',
      'correct': '-3 < x < 2',
    },
    {
      'name': 'T1P17',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: x² - 2x - 8 > 0',
      'answers': 'x < -2 or x > 4; x > -2 and x < 4; x < 2 or x > -4; x < -4 or x > 2',
      'correct': 'x < -2 or x > 4',
    },
    {
      'name': 'T1P18',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'Solve: 1/(x - 1) < 0',
      'answers': 'x < 1; x > 1; x ≠ 1; all x',
      'correct': 'x < 1',
    },
    {
      'name': 'T1P19',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: (2x + 3)/(x - 5) ≤ 0',
      'answers': 'x ∈ [ -3/2, 5 ); x ∈ ( -3/2, 5 ); x ∈ (5, ∞); x ∈ (-∞, -3/2]',
      'correct': 'x ∈ [ -3/2, 5 )',
    },
    {
      'name': 'T1P20',
      'category': 'Intermediate Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'Solve: |x + 2| > 7',
      'answers': 'x > 5 or x < -9; x > -5 or x < 9; x > 9 or x < -5; x > -9 and x < 5',
      'correct': 'x > 5 or x < -9',
    },

    // Topic 2: Functional Notation and Difference Quotients (20 problems)
    {
      'name': 'T2P1',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = 2x + 3, evaluate f(4).',
      'answers': '11;10;9;8',
      'correct': '11',
    },
    {
      'name': 'T2P2',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = x², evaluate f(3).',
      'answers': '9;6;8;7',
      'correct': '9',
    },
    {
      'name': 'T2P3',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = 3x - 1, evaluate f(-2).',
      'answers': '-7;-5;-3;1',
      'correct': '-7',
    },
    {
      'name': 'T2P4',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Let f(x)= x². Find the difference quotient at x=2: [f(2+h) - f(2)]/h.',
      'answers': '(4h+h²)/h; (h²+4h)/h; 4+h; All of the above are equivalent',
      'correct': '4+h',
    },
    {
      'name': 'T2P5',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Let f(x)= √x. Write the difference quotient for x=9.',
      'answers': '(√(9+h)-3)/h; (3+h-3)/h; h/(√(9+h)-3); 3/h',
      'correct': '(√(9+h)-3)/h',
    },
    {
      'name': 'T2P6',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = 1/x, evaluate f(2).',
      'answers': '0.5;2;1;0.25',
      'correct': '0.5',
    },
    {
      'name': 'T2P7',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = x³, evaluate f(2).',
      'answers': '6;7;8;9',
      'correct': '8',
    },
    {
      'name': 'T2P8',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Let f(x)= 2x². Write the difference quotient at x=3.',
      'answers': '6+2h; 6+h; 6+2h+h²; (2(9+6h+h²)-18)/h',
      'correct': '(2(9+6h+h²)-18)/h',
    },
    {
      'name': 'T2P9',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = |x - 1|, evaluate f(0).',
      'answers': '0;1;2;Undefined',
      'correct': '1',
    },
    {
      'name': 'T2P10',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x) = 5 - x, evaluate f(5).',
      'answers': '0;5;10;–5',
      'correct': '0',
    },
    {
      'name': 'T2P11',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'If f(x)= ln(x), evaluate f(e).',
      'answers': '0;1;e;Undefined',
      'correct': '1',
    },
    {
      'name': 'T2P12',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Let f(x)= 2x+1. Write the difference quotient at x=1.',
      'answers': '2;3;2+ h;2',
      'correct': '2',
    },
    {
      'name': 'T2P13',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x)= x² - 2x, evaluate f(3).',
      'answers': '3;4;5;6',
      'correct': '3',
    },
    {
      'name': 'T2P14',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Let f(x)= 3x² + 2. Write the difference quotient at x=2.',
      'answers': '6+?; (3(4+4h+h²)+2- (14))/h; 6+h; 6+2h',
      'correct': '(3(4+4h+h²)+2- (14))/h',
    },
    {
      'name': 'T2P15',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'If f(x)= x³ - x, evaluate f(2).',
      'answers': '6;7;8;9',
      'correct': '6',
    },
    {
      'name': 'T2P16',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x)= 2^x, evaluate f(3).',
      'answers': '6;7;8;8',
      'correct': '8',
    },
    {
      'name': 'T2P17',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Let f(x)= 10 - x². Write the difference quotient at x=2.',
      'answers': '((10- (4+?))-?)/h; (f(2+h)-6)/h; (f(2+h)-f(2))/h; (h²-?)/h',
      'correct': '(f(2+h)-f(2))/h',
    },
    {
      'name': 'T2P18',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x)= √(x+4), evaluate f(5).',
      'answers': '2;3;√9;4',
      'correct': '3',
    },
    {
      'name': 'T2P19',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x)= 3x+4, evaluate f(-1).',
      'answers': '1;0;–1;–2',
      'correct': '1',
    },
    {
      'name': 'T2P20',
      'category': 'Intermediate Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'If f(x)= 1/(x+1), evaluate f(1).',
      'answers': '0.5;1;2;Undefined',
      'correct': '0.5',
    },

    // Topic 3: Analyze functions (domains, ranges, restrictions, symmetry) – 20 problems
    {
      'name': 'T3P1',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the domain of f(x) = 1/(x - 3).',
      'answers': 'x ≠ 3; all real numbers; x > 3; x < 3',
      'correct': 'x ≠ 3',
    },
    {
      'name': 'T3P2',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the domain of f(x) = √(x + 2).',
      'answers': 'x ≥ -2; x > -2; all real numbers; x ≤ -2',
      'correct': 'x ≥ -2',
    },
    {
      'name': 'T3P3',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the range of f(x) = x².',
      'answers': 'y ≥ 0; y ≤ 0; all real numbers; y > 0',
      'correct': 'y ≥ 0',
    },
    {
      'name': 'T3P4',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the domain of f(x) = |x|.',
      'answers': 'all real numbers; x ≥ 0; x < 0; x ≠ 0',
      'correct': 'all real numbers',
    },
    {
      'name': 'T3P5',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain of f(x) = (x - 1)/(x + 2).',
      'answers': 'x ≠ -2; x ≠ 1; all real numbers; x ≠ -1',
      'correct': 'x ≠ -2',
    },
    {
      'name': 'T3P6',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain of f(x) = 1/(x² - 4).',
      'answers': 'x ≠ 2 and x ≠ -2; all real numbers; x > 2 or x < -2; x ≠ 0',
      'correct': 'x ≠ 2 and x ≠ -2',
    },
    {
      'name': 'T3P7',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the domain of f(x) = √(9 - x).',
      'answers': 'x ≤ 9; x ≥ 9; all real numbers; x < 9',
      'correct': 'x ≤ 9',
    },
    {
      'name': 'T3P8',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 1,
      'content': 'Determine the range of f(x) = x³.',
      'answers': 'all real numbers; y ≥ 0; y > 0; y ≤ 0',
      'correct': 'all real numbers',
    },
    {
      'name': 'T3P9',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain of f(x) = log(x - 1).',
      'answers': 'x > 1; x ≥ 1; all real numbers; x < 1',
      'correct': 'x > 1',
    },
    {
      'name': 'T3P10',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the domain of f(x) = (x + 1)/(x - 1).',
      'answers': 'x ≠ 1; x ≠ -1; all real numbers; x ≠ 0',
      'correct': 'x ≠ 1',
    },
    {
      'name': 'T3P11',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 1,
      'content': 'Determine the domain of f(x) = 1/(x² + 1).',
      'answers': 'all real numbers; x ≠ 0; x ≥ 0; x ≤ 0',
      'correct': 'all real numbers',
    },
    {
      'name': 'T3P12',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 1,
      'content': 'Determine the domain of f(x) = √x.',
      'answers': 'x ≥ 0; all real numbers; x > 0; x ≤ 0',
      'correct': 'x ≥ 0',
    },
    {
      'name': 'T3P13',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain of f(x) = (x² - 1)/(x - 1).',
      'answers': 'all real numbers except 1; all real numbers; x ≠ -1; x ≠ 1',
      'correct': 'all real numbers except 1',
    },
    {
      'name': 'T3P14',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain of f(x) = 1/√(x - 2).',
      'answers': 'x > 2; x ≥ 2; all real numbers; x < 2',
      'correct': 'x > 2',
    },
    {
      'name': 'T3P15',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the symmetry of f(x) = x².',
      'answers': 'Even (symmetric about y-axis); Odd; Neither; Both',
      'correct': 'Even (symmetric about y-axis)',
    },
    {
      'name': 'T3P16',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain and range of f(x) = 1/(x + 2).',
      'answers': 'Domain: x ≠ -2; Range: all real numbers except 0; Others',
      'correct': 'Domain: x ≠ -2; Range: all real numbers except 0',
    },
    {
      'name': 'T3P17',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the range of f(x) = x² - 4.',
      'answers': 'y ≥ -4; y ≥ 0; all real numbers; y ≤ -4',
      'correct': 'y ≥ -4',
    },
    {
      'name': 'T3P18',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Determine the domain of f(x) = √(4 - x²).',
      'answers': '-2 ≤ x ≤ 2; x ≥ 2; x ≤ -2; all real numbers',
      'correct': '-2 ≤ x ≤ 2',
    },
    {
      'name': 'T3P19',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the symmetry of f(x) = sin(x).',
      'answers': 'Odd (symmetric about the origin); Even; Neither; Both',
      'correct': 'Odd (symmetric about the origin)',
    },
    {
      'name': 'T3P20',
      'category': 'Intermediate Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Determine the symmetry of f(x) = cos(x).',
      'answers': 'Even (symmetric about the y-axis); Odd; Neither; Both',
      'correct': 'Even (symmetric about the y-axis)',
    },

    // Topic 4: Sketch graphs and transformations (20 problems)
    {
      'name': 'T4P1',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Describe the transformation of y = (x - 2)² + 3.',
      'answers': 'Shift right 2 and up 3; Shift left 2 and down 3; Shift right 2 and down 3; Shift left 2 and up 3',
      'correct': 'Shift right 2 and up 3',
    },
    {
      'name': 'T4P2',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Describe the transformation of y = -|x|.',
      'answers': 'Reflect over the x-axis; Reflect over the y-axis; Shift up; Shift down',
      'correct': 'Reflect over the x-axis',
    },
    {
      'name': 'T4P3',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Sketch the graph of y = √(x - 1). What is its horizontal shift?',
      'answers': 'Shift right 1; Shift left 1; No shift; Shift up 1',
      'correct': 'Shift right 1',
    },
    {
      'name': 'T4P4',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Sketch the graph of y = -x². How is it transformed compared to y = x²?',
      'answers': 'Reflected over the x-axis; Reflected over the y-axis; Shifted right; Shifted left',
      'correct': 'Reflected over the x-axis',
    },
    {
      'name': 'T4P5',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Describe the transformation for y = (x + 3)² - 4.',
      'answers': 'Shift left 3 and down 4; Shift right 3 and up 4; Shift left 3 and up 4; Shift right 3 and down 4',
      'correct': 'Shift left 3 and down 4',
    },
    {
      'name': 'T4P6',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'For y = |x| + 2, what is the vertical shift?',
      'answers': 'Up 2; Down 2; Up 1; No shift',
      'correct': 'Up 2',
    },
    {
      'name': 'T4P7',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'For y = -2|x - 1|, describe the transformation.',
      'answers': 'Shift right 1, reflect over x-axis, stretch vertically by 2; Shift left 1, reflect over y-axis; Reflect over x-axis only; Stretch vertically by 2 only',
      'correct': 'Shift right 1, reflect over x-axis, stretch vertically by 2',
    },
    {
      'name': 'T4P8',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'What is the vertex of y = (x - 3)² - 5?',
      'answers': '(3,-5); (-3,5); (3,5); (-3,-5)',
      'correct': '(3,-5)',
    },
    {
      'name': 'T4P9',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Describe the line transformation of y = -x + 4.',
      'answers': 'Reflection over x-axis; Reflection over y-axis; No transformation; Shift up 4',
      'correct': 'Reflection over x-axis',
    },
    {
      'name': 'T4P10',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Transform y = x² to y = (x + 2)² - 1. What is the new vertex?',
      'answers': '(-2,-1); (2,1); (-2,1); (2,-1)',
      'correct': '(-2,-1)',
    },
    {
      'name': 'T4P11',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Describe the transformation for y = (x - 4)²/2 + 3.',
      'answers': 'Stretch vertically by 1/2, shift right 4, up 3; Stretch horizontally; Reflect; Shift left',
      'correct': 'Stretch vertically by 1/2, shift right 4, up 3',
    },
    {
      'name': 'T4P12',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Sketch the graph of y = -0.5x² + 2. What is its maximum point?',
      'answers': '(0,2); (2,2); (0,-2); (2,-2)',
      'correct': '(0,2)',
    },
    {
      'name': 'T4P13',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'What is the vertical shift in y = |x - 1| + 3?',
      'answers': 'Up 3; Down 3; Up 1; No shift',
      'correct': 'Up 3',
    },
    {
      'name': 'T4P14',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'For y = 2|x - 2|, what is the horizontal shift?',
      'answers': 'Right 2; Left 2; No shift; Up 2',
      'correct': 'Right 2',
    },
    {
      'name': 'T4P15',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Describe the graph of y = -|x + 1| + 4.',
      'answers': 'Reflection over x-axis, shift left 1, up 4; Reflection over y-axis; Shift right 1; No transformation',
      'correct': 'Reflection over x-axis, shift left 1, up 4',
    },
    {
      'name': 'T4P16',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Sketch y = (x - 2)². What is its vertex?',
      'answers': '(2,0); (-2,0); (0,2); (0,-2)',
      'correct': '(2,0)',
    },
    {
      'name': 'T4P17',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'For y = -(x + 3)² + 1, what is the vertex?',
      'answers': '(-3,1); (-3,-1); (3,1); (3,-1)',
      'correct': '(-3,1)',
    },
    {
      'name': 'T4P18',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'For y = |x| - 3, what is the y-intercept?',
      'answers': '-3;0;3;1',
      'correct': '-3',
    },
    {
      'name': 'T4P19',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'For y = 2|x - 2|, what is the stretch factor?',
      'answers': '2;0.5;1;No stretch',
      'correct': '2',
    },
    {
      'name': 'T4P20',
      'category': 'Intermediate Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Describe the transformation for y = -|x + 1| + 4.',
      'answers': 'Reflect over x-axis, shift left 1, up 4; Reflect over y-axis; Shift right; No change',
      'correct': 'Reflect over x-axis, shift left 1, up 4',
    },

    // Topic 5: Operations on functions (compositions and inverses) – 20 problems
    {
      'name': 'T5P1',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'If f(x)= 2x + 3 and g(x)= x - 4, find (f ∘ g)(x).',
      'answers': '2x - 5; 2x + 11; 2x - 5; 2x - 5', // Duplicate answer intentionally simplified
      'correct': '2(x - 4) + 3', // which simplifies to 2x - 5
    },
    {
      'name': 'T5P2',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Find the inverse of f(x)= 3x - 5.',
      'answers': ['(x+5)/3', '(x-5)/3', '3x+5', '3x-5'],
      'correct': '(x+5)/3',
    },
    {
      'name': 'T5P3',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'If f(x)= x² and g(x)= √x, find (f ∘ g)(x).',
      'answers': 'x; x²; √x; 2x',
      'correct': 'x',
    },
    {
      'name': 'T5P4',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'If f(x)= x+1 and g(x)= 2x, find (f ∘ g)(2).',
      'answers': '5;6;7;8',
      'correct': '5',
    },
    {
      'name': 'T5P5',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Find the inverse of f(x)= (x - 2)/4.',
      'answers': ['4x+2', '(4x+2)', '(x+2)/4', '(x+2)*4'],
      'correct': '(4x+2)',
    },
    {
      'name': 'T5P6',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'If f(x)= x² and g(x)= x+3, find (f ∘ g)(x).',
      'answers': ['(x+3)²', 'x²+3', 'x²+6x+9', 'x²+9'],
      'correct': '(x+3)²',
    },
    {
      'name': 'T5P7',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'If f(x)= x - 1 and g(x)= 2x, find (g ∘ f)(x).',
      'answers': ['2x - 2', '2x - 1', '2x - 3', '2x+1'],
      'correct': '2(x - 1)',
    },
    {
      'name': 'T5P8',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 4,
      'content': 'Find the inverse of f(x)= 1/x.',
      'answers': ['f⁻¹(x)=1/x', 'f⁻¹(x)=x', 'f⁻¹(x)=1/(x-1)', 'f⁻¹(x)= -1/x'],
      'correct': 'f⁻¹(x)=1/x',
    },
    {
      'name': 'T5P9',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'If f(x)= 2x+1 and g(x)= 3x, find (g ∘ f)(x).',
      'answers': ['6x+3', '6x+1', '6x+5', '6x+4'],
      'correct': '6x+3',
    },
    {
      'name': 'T5P10',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Find the inverse of f(x)= x + 7.',
      'answers': ['x - 7', 'x + 7', '(x - 7)', '(x+7)'],
      'correct': 'x - 7',
    },
    {
      'name': 'T5P11',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'If f(x)= x² and g(x)= x - 2, find (f ∘ g)(x).',
      'answers': ['(x-2)²', 'x² - 2', 'x² - 4x + 4', 'x²-2x+4'],
      'correct': '(x-2)²',
    },
    {
      'name': 'T5P12',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Find the inverse of f(x)= 4x - 8.',
      'answers': ['(x+8)/4', '(x+2)/4', '(x+2)/4', '(x+?)/4'],
      'correct': '(x+2)/4',
    },
    {
      'name': 'T5P13',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Find (f ∘ g)(3) if f(x)= x+4 and g(x)= x².',
      'answers': ['13','16','19','25'],
      'correct': '13',
    },
    {
      'name': 'T5P14',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Find the inverse of f(x)= (x+1)/3.',
      'answers': ['3x-1','(3x-1)','(x-1)/3','(x+1)/3'],
      'correct': '(3x-1)',
    },
    {
      'name': 'T5P15',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'If f(x)= 3x and g(x)= x/2, find (f ∘ g)(x).',
      'answers': ['(3x)/2','(3/2)x','(x)/2','3x^2'],
      'correct': '(3/2)x',
    },
    {
      'name': 'T5P16',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Find the inverse of f(x)= 5 - x.',
      'answers': ['5 - x','x - 5','5 - x','-(x - 5)'],
      'correct': '5 - x',
    },
    {
      'name': 'T5P17',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'If f(x)= 2x + 3 and g(x)= x - 5, find (g ∘ f)(2).',
      'answers': ['x = 2','x = 3','x = 4','x = 5'],
      'correct': 'x = 2',
    },
    {
      'name': 'T5P18',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Find the inverse of f(x)= x/4.',
      'answers': ['4x','x/4','4/x','x*4'],
      'correct': '4x',
    },
    {
      'name': 'T5P19',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'If f(x)= x³ and g(x)= x^(1/3), find (f ∘ g)(x).',
      'answers': ['x','x^(4/3)','x^3','x^(1/3)'],
      'correct': 'x',
    },
    {
      'name': 'T5P20',
      'category': 'Intermediate Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'If f(x)= 2x - 1 and g(x)= x², find (f ∘ g)(x).',
      'answers': ['2x² - 1','2x - 1','x² - 1','2x² + 1'],
      'correct': '2x - 1',
    },

    // Topic 6: Zeros of polynomial equations (20 problems)
    {
      'name': 'T6P1',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= x² - 5x + 6.',
      'answers': 'x = 2 and x = 3; x = 1 and x = 6; x = -2 and x = -3; x = 2 and x = -3',
      'correct': 'x = 2 and x = 3',
    },
    {
      'name': 'T6P2',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 1,
      'content': 'Find the zeros of f(x)= x² - 4.',
      'answers': 'x = -2,2; x = 0; x = -4,4; x = 2,4',
      'correct': 'x = -2,2',
    },
    {
      'name': 'T6P3',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= x³ - x² - x + 1.',
      'answers': ['x = 1 (triple zero)', 'x = 1 and x = -1', 'x = 0 and x = 1', 'x = -1, 0, 1'],
      'correct': 'x = 1 and x = -1',
    },
    {
      'name': 'T6P4',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= 2x² - 8.',
      'answers': 'x = -2,2; x = -4,4; x = 0; x = -1,1',
      'correct': 'x = -2,2',
    },
    {
      'name': 'T6P5',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= x² + x - 6.',
      'answers': 'x = 2 and x = -3; x = 3 and x = -2; x = 1 and x = -6; x = -1 and x = 6',
      'correct': 'x = 2 and x = -3',
    },
    {
      'name': 'T6P6',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= 3x² - 12.',
      'answers': 'x = -2,2; x = 0; x = -4,4; x = 2',
      'correct': 'x = -2,2',
    },
    {
      'name': 'T6P7',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= x³ - 3x.',
      'answers': 'x = -√3, 0, √3; x = -3,0,3; x = -1,0,1; x = 1,2,3',
      'correct': 'x = -√3, 0, √3',
    },
    {
      'name': 'T6P8',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 1,
      'content': 'Find the zeros of f(x)= x² - 9.',
      'answers': 'x = -3,3; x = 0; x = -9,9; x = -1,1',
      'correct': 'x = -3,3',
    },
    {
      'name': 'T6P9',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= 2x² - 3x - 5.',
      'answers': ['x = 5/2 and x = -1', 'x = 2 and x = -1.25', 'x = -1 and x = 2.5', 'x = 1 and x = -5'],
      'correct': 'x = -1 and x = 2.5',
    },
    {
      'name': 'T6P10',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= x² - 2x.',
      'answers': 'x = 0 and x = 2; x = 1 and x = -1; x = 2; x = 0',
      'correct': 'x = 0 and x = 2',
    },
    {
      'name': 'T6P11',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= x² - 4x + 4.',
      'answers': 'x = 2 (double zero); x = 0 and x = 4; x = 2 and x = -2; x = 1 and x = 3',
      'correct': 'x = 2 (double zero)',
    },
    {
      'name': 'T6P12',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= 4x² - 25.',
      'answers': 'x = 5/2 and x = -5/2; x = 0; x = 5 and x = -5; x = 2 and x = -2',
      'correct': 'x = 5/2 and x = -5/2',
    },
    {
      'name': 'T6P13',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= x³ - 6x² + 11x - 6.',
      'answers': 'x = 1, 2, 3; x = 0, 1, 6; x = 1, -2, 3; x = -1, 2, 3',
      'correct': 'x = 1, 2, 3',
    },
    {
      'name': 'T6P14',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 4,
      'content': 'Find the zeros of f(x)= 2x³ - 3x² - 8x + 12.',
      'answers': ['x = 2; x = 1; x = -3', 'x = 2; x = -1; x = 2.5', 'x = -2; x = 1; x = 3', 'x = 2; x = -1; x = 2.5'],
      'correct': 'x = 2; x = -1; x = 2.5',
    },
    {
      'name': 'T6P15',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= x² + 2x - 8.',
      'answers': 'x = 2 and x = -4; x = -2 and x = 4; x = 2 and x = 4; x = -2 and x = -4',
      'correct': 'x = 2 and x = -4',
    },
    {
      'name': 'T6P16',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the zeros of f(x)= 3x² - x - 2.',
      'answers': ['x = 1 and x = -2/3','x = -1 and x = 2/3','x = 2 and x = -1','x = -2 and x = 1/3'],
      'correct': 'x = 1 and x = -2/3',
    },
    {
      'name': 'T6P17',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= x³ - x.',
      'answers': 'x = -1, 0, 1; x = 0; x = -1, 1; x = -2, 0, 2',
      'correct': 'x = -1, 0, 1',
    },
    {
      'name': 'T6P18',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 1,
      'content': 'Find the zeros of f(x)= x² - 1.',
      'answers': 'x = -1 and x = 1; x = 0; x = -2 and x = 2; x = 1',
      'correct': 'x = -1 and x = 1',
    },
    {
      'name': 'T6P19',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= 2x² - 4x.',
      'answers': 'x = 0 and x = 2; x = 2; x = -2 and x = 2; x = 0',
      'correct': 'x = 0 and x = 2',
    },
    {
      'name': 'T6P20',
      'category': 'Intermediate Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find the zeros of f(x)= x² - 16.',
      'answers': 'x = -4 and x = 4; x = 4; x = -4; x = 0',
      'correct': 'x = -4 and x = 4',
    },

    // Topic 7: Graphing polynomial and rational functions (intercepts and asymptotes) – 20 problems
    {
      'name': 'T7P1',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the vertical asymptote of f(x)= 1/(x - 2).',
      'answers': 'x = 2; x = -2; x = 0; None',
      'correct': 'x = 2',
    },
    {
      'name': 'T7P2',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the x-intercepts of f(x)= x² - 4.',
      'answers': 'x = -2, 2; x = 0; x = -4,4; x = 2,4',
      'correct': 'x = -2, 2',
    },
    {
      'name': 'T7P3',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the y-intercept of f(x)= (2x+3)/(x - 1).',
      'answers': 'y = -3; y = 3; y = -2; y = 2',
      'correct': 'y = 3',
    },
    {
      'name': 'T7P4',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the horizontal asymptote of f(x)= (3x+5)/(x+2).',
      'answers': 'y = 3; y = 5; y = 0; y = 1',
      'correct': 'y = 3',
    },
    {
      'name': 'T7P5',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Find the vertical asymptote of f(x)= (x+1)/(x² - 4).',
      'answers': 'x = 2 and x = -2; x = 2; x = -2; None',
      'correct': 'x = 2 and x = -2',
    },
    {
      'name': 'T7P6',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the x-intercepts of f(x)= x³ - x.',
      'answers': 'x = -1, 0, 1; x = 0; x = -1 and 1; x = 2',
      'correct': 'x = -1, 0, 1',
    },
    {
      'name': 'T7P7',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Determine the intercepts of f(x)= (x-2)²/(x+3).',
      'answers': 'x-intercept: 2; y-intercept: 4/3; Others',
      'correct': 'x-intercept: 2; y-intercept: 4/3',
    },
    {
      'name': 'T7P8',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Find the horizontal asymptote of f(x)= (2x²+3)/(x²-1).',
      'answers': 'y = 2; y = 3; y = 0; y = 1',
      'correct': 'y = 2',
    },
    {
      'name': 'T7P9',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the x-intercepts of f(x)= (x²-9)/(x+1).',
      'answers': 'x = -3, 3; x = 0; x = 3; x = -3',
      'correct': 'x = -3, 3',
    },
    {
      'name': 'T7P10',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the vertical asymptote of f(x)= 1/(x² - 1).',
      'answers': 'x = 1 and x = -1; x = 0; None; x = 2',
      'correct': 'x = 1 and x = -1',
    },
    {
      'name': 'T7P11',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Determine the intercepts of f(x)= (x²-1)/(x-1).',
      'answers': 'x = 2 (with hole at x=1); Others',
      'correct': 'x = 2 (with hole at x=1)',
    },
    {
      'name': 'T7P12',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the horizontal asymptote of f(x)= (5x-2)/(2x+3).',
      'answers': 'y = 5/2; y = 2; y = 3; y = 0',
      'correct': 'y = 5/2',
    },
    {
      'name': 'T7P13',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the x-intercepts of f(x)= x(x-4).',
      'answers': 'x = 0 and x = 4; x = 4; x = 0; x = -4 and 0',
      'correct': 'x = 0 and x = 4',
    },
    {
      'name': 'T7P14',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the vertical asymptote of f(x)= (2x+1)/(x-3).',
      'answers': 'x = 3; x = -3; x = 2; None',
      'correct': 'x = 3',
    },
    {
      'name': 'T7P15',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Find the horizontal asymptote of f(x)= (3x²-2)/(x²+4).',
      'answers': 'y = 3; y = -3; y = 0; y = 1',
      'correct': 'y = 3',
    },
    {
      'name': 'T7P16',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Determine the intercepts of f(x)= (x²-4)/(x+2).',
      'answers': 'x = -2 (hole), x = 2; x = 2; Others',
      'correct': 'x = 2, with a hole at x = -2',
    },
    {
      'name': 'T7P17',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the vertical asymptote of f(x)= (x+3)/(x²-9).',
      'answers': 'x = 3 and x = -3; x = 0; x = -3; x = 3',
      'correct': 'x = 3 and x = -3',
    },
    {
      'name': 'T7P18',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the x-intercepts of f(x)= x² - 5x + 6.',
      'answers': 'x = 2 and x = 3; x = 1 and x = 6; x = 3; x = 2',
      'correct': 'x = 2 and x = 3',
    },
    {
      'name': 'T7P19',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Find the horizontal asymptote of f(x)= (x³+2)/(2x³-3).',
      'answers': 'y = 1/2; y = 2; y = 0; y = ∞',
      'correct': 'y = 1/2',
    },
    {
      'name': 'T7P20',
      'category': 'Intermediate Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Determine the intercepts of f(x)= (2x - 4)/(x - 2).',
      'answers': 'x-intercept: 2; y-intercept: -4; Others',
      'correct': 'x-intercept: 2, with a hole at x = 2',
    },

    // Topic 8: Analyze exponential and logarithmic functions – 20 problems
    {
      'name': 'T8P1',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the domain of f(x)= log(x - 1).',
      'answers': 'x > 1; x ≥ 1; all real; x < 1',
      'correct': 'x > 1',
    },
    {
      'name': 'T8P2',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the range of f(x)= e^x.',
      'answers': 'y > 0; y ≥ 0; all real; y < 0',
      'correct': 'y > 0',
    },
    {
      'name': 'T8P3',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 1,
      'content': 'Determine the domain of f(x)= e^(-x).',
      'answers': 'all real numbers; x > 0; x < 0; x ≠ 0',
      'correct': 'all real numbers',
    },
    {
      'name': 'T8P4',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the range of f(x)= log(x).',
      'answers': 'all real numbers; y ≥ 0; y > 0; y ≤ 0',
      'correct': 'all real numbers',
    },
    {
      'name': 'T8P5',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the domain of f(x)= 2^(x - 3).',
      'answers': 'all real numbers; x > 3; x ≥ 3; x < 3',
      'correct': 'all real numbers',
    },
    {
      'name': 'T8P6',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Find the horizontal asymptote of f(x)= e^(-x).',
      'answers': 'y = 0; y = 1; y = -1; none',
      'correct': 'y = 0',
    },
    {
      'name': 'T8P7',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the domain of f(x)= log₂(x + 2).',
      'answers': 'x > -2; x ≥ -2; all real; x < -2',
      'correct': 'x > -2',
    },
    {
      'name': 'T8P8',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 1,
      'content': 'Determine the range of f(x)= 10^x.',
      'answers': 'y > 0; y ≥ 0; all real; y < 0',
      'correct': 'y > 0',
    },
    {
      'name': 'T8P9',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the domain of f(x)= ln(x + 5).',
      'answers': 'x > -5; x ≥ -5; all real; x < -5',
      'correct': 'x > -5',
    },
    {
      'name': 'T8P10',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 1,
      'content': 'Determine the range of f(x)= log₁₀(x).',
      'answers': 'all real numbers; y ≥ 0; y > 0; y < 0',
      'correct': 'all real numbers',
    },
    {
      'name': 'T8P11',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 1,
      'content': 'Determine the domain of f(x)= e^(x) + 3.',
      'answers': 'all real numbers; x > 0; x < 0; none',
      'correct': 'all real numbers',
    },
    {
      'name': 'T8P12',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Find the horizontal asymptote of f(x)= 2^(-x).',
      'answers': 'y = 0; y = 1; none; y = -1',
      'correct': 'y = 0',
    },
    {
      'name': 'T8P13',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Determine the domain of f(x)= log(x²).',
      'answers': 'x ≠ 0; all real; x > 0; x < 0',
      'correct': 'x ≠ 0',
    },
    {
      'name': 'T8P14',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the range of f(x)= e^(x) - 1.',
      'answers': 'y > -1; y ≥ -1; all real; y < -1',
      'correct': 'y > -1',
    },
    {
      'name': 'T8P15',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the domain of f(x)= log(2x+1).',
      'answers': 'x > -0.5; x ≥ -0.5; all real; x < -0.5',
      'correct': 'x > -0.5',
    },
    {
      'name': 'T8P16',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Find the horizontal asymptote of f(x)= e^(-x) + 2.',
      'answers': 'y = 2; y = 0; y = 1; none',
      'correct': 'y = 2',
    },
    {
      'name': 'T8P17',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the domain of f(x)= ln(x - 2).',
      'answers': 'x > 2; x ≥ 2; all real; x < 2',
      'correct': 'x > 2',
    },
    {
      'name': 'T8P18',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Determine the range of f(x)= 2^(x) + 1.',
      'answers': 'y > 1; y ≥ 1; all real; y < 1',
      'correct': 'y > 1',
    },
    {
      'name': 'T8P19',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 1,
      'content': 'Determine the domain of f(x)= log₂(x).',
      'answers': 'x > 0; all real; x ≥ 0; x < 0',
      'correct': 'x > 0',
    },
    {
      'name': 'T8P20',
      'category': 'Intermediate Algebra',
      'topic': 8,
      'difficulty': 1,
      'content': 'Find the horizontal asymptote of f(x)= 3^(-x).',
      'answers': 'y = 0; y = 3; none; y = 1',
      'correct': 'y = 0',
    },

    // Topic 9: Evaluate exponential and logarithmic expressions – 20 problems
    {
      'name': 'T9P1',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 2^3.',
      'answers': '8;6;10;9',
      'correct': '8',
    },
    {
      'name': 'T9P2',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: log₁₀(100).',
      'answers': '1;2;3;4',
      'correct': '2',
    },
    {
      'name': 'T9P3',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: e^0.',
      'answers': '0;1;e;Undefined',
      'correct': '1',
    },
    {
      'name': 'T9P4',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: ln(e).',
      'answers': '0;1;e;Undefined',
      'correct': '1',
    },
    {
      'name': 'T9P5',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 3^2.',
      'answers': '6;7;8;9',
      'correct': '9',
    },
    {
      'name': 'T9P6',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: log₂(8).',
      'answers': '2;3;4;5',
      'correct': '3',
    },
    {
      'name': 'T9P7',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 10^2.',
      'answers': '50;75;100;125',
      'correct': '100',
    },
    {
      'name': 'T9P8',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 2^0.',
      'answers': '0;1;2;Undefined',
      'correct': '1',
    },
    {
      'name': 'T9P9',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: ln(1).',
      'answers': '0;1;Undefined;e',
      'correct': '0',
    },
    {
      'name': 'T9P10',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: log₁₀(1000).',
      'answers': '2;3;4;5',
      'correct': '3',
    },
    {
      'name': 'T9P11',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 5^3.',
      'answers': '100;120;125;130',
      'correct': '125',
    },
    {
      'name': 'T9P12',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 3^3.',
      'answers': '26;27;28;29',
      'correct': '27',
    },
    {
      'name': 'T9P13',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Evaluate: log₄(64).',
      'answers': '2;3;4;5',
      'correct': '3',
    },
    {
      'name': 'T9P14',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 4^2.',
      'answers': '14;15;16;18',
      'correct': '16',
    },
    {
      'name': 'T9P15',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Evaluate: e^2 (approx).',
      'answers': ['6.39','7.39','7.39','8.39'],
      'correct': '7.39',
    },
    {
      'name': 'T9P16',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Evaluate: ln(e^3).',
      'answers': '1;2;3;4',
      'correct': '3',
    },
    {
      'name': 'T9P17',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 2^4.',
      'answers': '14;15;16;17',
      'correct': '16',
    },
    {
      'name': 'T9P18',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: log₂(16).',
      'answers': '2;3;4;5',
      'correct': '4',
    },
    {
      'name': 'T9P19',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 10^0.',
      'answers': '0;1;10;Undefined',
      'correct': '1',
    },
    {
      'name': 'T9P20',
      'category': 'Intermediate Algebra',
      'topic': 9,
      'difficulty': 1,
      'content': 'Evaluate: 3^0.',
      'answers': '0;1;3;Undefined',
      'correct': '1',
    },

    // Topic 10: Solve exponential and logarithmic equations/applications – 20 problems
    {
      'name': 'T10P1',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: 2^x = 16.',
      'answers': 'x = 3;x = 4;x = 5;x = 6',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P2',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₁₀(x) = 2.',
      'answers': 'x = 50;x = 75;x = 100;x = 125',
      'correct': 'x = 100',
    },
    {
      'name': 'T10P3',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: e^x = e^3.',
      'answers': 'x = 2;x = 3;x = 4;x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P4',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: 3^x = 27.',
      'answers': 'x = 2;x = 3;x = 4;x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P5',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₂(x) = 5.',
      'answers': 'x = 16;x = 32;x = 64;x = 128',
      'correct': 'x = 32',
    },
    {
      'name': 'T10P6',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: 10^x = 1000.',
      'answers': 'x = 2;x = 3;x = 4;x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P7',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: 2^(x+1) = 32.',
      'answers': 'x = 3;x = 4;x = 5;x = 6',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P8',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₃(x) = 4.',
      'answers': 'x = 81;x = 64;x = 27;x = 16',
      'correct': 'x = 81',
    },
    {
      'name': 'T10P9',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve for x: 3^(x+2) = 81.',
      'answers': 'x = 0;x = 1;x = 2;x = 3',
      'correct': 'x = 1',
    },
    {
      'name': 'T10P10',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₂(x+1) = 3.',
      'answers': 'x = 5;x = 6;x = 7;x = 8',
      'correct': 'x = 7',
    },
    {
      'name': 'T10P11',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: 2^(2x) = 64.',
      'answers': 'x = 2;x = 3;x = 4;x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P12',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₁₀(2x) = 1.',
      'answers': 'x = 4;x = 5;x = 6;x = 7',
      'correct': 'x = 5',
    },
    {
      'name': 'T10P13',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve for x: e^(x-1) = 7.389.',
      'answers': 'x = 1;x = 2;x = 3;x = 4',
      'correct': 'x = 2',
    },
    {
      'name': 'T10P14',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: 4^x = 64.',
      'answers': 'x = 2;x = 3;x = 4;x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P15',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₂(8x) = 6.',
      'answers': 'x = 7;x = 8;x = 9;x = 10',
      'correct': 'x = 8',
    },
    {
      'name': 'T10P16',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: 2^x = 8.',
      'answers': 'x = 2;x = 3;x = 4;x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P17',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: log₁₀(x/2) = 1.',
      'answers': 'x = 10;x = 20;x = 30;x = 40',
      'correct': 'x = 20',
    },
    {
      'name': 'T10P18',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: e^(2x) = 7.389.',
      'answers': 'x = 0.5;x = 1;x = 1.5;x = 2',
      'correct': 'x = 1',
    },
    {
      'name': 'T10P19',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: 3^x = 9.',
      'answers': 'x = 1;x = 2;x = 3;x = 4',
      'correct': 'x = 2',
    },
    {
      'name': 'T10P20',
      'category': 'Intermediate Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: 2^x = 16.',
      'answers': 'x = 3;x = 4;x = 5;x = 6',
      'correct': 'x = 4',
    },

    // Topic 11: Analyze and graph conic sections – 20 problems
    {
      'name': 'T11P1',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'Find the vertex of the parabola: y = (x - 2)² - 3.',
      'answers': '(2, -3); (-2, 3); (2, 3); (-2, -3)',
      'correct': '(2, -3)',
    },
    {
      'name': 'T11P2',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the ellipse x²/25 + y²/9 = 1, find the foci.',
      'answers': ['(±3, 0)', '(±4, 0)', '(0, ±3)', '(0, ±4)'],
      'correct': '(±3, 0)',
    },
    {
      'name': 'T11P3',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the hyperbola x²/16 - y²/9 = 1, state the equation of its asymptotes.',
      'answers': ['y = ±(3/4)x', 'y = ±(4/3)x', 'y = ±x', 'y = ±2x'],
      'correct': 'y = ±(3/4)x',
    },
    {
      'name': 'T11P4',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the circle (x - 1)² + (y + 2)² = 16, find its center and radius.',
      'answers': ['Center: (1, -2), Radius: 4', 'Center: (-1, 2), Radius: 4', 'Center: (1, 2), Radius: 4', 'Center: (-1, -2), Radius: 4'],
      'correct': 'Center: (1, -2), Radius: 4',
    },
    {
      'name': 'T11P5',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the parabola y = -2(x + 1)² + 5, find its vertex.',
      'answers': ['(-1, 5)', '(-1, -5)', '(1, 5)', '(1, -5)'],
      'correct': '(-1, 5)',
    },
    {
      'name': 'T11P6',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the ellipse x²/9 + y²/4 = 1, find the foci.',
      'answers': ['(±√5, 0)', '(±2, 0)', '(0, ±√5)', '(0, ±2)'],
      'correct': '(±√5, 0)',
    },
    {
      'name': 'T11P7',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the hyperbola y²/16 - x²/9 = 1, find its vertices.',
      'answers': ['(0, ±4)', '(±4, 0)', '(0, ±3)', '(±3, 0)'],
      'correct': '(0, ±4)',
    },
    {
      'name': 'T11P8',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the parabola x² = 4y, state its vertex.',
      'answers': ['(0,0)', '(4,0)', '(0,4)', '(2,2)'],
      'correct': '(0,0)',
    },
    {
      'name': 'T11P9',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 1,
      'content': 'For the circle x² + y² = 49, find its radius.',
      'answers': ['7','6','5','4'],
      'correct': '7',
    },
    {
      'name': 'T11P10',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the ellipse (x - 2)²/16 + (y + 3)²/9 = 1, what are the coordinates of the vertices along the major axis?',
      'answers': ['(2±4, -3)', '(2, -3±4)', '(2±3, -3)', '(2, -3±3)'],
      'correct': '(2±4, -3)',
    },
    {
      'name': 'T11P11',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the hyperbola (y - 1)²/9 - (x + 2)²/4 = 1, find its vertices.',
      'answers': ['(-2, 1±3)', '(±2, 1)', '( -2±?, 1)', 'None'],
      'correct': '(-2, 1±3)',
    },
    {
      'name': 'T11P12',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the parabola y = 3(x + 1)² - 2, find its vertex.',
      'answers': ['(-1, -2)', '(-1, 2)', '(1, -2)', '(1, 2)'],
      'correct': '(-1, -2)',
    },
    {
      'name': 'T11P13',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the circle (x + 3)² + (y - 4)² = 36, find its center and radius.',
      'answers': ['Center: (-3, 4), Radius: 6', 'Center: (3, -4), Radius: 6', 'Center: (-3, -4), Radius: 6', 'Center: (3, 4), Radius: 6'],
      'correct': 'Center: (-3, 4), Radius: 6',
    },
    {
      'name': 'T11P14',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'For the ellipse x²/49 + y²/25 = 1, find the foci (approximate).',
      'answers': ['(±√24, 0)', '(±5, 0)', '(0, ±√24)', '(0, ±5)'],
      'correct': '(±√24, 0)',
    },
    {
      'name': 'T11P15',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the hyperbola x²/9 - y²/4 = 1, find its vertices.',
      'answers': ['(±3, 0)', '(0, ±2)', '(±2, 0)', 'None'],
      'correct': '(±3, 0)',
    },
    {
      'name': 'T11P16',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the parabola y = -(x - 3)² + 6, find its vertex.',
      'answers': ['(3,6)', '(3,-6)', '(-3,6)', '(-3,-6)'],
      'correct': '(3,6)',
    },
    {
      'name': 'T11P17',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 1,
      'content': 'For the circle (x - 2)² + (y + 1)² = 9, find its center.',
      'answers': ['(2,-1)','(-2,1)','(2,1)','(-2,-1)'],
      'correct': '(2,-1)',
    },
    {
      'name': 'T11P18',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the ellipse (x + 1)²/4 + (y - 2)²/9 = 1, find its center.',
      'answers': ['(-1,2)','(1,-2)','(-1,-2)','(1,2)'],
      'correct': '(-1,2)',
    },
    {
      'name': 'T11P19',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the hyperbola y²/16 - x²/9 = 1, find its vertices.',
      'answers': ['(0, ±4)','(±4,0)','(0, ±3)','(±3,0)'],
      'correct': '(0, ±4)',
    },
    {
      'name': 'T11P20',
      'category': 'Intermediate Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'For the parabola x = -0.5(y - 2)² + 3, find its vertex.',
      'answers': ['(3,2)','(-3,2)','(3,-2)','(-3,-2)'],
      'correct': '(3,2)',
    },

    // Topic 12: Applications involving conic sections – 20 problems
    {
      'name': 'T12P1',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A satellite dish is parabolic: y = a(x - 1)². If the dish is 4 units deep and 8 units wide at the top, find a.',
      'answers': ['a = -0.5','a = 0.5','a = -1','a = 1'],
      'correct': 'a = -0.5',
    },
    {
      'name': 'T12P2',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'A circular garden has an area of 78.5 square units. What is its diameter? (Use π = 3.14)',
      'answers': ['10','8','9','7'],
      'correct': '10',
    },
    {
      'name': 'T12P3',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A baseball field is shaped like a half-ellipse with a major axis of 100 and minor axis of 80. Approximate its area.',
      'answers': ['6280','628','3140','1570'],
      'correct': '3140',
    },
    {
      'name': 'T12P4',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 4,
      'content': 'An ellipse has foci at (±3, 0) and a major axis length of 10. Write its equation.',
      'answers': ['(x²/16)+(y²/9)=1','(x²/9)+(y²/16)=1','(x²/25)+(y²/9)=1','(x²/16)+(y²/25)=1'],
      'correct': '(x²/16)+(y²/9)=1',
    },
    {
      'name': 'T12P5',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 4,
      'content': 'A hyperbola has vertices at (0, ±4) and asymptote slope 2. Write its equation in standard form.',
      'answers': ['y²/16 - x²/9 = 1','x²/16 - y²/9 = 1','y²/9 - x²/16 = 1','x²/9 - y²/16 = 1'],
      'correct': 'y²/16 - x²/9 = 1',
    },
    {
      'name': 'T12P6',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'A parabolic arch is described by y = -0.5x² + 10. What is its maximum height?',
      'answers': ['10','8','5','12'],
      'correct': '10',
    },
    {
      'name': 'T12P7',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A satellite dish has a parabolic shape with vertex (0, 10) and passes through (2, 8). Find its equation.',
      'answers': ['y = -0.5x² + 10','y = -x² + 10','y = -0.5x² + 8','y = -x² + 8'],
      'correct': 'y = -0.5x² + 10',
    },
    {
      'name': 'T12P8',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'A circular fountain has a circumference of 31.4 units. What is its radius? (Use π = 3.14)',
      'answers': ['5','4','6','7'],
      'correct': '5',
    },
    {
      'name': 'T12P9',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A garden is an ellipse with area 50 square units and a minor axis of length 4. Find the major axis length (approx.).',
      'answers': ['10','12','14','16'],
      'correct': '12',
    },
    {
      'name': 'T12P10',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A parabola has vertex (2, 3) and passes through (4, 7). Find its equation.',
      'answers': ['y = a(x - 2)² + 3, a = 0.5','y = a(x - 2)² + 3, a = 1','y = a(x - 2)² + 3, a = -0.5','y = a(x - 2)² + 3, a = -1'],
      'correct': 'y = a(x - 2)² + 3, a = 0.5',
    },
    {
      'name': 'T12P11',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 4,
      'content': 'A hyperbola has foci at (0, ±5) and vertices at (0, ±3). Write its equation.',
      'answers': ['y²/9 - x²/4 = 1','x²/9 - y²/4 = 1','y²/4 - x²/9 = 1','x²/4 - y²/9 = 1'],
      'correct': 'y²/9 - x²/4 = 1',
    },
    {
      'name': 'T12P12',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 4,
      'content': 'Given an ellipse with center (1, -2), vertices at (1, 2), and co-vertices at (-1, -2), write its equation.',
      'answers': ['(x-1)²/4 + (y+2)²/16 = 1','(x-1)²/16 + (y+2)²/4 = 1','(x-1)²/9 + (y+2)²/16 = 1','(x-1)²/16 + (y+2)²/9 = 1'],
      'correct': '(x-1)²/4 + (y+2)²/16 = 1',
    },
    {
      'name': 'T12P13',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A parabolic window is 6 units wide and 2 units high. Find an equation for the parabola (vertex form) that models it.',
      'answers': ['y = -0.5(x)²+2','y = -0.5(x)²+1','y = -0.5(x)²+0','y = -x²+2'],
      'correct': 'y = -0.5x²+2',
    },
    {
      'name': 'T12P14',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'A circular fountain has an area of 50.24 square units. What is its radius? (Use π = 3.14)',
      'answers': ['4','5','6','7'],
      'correct': '4',
    },
    {
      'name': 'T12P15',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A parabolic arch has equation y = -x² + 4. What is its width at ground level (y=0)?',
      'answers': ['4','2','6','8'],
      'correct': '4',
    },
    {
      'name': 'T12P16',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 4,
      'content': 'A track is shaped like an ellipse with a major axis of 200 units and a minor axis of 100 units. Approximate its area.',
      'answers': ['15700','15708','15710','15720'],
      'correct': '15708',
    },
    {
      'name': 'T12P17',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 5,
      'content': 'A hyperbola has asymptotes y = ±x. If it passes through (2, 0), approximate its equation.',
      'answers': ['x²/4 - y²/4 = 1','x²/4 - y²/4 = -1','y²/4 - x²/4 = 1','x²/2 - y²/2 = 1'],
      'correct': 'x²/4 - y²/4 = 1',
    },
    {
      'name': 'T12P18',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'A parabolic window has vertex (2,3) and passes through (4,7). Find its equation.',
      'answers': ['y = a(x-2)² + 3, a = 0.5','y = a(x-2)² + 3, a = 1','y = a(x-2)² + 3, a = -0.5','y = a(x-2)² + 3, a = -1'],
      'correct': 'y = a(x-2)² + 3, a = 0.5',
    },
    {
      'name': 'T12P19',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'A circle has a diameter of 10 units. What is its area? (Use π = 3.14)',
      'answers': ['78.5','80','81','82'],
      'correct': '78.5',
    },
    {
      'name': 'T12P20',
      'category': 'Intermediate Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'A hyperbola has equation x²/16 - y²/9 = 1. Find the distance between its vertices.',
      'answers': ['4','6','8','10'],
      'correct': '4',
    },

    // Topic 13: Solve non-linear systems using substitution and elimination – 20 problems
    {
      'name': 'T13P1',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² + y = 10, y - x = 2 }.',
      'answers': ['x = 2, y = 4; x = 1, y = 3; x = 3, y = 5; x = -1, y = 1'],
      'correct': 'x = 2, y = 4',
    },
    {
      'name': 'T13P2',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { x² + y² = 25, y = x + 1 }.',
      'answers': ['x = 3, y = 4; x = -3, y = -2; x = 4, y = 5; x = -4, y = -3'],
      'correct': 'x = 3, y = 4',
    },
    {
      'name': 'T13P3',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { y = x², x + y = 6 }.',
      'answers': ['x = 2, y = 4; x = 1, y = 1; x = 3, y = 9; x = -2, y = 4'],
      'correct': 'x = 2, y = 4',
    },
    {
      'name': 'T13P4',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² - y = 3, x + y = 5 }.',
      'answers': ['x = 2, y = 3; x = 3, y = 2; x = 1, y = 4; x = -1, y = 6'],
      'correct': 'x = 3, y = 2',
    },
    {
      'name': 'T13P5',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { x² + y² = 13, y = 2x - 1 }.',
      'answers': ['x = 2, y = 3; x = 3, y = 5; x = 1, y = 1; x = -2, y = -5'],
      'correct': 'x = 2, y = 3',
    },
    {
      'name': 'T13P6',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { y = x² - 4, y = 2x - 3 }.',
      'answers': ['x = 1, y = -1; x = 2, y = 1; x = 3, y = 3; x = -1, y = -5'],
      'correct': 'x = 2, y = 1',
    },
    {
      'name': 'T13P7',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² + y = 7, y = x + 1 }.',
      'answers': ['x = 2, y = 3; x = 3, y = 4; x = 1, y = 2; x = -2, y = -1'],
      'correct': 'x = 2, y = 3',
    },
    {
      'name': 'T13P8',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { x² - y² = 9, x - y = 3 }.',
      'answers': ['x = 3, y = 0; x = 4, y = 1; x = -3, y = -6; x = 3, y = 0'],
      'correct': 'x = 3, y = 0',
    },
    {
      'name': 'T13P9',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { y = 3x², x + y = 4 }.',
      'answers': ['x = 1, y = 3; x = 0, y = 0; x = 1, y = 3; x = -1, y = 3'],
      'correct': 'x = 1, y = 3',
    },
    {
      'name': 'T13P10',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² + y = 8, y = x - 2 }.',
      'answers': ['x = 4, y = 2; x = 3, y = 1; x = 2, y = 0; x = -2, y = -4'],
      'correct': 'x = 3, y = 1',
    },
    {
      'name': 'T13P11',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { x² + y² = 10, x - y = 1 }.',
      'answers': ['x = 2, y = 1; x = 3, y = 2; x = 1, y = 0; x = -2, y = -3'],
      'correct': 'x = 2, y = 1',
    },
    {
      'name': 'T13P12',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { y = x² + 2, x + y = 5 }.',
      'answers': ['x = 1, y = 3; x = 2, y = 6; x = 0, y = 2; x = -1, y = 1'],
      'correct': 'x = 1, y = 3',
    },
    {
      'name': 'T13P13',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² - y = 2, 2x + y = 6 }.',
      'answers': ['x = 2, y = 2; x = 1, y = 4; x = 2, y = 2; x = 3, y = 0'],
      'correct': 'x = 2, y = 2',
    },
    {
      'name': 'T13P14',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { y = x², y = 4 - x }.',
      'answers': ['x = 2, y = 4; x = 1, y = 3; x = -2, y = 8; x = 1, y = 3'],
      'correct': 'x = 1, y = 3',
    },
    {
      'name': 'T13P15',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² + y = 11, x - y = 1 }.',
      'answers': ['x = 3, y = 2; x = 2, y = 1; x = 4, y = 3; x = 1, y = 0'],
      'correct': 'x = 3, y = 2',
    },
    {
      'name': 'T13P16',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { y = x² - 1, x + y = 3 }.',
      'answers': ['x = 2, y = 3; x = 1, y = 0; x = 2, y = 3; x = 1, y = 0'],
      'correct': 'x = 2, y = 1',
    },
    {
      'name': 'T13P17',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { x² + y² = 20, y = 2x }.',
      'answers': ['x = 2, y = 4 and x = -2, y = -4; x = 3, y = 6; x = 1, y = 2; x = -3, y = -6'],
      'correct': 'x = 2, y = 4 and x = -2, y = -4',
    },
    {
      'name': 'T13P18',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { y = x² - 3, x + y = 1 }.',
      'answers': ['x = 2, y = 1; x = 1, y = -2; x = -1, y = -4; x = 2, y = -1'],
      'correct': 'x = 1, y = -2',
    },
    {
      'name': 'T13P19',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve the system: { x² + y = 12, 2x - y = 3 }.',
      'answers': ['x = 3, y = 3; x = 2, y = 8; x = 3, y = 3; x = 4, y = 4'],
      'correct': 'x = 3, y = 3',
    },
    {
      'name': 'T13P20',
      'category': 'Intermediate Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve the system: { x² - y = 4, x + y = 6 }.',
      'answers': ['x = 2, y = 4; x = 3, y = 3; x = 4, y = 2; x = 1, y = 5'],
      'correct': 'x = 4, y = 2',
    },
  ];

  Future<void> _addProblems(List<Map<String,dynamic>> newProblems) async {
    for (Map<String,dynamic> newProblem in newProblems) {
      await db.insert('questions',newProblem);
    }
  }

  Future<void> _loadProblems() async {
    List<Map<String,dynamic>> questions = await db.queryWhere('questions','category=?',['Intermediate Algebra']);
    setState(() {
      this.questions = questions;
    });
  }

  @override
  void initState() {
    super.initState();
    _addProblems(newProblems);
    _loadProblems();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: ListView.builder(
            itemCount: questions.length,
            itemBuilder: (context,index) {
              return questionWidget(
                questions[index]['name'], 
                questions[index]['difficulty'], 
                questions[index]['content'], 
                questions[index]['answers']
              );
            },
          ),
        )
      ],
    );
  }

  Widget questionWidget(String name, int difficulty, String content, String answers) {
    List<String> answersSplit = answers.split(';');
    return GestureDetector(
      onTap: () => _showQuestion(name, content, answersSplit),
      child: Card(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(15),
        ),
        margin: const EdgeInsets.all(8.0),
        elevation: 3,
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(name, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              SizedBox(height: 5),
              Text("Difficulty: $difficulty", style: TextStyle(fontSize: 14, color: Colors.grey)),
              SizedBox(height: 5),
              Text(content, maxLines: 2, overflow: TextOverflow.ellipsis, style: TextStyle(fontSize: 16)),
            ],
          ),
        ),
      ),
    );
  }

  void _showQuestion(String name, String content, List<String> answers) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        scrollable: true,
        title: Text(name),
        content: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(content, style: TextStyle(fontSize: 16)),
                SizedBox(height: 10),
                Column(
                  children: answers.map((answer) => Center(
                    child: ElevatedButton(
                      onPressed: () async {
                        bool isCorrect = await db.checkAnswer(name, answer,'Intermediate Algebra');
                        if (isCorrect) {
                          await db.updateUserQuestProgress(Session.instance.currentUserId ?? 0, 1, 1);
                          int questionId = await db.getQuestionIdByNameAndCategory(name, 'Intermediate Algebra') ?? 0;
                          await db.broDidntMessUp(questionId, 'Intermediate Algebra', Session.instance.currentUserId ?? 0);
                        }
                        print(answer);
                        print(isCorrect);
                        _showResultAnimation(isCorrect);
                      },
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color.fromARGB(255, 27, 50, 56),
                        padding: EdgeInsets.symmetric(vertical: 10, horizontal: 20),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                      child: Text("Answer: $answer", style: TextStyle(fontWeight: FontWeight.bold))
                    ),
                  )).toList(),
                )
              ],
            ),
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: Text("Close")),
        ],
      ),
    );
  }
  void _showResultAnimation(bool isCorrect) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        content: Container(
          width: 150,
          height: 150,
          child: RiveAnimation.asset(
            isCorrect ? 'assets/checkmark_icon.riv' : 'assets/error_icon.riv',
          ),
        ),
      ),
    );

    // Close the animation dialog after 1.5 seconds
    Future.delayed(Duration(milliseconds: 1500), () {
      if (Navigator.canPop(context)) {
        Navigator.pop(context);
      }
    });
  }
}