const List<Map<String, dynamic>> algProblems = [
    // Topic 1: Evaluate functions and use function notation (20 problems)
    {
      'name': 'T1P1',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 2x + 3, evaluate f(5).',
      'answers': '13;12;10;15',
      'correct': '13',
    },
    {
      'name': 'T1P2',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'If f(x) = x² - 1, evaluate f(3).',
      'answers': '8;9;10;11',
      'correct': '8',
    },
    {
      'name': 'T1P3',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 3x - 4, evaluate f(0).',
      'answers': '-4;0;4;–4',
      'correct': '-4',
    },
    {
      'name': 'T1P4',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = -x + 7, evaluate f(2).',
      'answers': '5;4;6;7',
      'correct': '5',
    },
    {
      'name': 'T1P5',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = x², evaluate f(4).',
      'answers': '16;8;12;20',
      'correct': '16',
    },
    {
      'name': 'T1P6',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = √(x), evaluate f(9).',
      'answers': '3;2;4;1',
      'correct': '3',
    },
    {
      'name': 'T1P7',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 1/(x+1), evaluate f(1).',
      'answers': '1/2;1;2;0',
      'correct': '1/2',
    },
    {
      'name': 'T1P8',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 2x - 1, evaluate f(-3).',
      'answers': '-7;-5;-4;-6',
      'correct': '-7',
    },
    {
      'name': 'T1P9',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 4x + 2, evaluate f(3).',
      'answers': '14;12;16;10',
      'correct': '14',
    },
    {
      'name': 'T1P10',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = x³, evaluate f(2).',
      'answers': '8;6;10;4',
      'correct': '8',
    },
    {
      'name': 'T1P11',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = 3x, evaluate f(-1).',
      'answers': '-3;3;0;1',
      'correct': '-3',
    },
    {
      'name': 'T1P12',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 5 - x, evaluate f(6).',
      'answers': '-1;1;0;2',
      'correct': '-1',
    },
    {
      'name': 'T1P13',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = x/2, evaluate f(10).',
      'answers': '5;4;6;10',
      'correct': '5',
    },
    {
      'name': 'T1P14',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = 2x + 1, evaluate f(-2).',
      'answers': '-3;-4;-1;0',
      'correct': '-3',
    },
    {
      'name': 'T1P15',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = |x|, evaluate f(-4).',
      'answers': '4;–4;0;8',
      'correct': '4',
    },
    {
      'name': 'T1P16',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 2,
      'content': 'If f(x) = x² + 2, evaluate f(3).',
      'answers': '11;10;9;12',
      'correct': '11',
    },
    {
      'name': 'T1P17',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 3,
      'content': 'If f(x) = 2x² - 3, evaluate f(2).',
      'answers': '5;4;6;7',
      'correct': '5',
    },
    {
      'name': 'T1P18',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = 10 - x, evaluate f(7).',
      'answers': '3;2;4;5',
      'correct': '3',
    },
    {
      'name': 'T1P19',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = 3x², evaluate f(1).',
      'answers': '3;1;0;2',
      'correct': '3',
    },
    {
      'name': 'T1P20',
      'category': 'Algebra',
      'topic': 1,
      'difficulty': 1,
      'content': 'If f(x) = x + 9, evaluate f(0).',
      'answers': '9;0;10;8',
      'correct': '9',
    },

    // Topic 2: Solve linear systems in two variables (20 problems)
    {
      'name': 'T2P1',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: x + y = 6 and x - y = 2.',
      'answers': 'x = 4, y = 2; x = 3, y = 3; x = 2, y = 4; x = 5, y = 1',
      'correct': 'x = 4, y = 2',
    },
    {
      'name': 'T2P2',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 2x + 3y = 12 and x - y = 1.',
      'answers': 'x = 3, y = 2; x = 2, y = 1; x = 4, y = 3; x = 5, y = 4',
      'correct': 'x = 3, y = 2',
    },
    {
      'name': 'T2P3',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 3x + 2y = 18 and 2x - y = 3.',
      'answers': 'x = 24/7, y = 27/7; x = 3, y = 4; x = 4, y = 2; x = 5, y = 1',
      'correct': 'x = 24/7, y = 27/7',
    },
    {
      'name': 'T2P4',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: x + 2y = 7 and 2x - y = 1.',
      'answers': 'x = 9/5, y = 13/5; x = 2, y = 3; x = 3, y = 2; x = 4, y = 1',
      'correct': 'x = 9/5, y = 13/5',
    },
    {
      'name': 'T2P5',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: 2x + y = 8 and x + y = 6.',
      'answers': 'x = 2, y = 4; x = 3, y = 3; x = 4, y = 2; x = 5, y = 1',
      'correct': 'x = 2, y = 4',
    },
    {
      'name': 'T2P6',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: 3x + y = 10 and x - y = 2.',
      'answers': 'x = 3, y = 1; x = 4, y = 2; x = 5, y = 3; x = 2, y = 0',
      'correct': 'x = 3, y = 1',
    },
    {
      'name': 'T2P7',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 4x + 2y = 20 and x - y = 1.',
      'answers': 'x = 11/3, y = 8/3; x = 3, y = 2; x = 4, y = 3; x = 5, y = 4',
      'correct': 'x = 11/3, y = 8/3',
    },
    {
      'name': 'T2P8',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: 2x + 4y = 16 and x - 2y = -2.',
      'answers': 'x = 2, y = 3; x = 4, y = 2; x = 6, y = 1; x = 0, y = 4',
      'correct': 'x = 4, y = 2',
    },
    {
      'name': 'T2P9',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 5x + y = 11 and 2x - y = 3.',
      'answers': 'x = 2, y = 1; x = 3, y = -4; x = 2, y = -1; x = 1, y = 6',
      'correct': 'x = 2, y = 1',
    },
    {
      'name': 'T2P10',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: x + y = 7 and 2x + 3y = 17.',
      'answers': 'x = 4, y = 3; x = 3, y = 4; x = 2, y = 5; x = 5, y = 2',
      'correct': 'x = 4, y = 3',
    },
    {
      'name': 'T2P11',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 3x - y = 5 and 2x + y = 7.',
      'answers': 'x = 4, y = 3; x = 3, y = 2; x = 2, y = 1; x = 5, y = 4',
      'correct': 'x = 4, y = 3',
    },
    {
      'name': 'T2P12',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: 2x + y = 9 and x + y = 6.',
      'answers': 'x = 3, y = 3; x = 4, y = 2; x = 2, y = 4; x = 5, y = 1',
      'correct': 'x = 3, y = 3',
    },
    {
      'name': 'T2P13',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 4x + y = 13 and x - y = 1.',
      'answers': 'x = 3, y = 4; x = 2, y = 1; x = 4, y = 1; x = 5, y = 0',
      'correct': 'x = 3, y = 4',
    },
    {
      'name': 'T2P14',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 3x + 2y = 14 and 2x - y = 2.',
      'answers': 'x = 4, y = 1; x = 3, y = 2; x = 2, y = 4; x = 5, y = 2',
      'correct': 'x = 4, y = 1',
    },
    {
      'name': 'T2P15',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: x + 3y = 10 and 2x - y = 1.',
      'answers': 'x = 4, y = 2; x = 3, y = 2.33; x = 5, y = 1.67; x = 2, y = 2.67',
      'correct': 'x = 5, y = 1.67',
    },
    {
      'name': 'T2P16',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 2x + 4y = 20 and 3x - 2y = 4.',
      'answers': 'x = 4, y = 3; x = 5, y = 2.5; x = 3, y = 4; x = 6, y = 2',
      'correct': 'x = 4, y = 3',
    },
    {
      'name': 'T2P17',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: x + y = 8 and x = 3.',
      'answers': 'y = 5; y = 4; y = 6; y = 3',
      'correct': 'y = 5',
    },
    {
      'name': 'T2P18',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: 2x + 3y = 16 and x + y = 7.',
      'answers': 'x = 3, y = 4; x = 4, y = 3; x = 2, y = 5; x = 5, y = 2',
      'correct': 'x = 3, y = 4',
    },
    {
      'name': 'T2P19',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 3,
      'content': 'Solve: 3x + y = 11 and 2x - y = 2.',
      'answers': 'x = 3, y = 2; x = 2, y = 5; x = 4, y = -1; x = 3, y = 3',
      'correct': 'x = 3, y = 2',
    },
    {
      'name': 'T2P20',
      'category': 'Algebra',
      'topic': 2,
      'difficulty': 2,
      'content': 'Solve: x + 2y = 9 and x - y = 1.',
      'answers': 'x = 4, y = 2.5; x = 5, y = 2; x = 3, y = 3; x = 6, y = 1.5',
      'correct': 'x = 4, y = 2.5',
    },

    // Topic 3: Solve absolute value equations and inequalities (20 problems)
    {
      'name': 'T3P1',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x - 4| = 3.',
      'answers': 'x = 1 or 7; x = 4; x = -3 or 11; x = 3 or 5',
      'correct': 'x = 1 or 7',
    },
    {
      'name': 'T3P2',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve: |2x + 1| < 5.',
      'answers': '-3 < x < 2; -2 < x < 3; x < -3 or x > 2; x > 3 or x < -2',
      'correct': '-3 < x < 2',
    },
    {
      'name': 'T3P3',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x| = 6.',
      'answers': 'x = 6; x = -6; x = 6 or x = -6; x = 0',
      'correct': 'x = 6 or x = -6',
    },
    {
      'name': 'T3P4',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve: |x + 2| ≥ 4.',
      'answers': 'x ≤ -6 or x ≥ 2; x ≥ -2; x < 2; x ≤ 2',
      'correct': 'x ≤ -6 or x ≥ 2',
    },
    {
      'name': 'T3P5',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |3x - 1| = 8.',
      'answers': 'x = 3; x = -3; x = 3 or x = -3; x = 3 or -7/3',
      'correct': 'x = 3 or x = -7/3',
    },
    {
      'name': 'T3P6',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve the inequality: |x - 2| ≤ 5.',
      'answers': '-3 ≤ x ≤ 7; x < -3 or x > 7; -5 ≤ x ≤ 5; x ≥ 2',
      'correct': '-3 ≤ x ≤ 7',
    },
    {
      'name': 'T3P7',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x + 1| = 0.',
      'answers': 'x = -1; x = 0; x = 1; No solution',
      'correct': 'x = -1',
    },
    {
      'name': 'T3P8',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve the inequality: |2x| > 6.',
      'answers': 'x > 3 or x < -3; -3 < x < 3; x > 3; x < -3',
      'correct': 'x > 3 or x < -3',
    },
    {
      'name': 'T3P9',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x - 3| = 0.',
      'answers': 'x = 3; x = 0; x = -3; No solution',
      'correct': 'x = 3',
    },
    {
      'name': 'T3P10',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve: |x + 5| < 2.',
      'answers': '-7 < x < -3; x > -7; x < -3; -2 < x < 2',
      'correct': '-7 < x < -3',
    },
    {
      'name': 'T3P11',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |2x - 4| = 0.',
      'answers': 'x = 2; x = 0; x = 4; No solution',
      'correct': 'x = 2',
    },
    {
      'name': 'T3P12',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve the inequality: |x| ≥ 3.',
      'answers': 'x ≤ -3 or x ≥ 3; -3 < x < 3; x > 3; x < -3',
      'correct': 'x ≤ -3 or x ≥ 3',
    },
    {
      'name': 'T3P13',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x + 4| = 5.',
      'answers': 'x = 1 or x = -9; x = -1 or x = -9; x = 9; x = 1',
      'correct': 'x = 1 or x = -9',
    },
    {
      'name': 'T3P14',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve: |3x + 2| > 8.',
      'answers': 'x < -10/3 or x > 2; x > -10/3 and x < 2; x < -2 or x > 10/3; x < 2 or x > -10/3',
      'correct': 'x < -10/3 or x > 2',
    },
    {
      'name': 'T3P15',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x - 1| = 4.',
      'answers': 'x = 5 or x = -3; x = 3 or x = -3; x = 5 or x = 1; x = 1',
      'correct': 'x = 5 or x = -3',
    },
    {
      'name': 'T3P16',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve the inequality: |x - 2| ≥ 6.',
      'answers': 'x ≤ -4 or x ≥ 8; -4 < x < 8; x > -4; x < 8',
      'correct': 'x ≤ -4 or x ≥ 8',
    },
    {
      'name': 'T3P17',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |2x| = 10.',
      'answers': 'x = 5 or x = -5; x = 5; x = -5; x = 10',
      'correct': 'x = 5 or x = -5',
    },
    {
      'name': 'T3P18',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 3,
      'content': 'Solve: |x + 3| ≤ 7.',
      'answers': '-10 ≤ x ≤ 4; -4 ≤ x ≤ 10; -7 ≤ x ≤ 7; x ≥ 10',
      'correct': '-10 ≤ x ≤ 4',
    },
    {
      'name': 'T3P19',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve: |x| = 0.',
      'answers': 'x = 0; x = 1; x = -1; No solution',
      'correct': 'x = 0',
    },
    {
      'name': 'T3P20',
      'category': 'Algebra',
      'topic': 3,
      'difficulty': 2,
      'content': 'Solve the inequality: |x - 3| > 2.',
      'answers': 'x < 1 or x > 5; 1 < x < 5; x > 1; x < 5',
      'correct': 'x < 1 or x > 5',
    },

    // Topic 4: Polynomial expressions (20 problems)
    {
      'name': 'T4P1',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Factor: x² - 9.',
      'answers': '(x - 3)(x + 3); (x + 3)²; (x - 3)²; x(x - 9)',
      'correct': '(x - 3)(x + 3)',
    },
    {
      'name': 'T4P2',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Simplify: (x² + 5x + 6) - (x² - 3x - 4).',
      'answers': '8x + 10; 2x + 10; 8x + 2; 2x + 2',
      'correct': '8x + 10',
    },
    {
      'name': 'T4P3',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Factor: x² + 3x - 10.',
      'answers': '(x + 5)(x - 2); (x - 5)(x + 2); (x + 2)(x + 5); (x - 2)(x - 5)',
      'correct': '(x + 5)(x - 2)',
    },
    {
      'name': 'T4P4',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Simplify: 2x² - 3x + 4x - 6.',
      'answers': '2x² + x - 6; 2x² + x + 6; 2x² - x - 6; 2x² + 7x - 6',
      'correct': '2x² + x - 6',
    },
    {
      'name': 'T4P5',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Factor: 3x² - 12.',
      'answers': '3(x² - 4); 3(x - 2)(x + 2); (3x - 2)(x + 2); 3(x - 4)',
      'correct': '3(x - 2)(x + 2)',
    },
    {
      'name': 'T4P6',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Simplify: (2x² + 6x) ÷ (2x).',
      'answers': 'x + 3; 2x + 3; x + 6; 2x + 6',
      'correct': 'x + 3',
    },
    {
      'name': 'T4P7',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: (x² - 4x) + (2x - 8).',
      'answers': 'x² - 2x - 8; x² - 2x + 8; x² - 6x - 8; x² + 2x - 8',
      'correct': 'x² - 2x - 8',
    },
    {
      'name': 'T4P8',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor: x² + 6x + 9.',
      'answers': '(x+3)²;(x+2)(x+4);(x+1)(x+9);x²+9',
      'correct': '(x+3)²',
    },
    {
      'name': 'T4P9',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: 4x² - 16.',
      'answers': '4(x - 2)(x + 2); 4(x²-4); (2x-4)(2x+4); 2(x-2)(x+2)',
      'correct': '4(x - 2)(x + 2)',
    },
    {
      'name': 'T4P10',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor: x² - 2x - 15.',
      'answers': '(x-5)(x+3); (x+5)(x-3); (x-3)(x+5); (x+3)(x+5)',
      'correct': '(x-5)(x+3)',
    },
    {
      'name': 'T4P11',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: (x² + 4x + 4) - (x² - 2x + 1).',
      'answers': '6x + 3; 6x + 2; 2x + 3; 2x + 5',
      'correct': '6x + 3',
    },
    {
      'name': 'T4P12',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor completely: 2x² + 7x + 3.',
      'answers': '(2x+1)(x+3); (2x+3)(x+1); (2x+1)(x+2); (x+3)(x+1)',
      'correct': '(2x+1)(x+3)',
    },
    {
      'name': 'T4P13',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: 3x² - x² + 4x - 2x.',
      'answers': '2x²+2x; 2x²+6x; x²+2x; 4x',
      'correct': '2x²+2x',
    },
    {
      'name': 'T4P14',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor: x² - 10x + 25.',
      'answers': '(x-5)²;(x-10)(x+?);(x+5)²;x²-25',
      'correct': '(x-5)²',
    },
    {
      'name': 'T4P15',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: 6x - 2x + 3 - 1.',
      'answers': '4x+2;4x+3;6x+2;6x+3',
      'correct': '4x+2',
    },
    {
      'name': 'T4P16',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor: 4x² - 12x.',
      'answers': '4x(x - 3); 2x(2x - 3); 4x(x + 3); 2x(x - 6)',
      'correct': '4x(x - 3)',
    },
    {
      'name': 'T4P17',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: (x² + 2x + 1)/(x+1).',
      'answers': 'x+1;x;1;x+2',
      'correct': 'x+1',
    },
    {
      'name': 'T4P18',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor: 5x² + 15x.',
      'answers': '5x(x+3); 5(x²+3); x(5x+3); 5x+15',
      'correct': '5x(x+3)',
    },
    {
      'name': 'T4P19',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 2,
      'content': 'Simplify: (2x²+6x) - (x²+4x).',
      'answers': 'x²+2x; x²+4x; x²+6x; 2x²+2x',
      'correct': 'x²+2x',
    },
    {
      'name': 'T4P20',
      'category': 'Algebra',
      'topic': 4,
      'difficulty': 3,
      'content': 'Factor: x² + 7x + 12.',
      'answers': '(x+3)(x+4); (x+2)(x+6); (x+1)(x+12); (x+4)(x+3)',
      'correct': '(x+3)(x+4)',
    },

    // Topic 5: Rational expressions – 20 problems
    {
      'name': 'T5P1',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (x² - 9)/(x - 3).',
      'answers': 'x+3; x-3; x²-3; 1',
      'correct': 'x+3',
    },
    {
      'name': 'T5P2',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (1/x + 1/y) ÷ (1/x - 1/y).',
      'answers': '(x+y)/(x-y); (x-y)/(x+y); (y+x)/(y-x); (y-x)/(y+x)',
      'correct': '(x+y)/(x-y)',
    },
    {
      'name': 'T5P3',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (2x^2 - 8)/(2x).',
      'answers': 'x-4/x; x-4; 2x-8; 2(x-4)/x',
      'correct': 'x-4',
    },
    {
      'name': 'T5P4',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify the complex fraction: (1/x + 2/y) / (3/x - 4/y).',
      'answers': '[(y+2x)/(3y-4x)]; [(2x+y)/(3y-4x)]; [(y+2x)/(4x-3y)]; [(2x+y)/(4x-3y)]',
      'correct': '[(y+2x)/(3y-4x)]',
    },
    {
      'name': 'T5P5',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (x² - 4)/(x² - 2x).',
      'answers': '(x+2)/(x-2); (x-2)/(x-4); (x+2)/(x-2); (x-2)/(x+2)',
      'correct': '(x+2)/(x-2)',
    },
    {
      'name': 'T5P6',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (3x/(x²-1)) + (2/(x+1)).',
      'answers': '(5x+?)/(x-1); Simplify fully',
      'correct': 'Simplify fully', // (This one is left for further elaboration)
    },
    {
      'name': 'T5P7',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (x²-16)/(x-4).',
      'answers': 'x+4;x-4; x+8;x-8',
      'correct': 'x+4',
    },
    {
      'name': 'T5P8',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (2x-6)/(x²-9).',
      'answers': '2/(x+3); 2/(x-3); (2)/(x+3) - (2)/(x-3); None',
      'correct': '2/(x-3)', // Example answer
    },
    {
      'name': 'T5P9',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (x²-9x)/(x).',
      'answers': 'x-9; x-3; x+9; 9-x',
      'correct': 'x-9',
    },
    {
      'name': 'T5P10',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (4x+8)/(2x).',
      'answers': '2+4/x; 2+8/x; 2; 4/x+2',
      'correct': '2+4/x',
    },
    {
      'name': 'T5P11',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (x²-1)/(x-1).',
      'answers': 'x+1;x-1; x²-1; 1',
      'correct': 'x+1',
    },
    {
      'name': 'T5P12',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: [(1/x)+(1/(x+2))] ÷ [(1/x)-(1/(x+2))].',
      'answers': '(2x+2)/2; (x+1)/(x+?); Use common denominator;  (2x+2)/(?)',
      'correct': 'Use common denominator', // Placeholder answer
    },
    {
      'name': 'T5P13',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (2x²-8)/(2x).',
      'answers': 'x-4/x; x-4; 2(x-4)/x; x/2-4',
      'correct': 'x-4',
    },
    {
      'name': 'T5P14',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (x²-4)/(x²-2x).',
      'answers': '(x+2)/(x-2); (x-2)/(x-?); Check factors; None',
      'correct': '(x+2)/(x-2)',
    },
    {
      'name': 'T5P15',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (3x-9)/(3).',
      'answers': 'x-3; x+3; 3(x-3); x-9',
      'correct': 'x-3',
    },
    {
      'name': 'T5P16',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (x²-4x+4)/(x-2).',
      'answers': 'x-2; x-4; (x-2)²; x+2',
      'correct': 'x-2',
    },
    {
      'name': 'T5P17',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (2x²-6x)/(2x).',
      'answers': 'x-3; 2x-3; x+3; 3',
      'correct': 'x-3',
    },
    {
      'name': 'T5P18',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: (x²-9)/(x²-6x+9).',
      'answers': '(x-3)/(x-3); (x+3)/(x-3); (x-3)²;(x+3)²',
      'correct': '(x+3)/(x-3)',
    },
    {
      'name': 'T5P19',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 2,
      'content': 'Simplify: (4x²-16)/(2x-8).',
      'answers': '2x+4; 2x-4; 4x+4; 4x-4',
      'correct': '2x+4',
    },
    {
      'name': 'T5P20',
      'category': 'Algebra',
      'topic': 5,
      'difficulty': 3,
      'content': 'Simplify: [(x+2)/(x-2)] ÷ [(x-2)/(x+2)].',
      'answers': '(x+2)²/(x-2)²; (x-2)²/(x+2)²; 1; (x+2)/(x-2)',
      'correct': '1',
    },

    // Topic 6: Solve rational equations (20 problems)
    {
      'name': 'T6P1',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (1/(x-2)) + (1/(x+2)) = 1/3.',
      'answers': 'x = 5 or x = -5; x = 4 or x = -4; x = 3 or x = -3; x = 2 or x = -2',
      'correct': 'x = 5 or x = -5',
    },
    {
      'name': 'T6P2',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (2/(x)) = (x+3)/(x-3).',
      'answers': 'x = -1; x = 1; x = 3; x = -3',
      'correct': 'x = -1',
    },
    {
      'name': 'T6P3',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (x/(x-1)) = 2.',
      'answers': 'x = 2; x = 3; x = 1; x = -2',
      'correct': 'x = 2',
    },
    {
      'name': 'T6P4',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (3/(x)) + (2/(x+1)) = 1.',
      'answers': 'x = 2; x = 3; x = 1; x = 4',
      'correct': 'x = 2',
    },
    {
      'name': 'T6P5',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (2x)/(x-2) = 4.',
      'answers': 'x = 4; x = 3; x = 6; x = 2',
      'correct': 'x = 4',
    },
    {
      'name': 'T6P6',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (x+1)/(x-1) = 3.',
      'answers': 'x = 2; x = 3; x = 4; x = 1',
      'correct': 'x = 2',
    },
    {
      'name': 'T6P7',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (1/(x)) = 3.',
      'answers': 'x = 1/3; x = 3; x = -3; x = 0',
      'correct': 'x = 1/3',
    },
    {
      'name': 'T6P8',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (x-2)/(x+2) = 1/2.',
      'answers': 'x = 6; x = 2; x = -6; x = 4',
      'correct': 'x = 6',
    },
    {
      'name': 'T6P9',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (2x+3)/(x-3) = 2.',
      'answers': 'x = 9; x = 3; x = 0; x = -3',
      'correct': 'x = 9',
    },
    {
      'name': 'T6P10',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (x+2)/(x-2) = 3.',
      'answers': 'x = 4; x = 5; x = 2; x = 6',
      'correct': 'x = 4',
    },
    {
      'name': 'T6P11',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: 1/(x+1) - 1/(x-1) = 1/2.',
      'answers': 'x = 0; x = 2; x = -2; x = 1',
      'correct': 'x = 2',
    },
    {
      'name': 'T6P12',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (3x-1)/(x+2) = 2.',
      'answers': 'x = 5; x = 3; x = 4; x = -1',
      'correct': 'x = 5',
    },
    {
      'name': 'T6P13',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (2x+4)/(x) = 3.',
      'answers': 'x = 4; x = 2; x = 6; x = -4',
      'correct': 'x = 4',
    },
    {
      'name': 'T6P14',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (x-1)/(x+1) = 1/3.',
      'answers': 'x = 2; x = 4; x = 1; x = 3',
      'correct': 'x = 2',
    },
    {
      'name': 'T6P15',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (3)/(x) = 6.',
      'answers': 'x = 0.5; x = 2; x = 3; x = 0.5',
      'correct': 'x = 0.5',
    },
    {
      'name': 'T6P16',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (2x)/(x-2) = 3.',
      'answers': 'x = 6; x = 4; x = 3; x = 2',
      'correct': 'x = 6',
    },
    {
      'name': 'T6P17',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (x+3)/(x-3) = 2.',
      'answers': 'x = 9; x = 6; x = 3; x = -3',
      'correct': 'x = 9',
    },
    {
      'name': 'T6P18',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (2)/(x) = 4.',
      'answers': 'x = 0.5; x = 1; x = 2; x = 0.5',
      'correct': 'x = 0.5',
    },
    {
      'name': 'T6P19',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 3,
      'content': 'Solve: (3x+2)/(x) = 5.',
      'answers': 'x = 2; x = 3; x = 4; x = 1',
      'correct': 'x = 2',
    },
    {
      'name': 'T6P20',
      'category': 'Algebra',
      'topic': 6,
      'difficulty': 2,
      'content': 'Solve: (x+1)/(x-1) = 2.',
      'answers': 'x = 3; x = 4; x = 5; x = 2',
      'correct': 'x = 3',
    },

    // Topic 7: Solve literal equations for a specific variable (20 problems)
    {
      'name': 'T7P1',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for y: 3x + 2y = 12.',
      'answers': 'y = (12-3x)/2; y = (3x-12)/2; y = 12-3x; y = 12/2-3x',
      'correct': 'y = (12-3x)/2',
    },
    {
      'name': 'T7P2',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 4xy = 20 (assume y ≠ 0).',
      'answers': 'x = 5/y; x = 20/y; x = 4/y; x = y/5',
      'correct': 'x = 5/y',
    },
    {
      'name': 'T7P3',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for z: 2z + 3 = 11.',
      'answers': 'z = 4; z = 5; z = 3; z = 6',
      'correct': 'z = 4',
    },
    {
      'name': 'T7P4',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 5x - 7 = 3x + 1.',
      'answers': 'x = 4; x = 3; x = 2; x = 5',
      'correct': 'x = 4',
    },
    {
      'name': 'T7P5',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for y: 6y = 24.',
      'answers': 'y = 4; y = 3; y = 6; y = 2',
      'correct': 'y = 4',
    },
    {
      'name': 'T7P6',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 2x + 3y = 12, given y = 2.',
      'answers': 'x = 3; x = 4; x = 5; x = 2',
      'correct': 'x = 3',
    },
    {
      'name': 'T7P7',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for a: 4a - 5 = 11.',
      'answers': 'a = 4; a = 3; a = 5; a = 6',
      'correct': 'a = 4',
    },
    {
      'name': 'T7P8',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for y: 5y + 10 = 35.',
      'answers': 'y = 5; y = 4; y = 3; y = 6',
      'correct': 'y = 5',
    },
    {
      'name': 'T7P9',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 3x/2 = 9.',
      'answers': 'x = 4; x = 5; x = 6; x = 7',
      'correct': 'x = 6',
    },
    {
      'name': 'T7P10',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for z: z/3 + 2 = 5.',
      'answers': 'z = 9; z = 6; z = 3; z = 12',
      'correct': 'z = 9',
    },
    {
      'name': 'T7P11',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 2x - 3 = x + 4.',
      'answers': 'x = 7; x = -7; x = 1; x = 0',
      'correct': 'x = 7',
    },
    {
      'name': 'T7P12',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for y: 8y = 32.',
      'answers': 'y = 4;y = 3;y = 2;y = 8',
      'correct': 'y = 4',
    },
    {
      'name': 'T7P13',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 5x + 2 = 3x + 10.',
      'answers': 'x = 4;x = 3;x = 2;x = 5',
      'correct': 'x = 4',
    },
    {
      'name': 'T7P14',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for y: 7y - 14 = 0.',
      'answers': 'y = 2; y = 0; y = 7; y = 14',
      'correct': 'y = 2',
    },
    {
      'name': 'T7P15',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 4x + 8 = 16.',
      'answers': 'x = 2; x = 3; x = 4; x = 1',
      'correct': 'x = 2',
    },
    {
      'name': 'T7P16',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for a: 5a = 20.',
      'answers': 'a = 4; a = 5; a = 3; a = 2',
      'correct': 'a = 4',
    },
    {
      'name': 'T7P17',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 2x + 4 = 12.',
      'answers': 'x = 3; x = 4; x = 5; x = 6',
      'correct': 'x = 4',
    },
    {
      'name': 'T7P18',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for y: 3y = 12.',
      'answers': 'y = 3; y = 4; y = 5; y = 6',
      'correct': 'y = 4',
    },
    {
      'name': 'T7P19',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 3,
      'content': 'Solve for x: 7x - 5 = 2x + 10.',
      'answers': 'x = 3; x = 5; x = 4; x = 2',
      'correct': 'x = 3',
    },
    {
      'name': 'T7P20',
      'category': 'Algebra',
      'topic': 7,
      'difficulty': 2,
      'content': 'Solve for z: 4z + 8 = 0.',
      'answers': 'z = -2; z = 2; z = 0; z = -4',
      'correct': 'z = -2',
    },

    // Topic 8: Rational exponents and radicals (20 problems)
    {
      'name': 'T8P1',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: x^(3/2) when x = 16.',
      'answers': '64;32;16;8',
      'correct': '64',
    },
    {
      'name': 'T8P2',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Express √(x³) using rational exponents.',
      'answers': 'x^(3/2); x^(1/2); x^(2/3); x^(1/3)',
      'correct': 'x^(3/2)',
    },
    {
      'name': 'T8P3',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Convert: √(25) to rational exponent form.',
      'answers': '25^(1/2); 25^(2/1); 25^(1/3); 25^(3/2)',
      'correct': '25^(1/2)',
    },
    {
      'name': 'T8P4',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (x^(1/2))².',
      'answers': 'x; x^(1/2); x^2; 2x',
      'correct': 'x',
    },
    {
      'name': 'T8P5',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Express ³√(x²) as a rational exponent.',
      'answers': 'x^(2/3); x^(3/2); x^(1/3); x^(2)',
      'correct': 'x^(2/3)',
    },
    {
      'name': 'T8P6',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (16)^(3/4).',
      'answers': '8;4;16;2',
      'correct': '8',
    },
    {
      'name': 'T8P7',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Convert: 27^(1/3) to radical form.',
      'answers': '³√27; √27; 27; ³√9',
      'correct': '³√27',
    },
    {
      'name': 'T8P8',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (x^(3/2))*(x^(1/2)).',
      'answers': 'x^2;x^3;x;x^(1/2)',
      'correct': 'x^2',
    },
    {
      'name': 'T8P9',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Convert: √(81) to rational exponent form.',
      'answers': '81^(1/2); 81^(2/1); 81^(1/3); 81^(3/2)',
      'correct': '81^(1/2)',
    },
    {
      'name': 'T8P10',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (9^(1/2))^2.',
      'answers': '9; 3; 81; 6',
      'correct': '9',
    },
    {
      'name': 'T8P11',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Express ³√(8) using rational exponents.',
      'answers': '8^(1/3); 8^(1/2); 8^(3/2); 8^(2/3)',
      'correct': '8^(1/3)',
    },
    {
      'name': 'T8P12',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Express 16^(1/4) in radical form.',
      'answers': '⁴√16; √16; 16^(1/2); ⁴√8',
      'correct': '⁴√16',
    },
    {
      'name': 'T8P13',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (x^(2/3))/(x^(1/3)).',
      'answers': 'x^(1/3); x^(2/3); x; 1',
      'correct': 'x^(1/3)',
    },
    {
      'name': 'T8P14',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Express ⁶√(64) as a rational exponent.',
      'answers': '64^(1/6); 64^(1/3); 64^(1/2); 64^(1/4)',
      'correct': '64^(1/6)',
    },
    {
      'name': 'T8P15',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Convert: √(x^4) to rational exponents.',
      'answers': 'x^2; x^(4/2); x^4; x^8',
      'correct': 'x^2',
    },
    {
      'name': 'T8P16',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (27^(1/3))^2.',
      'answers': '9; 6; 3; 27',
      'correct': '9',
    },
    {
      'name': 'T8P17',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Express: 32^(1/5) in radical form.',
      'answers': '⁵√32; √32; 32^(1/2); 32^(1/4)',
      'correct': '⁵√32',
    },
    {
      'name': 'T8P18',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: x^(1/4)*x^(3/4).',
      'answers': 'x; x^2; x^(1/2); 1',
      'correct': 'x',
    },
    {
      'name': 'T8P19',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Express: √(x) as a rational exponent.',
      'answers': 'x^(1/2); x^(2); x^(1/3); x^(3/2)',
      'correct': 'x^(1/2)',
    },
    {
      'name': 'T8P20',
      'category': 'Algebra',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (a^(1/2))/(a^(1/4)).',
      'answers': 'a^(1/4); a^(1/2); a^(3/4); a^(1/8)',
      'correct': 'a^(1/4)',
    },

    // Topic 9: Simplify radical expressions (20 problems)
    {
      'name': 'T9P1',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(49).',
      'answers': '6;7;8;9',
      'correct': '7',
    },
    {
      'name': 'T9P2',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(x²).',
      'answers': '|x|; x; -x; x²',
      'correct': '|x|',
    },
    {
      'name': 'T9P3',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 3,
      'content': 'Simplify: √(50) in simplest radical form.',
      'answers': '5√2; 5√(2); 5√(10); √50',
      'correct': '5√2',
    },
    {
      'name': 'T9P4',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(x⁴).',
      'answers': 'x²; |x|; x; x^4',
      'correct': 'x²',
    },
    {
      'name': 'T9P5',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 3,
      'content': 'Simplify: √(18).',
      'answers': '3√2; 2√3; 3√3; 2√2',
      'correct': '3√2',
    },
    {
      'name': 'T9P6',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(100x²).',
      'answers': '10|x|; 10x; 100x; |x|',
      'correct': '10|x|',
    },
    {
      'name': 'T9P7',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 3,
      'content': 'Simplify: √(32).',
      'answers': '4√2; 2√8; 8; 4√3',
      'correct': '4√2',
    },
    {
      'name': 'T9P8',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(x²y²).',
      'answers': '|xy|; xy; x²y²; |x|+|y|',
      'correct': '|xy|',
    },
    {
      'name': 'T9P9',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(64).',
      'answers': '6;7;8;9',
      'correct': '8',
    },
    {
      'name': 'T9P10',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(2x²) given x ≥ 0.',
      'answers': 'x√2; √(2x); 2x; x/√2',
      'correct': 'x√2',
    },
    {
      'name': 'T9P11',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 3,
      'content': 'Simplify: √(72).',
      'answers': '6√2; 4√3; 3√8; 6√3',
      'correct': '6√2',
    },
    {
      'name': 'T9P12',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(9x²) given x is positive.',
      'answers': '3x; 9x; x/3; 3',
      'correct': '3x',
    },
    {
      'name': 'T9P13',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 3,
      'content': 'Simplify: √(50x²) in simplest radical form.',
      'answers': '5√2|x|; 5x√2; 10√(x); 5x',
      'correct': '5√2|x|',
    },
    {
      'name': 'T9P14',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(81).',
      'answers': '8;9;10;7',
      'correct': '9',
    },
    {
      'name': 'T9P15',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 3,
      'content': 'Simplify: √(200) in simplest radical form.',
      'answers': '10√2; 10√(2); 5√8; 10√(5)',
      'correct': '10√2',
    },
    {
      'name': 'T9P16',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(144x²) given x ≥ 0.',
      'answers': '12x; 144x; 12; 24x',
      'correct': '12x',
    },
    {
      'name': 'T9P17',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(25y²).',
      'answers': '5|y|; 5y; 25y; y/5',
      'correct': '5|y|',
    },
    {
      'name': 'T9P18',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(x⁴).',
      'answers': 'x²; x; |x|; x^4',
      'correct': 'x²',
    },
    {
      'name': 'T9P19',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(50) as a radical.',
      'answers': '5√2; 5√(2); 5√5; 25',
      'correct': '5√2',
    },
    {
      'name': 'T9P20',
      'category': 'Algebra',
      'topic': 9,
      'difficulty': 2,
      'content': 'Simplify: √(x²+0).',
      'answers': '|x|; x; 0; 1',
      'correct': '|x|',
    },

    // Topic 10: Solve radical equations and applications (20 problems)
    {
      'name': 'T10P1',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(x + 3) = 4.',
      'answers': 'x = 13; x = 16; x = 7; x = 1',
      'correct': 'x = 13',
    },
    {
      'name': 'T10P2',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(2x - 1) = x - 2.',
      'answers': 'x = 3; x = 4; x = 5; x = 6',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P3',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(x) + 2 = 5.',
      'answers': 'x = 9; x = 4; x = 3; x = 7',
      'correct': 'x = 9',
    },
    {
      'name': 'T10P4',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve: √(3x+4) = x - 2.',
      'answers': 'x = 6; x = 4; x = 8; x = 10',
      'correct': 'x = 6',
    },
    {
      'name': 'T10P5',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(x+1) + 3 = 7.',
      'answers': 'x = 15; x = 3; x = 4; x = 5',
      'correct': 'x = 3',
    },
    {
      'name': 'T10P6',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(2x+6) = x - 1.',
      'answers': 'x = 4; x = 5; x = 3; x = 2',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P7',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve: √(x+5) = (x-1)/2.',
      'answers': 'x = 6; x = 4; x = 8; x = 10',
      'correct': 'x = 6',
    },
    {
      'name': 'T10P8',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(3x - 2) = x - 4.',
      'answers': 'x = 6; x = 7; x = 8; x = 9',
      'correct': 'x = 6',
    },
    {
      'name': 'T10P9',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(x - 1) = 2.',
      'answers': 'x = 5; x = 3; x = 4; x = 6',
      'correct': 'x = 5',
    },
    {
      'name': 'T10P10',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(4x+9) = 5.',
      'answers': 'x = 4; x = 1; x = 2; x = 3',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P11',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve: √(x+2) = x - 2.',
      'answers': 'x = 6; x = 4; x = 5; x = 3',
      'correct': 'x = 6',
    },
    {
      'name': 'T10P12',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(2x+1) = x/2.',
      'answers': 'x = 3; x = 4; x = 5; x = 6',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P13',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve: √(x-4) + 2 = x - 2.',
      'answers': 'x = 6; x = 8; x = 10; x = 4',
      'correct': 'x = 8',
    },
    {
      'name': 'T10P14',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(x+8) = x - 4.',
      'answers': 'x = 6; x = 8; x = 10; x = 12',
      'correct': 'x = 8',
    },
    {
      'name': 'T10P15',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(3x+1) = 2.',
      'answers': 'x = 1; x = 3; x = 5; x = 7',
      'correct': 'x = 1',
    },
    {
      'name': 'T10P16',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve: √(x+4) = 3.',
      'answers': 'x = 5; x = 4; x = 3; x = 7',
      'correct': 'x = 5',
    },
    {
      'name': 'T10P17',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(2x+4) = x - 2.',
      'answers': 'x = 4; x = 6; x = 8; x = 10',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P18',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(x+9) = x - 3.',
      'answers': 'x = 6; x = 7; x = 8; x = 9',
      'correct': 'x = 6',
    },
    {
      'name': 'T10P19',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: √(3x+7) = x - 1.',
      'answers': 'x = 4; x = 5; x = 6; x = 7',
      'correct': 'x = 4',
    },
    {
      'name': 'T10P20',
      'category': 'Algebra',
      'topic': 10,
      'difficulty': 4,
      'content': 'Solve: √(x+16) = x - 4.',
      'answers': 'x = 8; x = 9; x = 10; x = 12',
      'correct': 'x = 8',
    },

    // Topic 11: Solve quadratic equations (20 problems)
    {
      'name': 'T11P1',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'Solve by factoring: x² - 5x + 6 = 0.',
      'answers': 'x = 2, 3; x = 1, 6; x = -2, -3; x = 2, -3',
      'correct': 'x = 2, 3',
    },
    {
      'name': 'T11P2',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve using the quadratic formula: x² + 4x + 3 = 0.',
      'answers': 'x = -1, -3; x = 1, 3; x = -2, -2; x = 2, 2',
      'correct': 'x = -1, -3',
    },
    {
      'name': 'T11P3',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve by completing the square: x² + 6x + 5 = 0.',
      'answers': 'x = -1, -5; x = -2, -3; x = 1, 5; x = 2, 3',
      'correct': 'x = -1, -5',
    },
    {
      'name': 'T11P4',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'Solve by factoring: x² - 9 = 0.',
      'answers': 'x = -3, 3; x = 0; x = -9, 9; x = 3',
      'correct': 'x = -3, 3',
    },
    {
      'name': 'T11P5',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve by square root method: x² = 16.',
      'answers': 'x = 4; x = -4; x = ±4; x = 0',
      'correct': 'x = ±4',
    },
    {
      'name': 'T11P6',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve by completing the square: x² + 2x - 3 = 0.',
      'answers': 'x = 1, -3; x = -1, 3; x = -3, 1; x = 1, 3',
      'correct': 'x = 1, -3',
    },
    {
      'name': 'T11P7',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'Solve by factoring: 2x² - 8 = 0.',
      'answers': 'x = -2, 2; x = 0; x = -4, 4; x = 2',
      'correct': 'x = -2, 2',
    },
    {
      'name': 'T11P8',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve using the quadratic formula: x² + x - 6 = 0.',
      'answers': 'x = 2, -3; x = -2, 3; x = 1, -6; x = -1, 6',
      'correct': 'x = 2, -3',
    },
    {
      'name': 'T11P9',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: x² - 2x - 8 = 0 by factoring.',
      'answers': 'x = -2, 4; x = 2, -4; x = -1, 8; x = 1, -8',
      'correct': 'x = -2, 4',
    },
    {
      'name': 'T11P10',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 4,
      'content': 'Solve: 3x² - 5x - 2 = 0 using the quadratic formula.',
      'answers': 'x = 2, x = -1/3; x = 1, x = -2; x = 2, x = 1/3; x = -2, x = 1/3',
      'correct': 'x = 2, x = -1/3',
    },
    {
      'name': 'T11P11',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'Solve by factoring: x² - x - 6 = 0.',
      'answers': 'x = -2, 3; x = 2, -3; x = 1, -6; x = -1, 6',
      'correct': 'x = -2, 3',
    },
    {
      'name': 'T11P12',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: x² + 3x + 2 = 0 by factoring.',
      'answers': 'x = -1, -2; x = 1, 2; x = -2, 1; x = 2, -1',
      'correct': 'x = -1, -2',
    },
    {
      'name': 'T11P13',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: 2x² + x - 1 = 0 using the quadratic formula.',
      'answers': 'x = 1/2, -1; x = -1/2, 1; x = 1, -1/2; x = -1, 1/2',
      'correct': 'x = 1/2, -1',
    },
    {
      'name': 'T11P14',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 4,
      'content': 'Solve: x² - 4x + 1 = 0 using completing the square.',
      'answers': 'x = 2 ± √3; x = 2 ± √2; x = 2 ± 1; x = 4 ± √3',
      'correct': 'x = 2 ± √3',
    },
    {
      'name': 'T11P15',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: x² + 2x - 8 = 0 by factoring.',
      'answers': 'x = 2, -4; x = -2, 4; x = 1, -8; x = -1, 8',
      'correct': 'x = 2, -4',
    },
    {
      'name': 'T11P16',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: 4x² - 12x + 9 = 0 by recognizing a perfect square.',
      'answers': 'x = 3 (double zero); x = 3; x = -3; x = 0',
      'correct': 'x = 3 (double zero)',
    },
    {
      'name': 'T11P17',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 4,
      'content': 'Solve: x² - 6x + 8 = 0 using the quadratic formula.',
      'answers': 'x = 2, x = 4; x = 4, x = 2; x = 3, x = 3; x = -2, x = -4',
      'correct': 'x = 2, x = 4',
    },
    {
      'name': 'T11P18',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: x² + x - 12 = 0 by factoring.',
      'answers': 'x = 3, -4; x = -3, 4; x = 4, -3; x = 2, -6',
      'correct': 'x = 3, -4',
    },
    {
      'name': 'T11P19',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 2,
      'content': 'Solve: x² - 2x = 0 by factoring.',
      'answers': 'x = 0, 2; x = 1, 2; x = -2, 2; x = 0',
      'correct': 'x = 0, 2',
    },
    {
      'name': 'T11P20',
      'category': 'Algebra',
      'topic': 11,
      'difficulty': 3,
      'content': 'Solve: 2x² + 5x + 2 = 0 by factoring.',
      'answers': 'x = -1, -1/2; x = 1, 2; x = -2, -1; x = 1/2, 1',
      'correct': 'x = -1, -1/2',
    },

    // Topic 12: Graph quadratic functions (20 problems)
    {
      'name': 'T12P1',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'Find the vertex of y = x² - 6x + 5.',
      'answers': '(3, -4); (3, 4); (2, -1); (2, 1)',
      'correct': '(3, -4)',
    },
    {
      'name': 'T12P2',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the axis of symmetry for y = -x² + 4x + 1.',
      'answers': 'x = 2; x = -2; x = 1; x = 4',
      'correct': 'x = 2',
    },
    {
      'name': 'T12P3',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'Determine the y-intercept of y = 2x² - 3x + 4.',
      'answers': '4;2;0;–4',
      'correct': '4',
    },
    {
      'name': 'T12P4',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Graph y = -x² + 2x + 3. What is its vertex?',
      'answers': '(1,4); (1,-4); (-1,4); (-1,-4)',
      'correct': '(1,4)',
    },
    {
      'name': 'T12P5',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'Find the x-intercepts of y = x² - 9.',
      'answers': 'x = -3, 3; x = 0; x = -9, 9; x = 3',
      'correct': 'x = -3, 3',
    },
    {
      'name': 'T12P6',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Determine the vertex of y = (x+2)² - 5.',
      'answers': '(-2, -5); (2, 5); (-2, 5); (2, -5)',
      'correct': '(-2, -5)',
    },
    {
      'name': 'T12P7',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'Find the axis of symmetry of y = x² + 4x + 3.',
      'answers': 'x = -2; x = 2; x = -1; x = 1',
      'correct': 'x = -2',
    },
    {
      'name': 'T12P8',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Determine the vertex of y = -2x² + 8x - 3.',
      'answers': '(2, 5); (2, -5); (4, 5); (4, -5)',
      'correct': '(2, 5)',
    },
    {
      'name': 'T12P9',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'Find the y-intercept of y = -x² + x + 6.',
      'answers': '6;1;–6;0',
      'correct': '6',
    },
    {
      'name': 'T12P10',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Graph y = x² - 2x - 3. What are the x-intercepts?',
      'answers': 'x = -1 and x = 3; x = 1 and x = -3; x = -3 and x = 3; x = 1 and x = 3',
      'correct': 'x = -1 and x = 3',
    },
    {
      'name': 'T12P11',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Determine the vertex of y = -x² - 4x + 1.',
      'answers': '(-2, 5); (-2, -3); (2, -3); (2, 5)',
      'correct': '(-2, -3)',
    },
    {
      'name': 'T12P12',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 2,
      'content': 'Find the axis of symmetry for y = 2x² + 8x + 6.',
      'answers': 'x = -2; x = 2; x = -1; x = 1',
      'correct': 'x = -2',
    },
    {
      'name': 'T12P13',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Graph y = x² - 4. Identify its vertex.',
      'answers': '(0,-4); (2,0); (0,4); (-2,0)',
      'correct': '(0,-4)',
    },
    {
      'name': 'T12P14',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Determine the x-intercepts of y = x² + x - 6.',
      'answers': 'x = -3, 2; x = 3, -2; x = -1, 6; x = 1, -6',
      'correct': 'x = -3, 2',
    },
    {
      'name': 'T12P15',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the vertex of y = -x² + 6x - 8.',
      'answers': '(3, 1); (3, -1); (2, 1); (2, -1)',
      'correct': '(3, 1)',
    },
    {
      'name': 'T12P16',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 4,
      'content': 'Graph y = 2x² - 8x + 5 and state the axis of symmetry.',
      'answers': 'x = 2; x = 4; x = 1; x = 3',
      'correct': 'x = 2',
    },
    {
      'name': 'T12P17',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the y-intercept of y = -3x² + x + 2.',
      'answers': '2; -2; 1; -1',
      'correct': '2',
    },
    {
      'name': 'T12P18',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Determine the vertex of y = x² + 2x + 1.',
      'answers': '(-1,0); (-1,1); (1,-1); (1,1)',
      'correct': '(-1,0)',
    },
    {
      'name': 'T12P19',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Graph y = -x² + 2x + 3 and identify the vertex.',
      'answers': '(1,4); (1,-4); (-1,4); (-1,-4)',
      'correct': '(1,4)',
    },
    {
      'name': 'T12P20',
      'category': 'Algebra',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the x-intercepts of y = x² - 5x + 6.',
      'answers': 'x = 2 and x = 3; x = 1 and x = 6; x = 0; x = 2 and x = 4',
      'correct': 'x = 2 and x = 3',
    },

    // Topic 13: Applications involving quadratic equations (20 problems)
    {
      'name': 'T13P1',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'A ball is thrown upward with height h(t)= -16t² + 32t + 5. When does it hit the ground?',
      'answers': 't ≈ 2.5 sec; t ≈ 3 sec; t ≈ 1.5 sec; t ≈ 4 sec',
      'correct': 't ≈ 2.5 sec',
    },
    {
      'name': 'T13P2',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'The area of a rectangle is 48 and its length is 3 times its width. Find its dimensions.',
      'answers': 'Width = 4, Length = 12; Width = 3, Length = 9; Width = 6, Length = 18; Width = 2, Length = 6',
      'correct': 'Width = 4, Length = 12',
    },
    {
      'name': 'T13P3',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve: The product of two numbers is 12 and their sum is 7. Find the numbers.',
      'answers': '3 and 4; 2 and 6; -3 and -4; 1 and 12',
      'correct': '3 and 4',
    },
    {
      'name': 'T13P4',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'A quadratic equation models the trajectory of a projectile: h(t)= -16t² + 48t + 2. Find when h(t)=0.',
      'answers': 't ≈ 0.1 sec and t ≈ 3 sec; t ≈ 1 sec and t ≈ 2 sec; t ≈ 0.5 sec and t ≈ 3 sec; t ≈ 1 and t ≈ 3',
      'correct': 't ≈ 0.1 sec and t ≈ 3 sec',
    },
    {
      'name': 'T13P5',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve: The area of a rectangle is 60, and its length exceeds its width by 4. Find the dimensions.',
      'answers': 'Width = 5, Length = 9; Width = 6, Length = 10; Width = 4, Length = 8; Width = 3, Length = 7',
      'correct': 'Width = 6, Length = 10',
    },
    {
      'name': 'T13P6',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve: The sum of two numbers is 11 and their product is 24. Find the numbers.',
      'answers': '3 and 8; 4 and 7; 5 and 6; 2 and 9',
      'correct': '3 and 8',
    },
    {
      'name': 'T13P7',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'A quadratic function f(x)= x² - 4x + k has exactly one real root. Find k.',
      'answers': 'k = 4; k = 0; k = 2; k = -4',
      'correct': 'k = 4',
    },
    {
      'name': 'T13P8',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve: x² - 4 = 5x - 6.',
      'answers': 'x = 2 or 5; x = 3 or 2; x = 1 or 6; x = 2 or 4',
      'correct': 'x = 2 or 5',
    },
    {
      'name': 'T13P9',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'A quadratic equation has roots that sum to 5 and product 6. Find the equation in standard form.',
      'answers': 'x² - 5x + 6 = 0;x² + 5x + 6 = 0;x² - 6x + 5 = 0;x² + 6x + 5 = 0',
      'correct': 'x² - 5x + 6 = 0',
    },
    {
      'name': 'T13P10',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve: The length of a rectangle is 2 more than its width. If its area is 15, find the dimensions.',
      'answers': 'Width = 3, Length = 5; Width = 2, Length = 4; Width = 5, Length = 7; Width = 1, Length = 3',
      'correct': 'Width = 3, Length = 5',
    },
    {
      'name': 'T13P11',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve: The quadratic equation x² - (k+2)x + k = 0 has a repeated root. Find k.',
      'answers': 'k = 4;k = 2;k = -2;k = 0',
      'correct': 'k = 0',
    },
    {
      'name': 'T13P12',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'A rectangle’s area is 24 and its perimeter is 20. Find its dimensions.',
      'answers': 'Width = 3, Length = 8; Width = 4, Length = 6; Width = 2, Length = 12; Width = 5, Length = 4.8',
      'correct': 'Width = 4, Length = 6',
    },
    {
      'name': 'T13P13',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve: The sum of the squares of two consecutive integers is 85. Find the integers.',
      'answers': '6 and 7; 5 and 6; 7 and 8; 4 and 5',
      'correct': '6 and 7',
    },
    {
      'name': 'T13P14',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'A quadratic function models a projectile: h(t)= -t² + 4t + 1. Find the time when the projectile reaches its maximum height.',
      'answers': 't = 2; t = 3; t = 1; t = 4',
      'correct': 't = 2',
    },
    {
      'name': 'T13P15',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve: The product of two numbers is 20 and their difference is 2. Find the numbers.',
      'answers': '4 and 5; 2 and 10; 4 and 6; 3 and 7',
      'correct': '4 and 5',
    },
    {
      'name': 'T13P16',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'A quadratic equation has roots in the ratio 2:3 and a sum of 25. Find the roots.',
      'answers': '10 and 15; 8 and 12; 9 and 16; 7 and 18',
      'correct': '10 and 15',
    },
    {
      'name': 'T13P17',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'Solve: The sum of two numbers is 12 and the sum of their squares is 74. Find the numbers.',
      'answers': '5 and 7; 4 and 8; 6 and 6; 3 and 9',
      'correct': '5 and 7',
    },
    {
      'name': 'T13P18',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'A quadratic equation representing a rectangle’s area is given by x² - 5x + k = 0. If the rectangle’s area is 6, find k.',
      'answers': 'k = 6; k = 4; k = 5; k = 3',
      'correct': 'k = 4',
    },
    {
      'name': 'T13P19',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 3,
      'content': 'Solve: The sum of two numbers is 10 and their product is 21. Find the numbers.',
      'answers': 'x = 3 and 7; x = 2 and 8; x = 4 and 6; x = 5 and 5',
      'correct': 'x = 3 and 7',
    },
    {
      'name': 'T13P20',
      'category': 'Algebra',
      'topic': 13,
      'difficulty': 4,
      'content': 'A quadratic function models the profit P(x)= -x² + 10x - 16. Find the number of items x that maximize profit.',
      'answers': 'x = 5; x = 4; x = 6; x = 7',
      'correct': 'x = 5',
    },
  ];