const List<Map<String, dynamic>> geoProblems = [
    // Topic 1: Foundations for Geometry
    {
      'name': 'T1P1',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Which of the following is an undefined term in geometry?',
      'answers': 'Point;Line;Plane;All of the above',
      'correct': 'All of the above',
    },
    {
      'name': 'T1P2',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'A point has no ____.',
      'answers': 'Dimension;Length;Width;Area',
      'correct': 'Dimension',
    },
    {
      'name': 'T1P3',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 1,
      'content': 'A line is defined as a collection of ______.',
      'answers': 'Points;Angles;Segments;Curves',
      'correct': 'Points',
    },
    {
      'name': 'T1P4',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 1,
      'content': 'Which term best describes a flat surface that extends infinitely in all directions?',
      'answers': 'Line;Plane;Space;Solid',
      'correct': 'Plane',
    },
    {
      'name': 'T1P5',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Two distinct points determine a ____.',
      'answers': 'Line;Segment;Ray;Plane',
      'correct': 'Line',
    },
    {
      'name': 'T1P6',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'The distance between two points in the coordinate plane is given by the ______.',
      'answers': 'Midpoint formula;Distance formula;Slope formula;Area formula',
      'correct': 'Distance formula',
    },
    {
      'name': 'T1P7',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'Find the midpoint of the segment joining (2,3) and (8,11).',
      'answers': '(5,7); (4,7); (5,8); (6,7)',
      'correct': '(5,7)',
    },
    {
      'name': 'T1P8',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'What is the sum of the interior angles of a quadrilateral?',
      'answers': '180°; 360°; 270°; 90°',
      'correct': '360°',
    },
    {
      'name': 'T1P9',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'A ray has a starting point and ______.',
      'answers': 'an endpoint; no endpoint; two endpoints; infinite endpoints',
      'correct': 'no endpoint',
    },
    {
      'name': 'T1P10',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 1,
      'content': 'A line segment has two endpoints. True or False?',
      'answers': 'True;False',
      'correct': 'True',
    },
    {
      'name': 'T1P11',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'What is the measure of a right angle?',
      'answers': '45°;60°;90°;120°',
      'correct': '90°',
    },
    {
      'name': 'T1P12',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'If two angles are complementary and one is 35°, the other is ____.',
      'answers': '55°;45°;65°;75°',
      'correct': '55°',
    },
    {
      'name': 'T1P13',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'What is the sum of the interior angles of a pentagon?',
      'answers': '360°;540°;720°;180°',
      'correct': '540°',
    },
    {
      'name': 'T1P14',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'Which term describes points that lie on the same line?',
      'answers': 'Collinear;Concurrent;Coplanar;Colinear',
      'correct': 'Collinear',
    },
    {
      'name': 'T1P15',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'What is the sum of the exterior angles of any convex polygon?',
      'answers': '180°;360°;540°;720°',
      'correct': '360°',
    },
    {
      'name': 'T1P16',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Which of the following is a property of a plane?',
      'answers': 'It is one-dimensional; It has no thickness; It has finite area; It is curved',
      'correct': 'It has no thickness',
    },
    {
      'name': 'T1P17',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'How many points are needed to determine a unique plane?',
      'answers': '2; 3 non-collinear points; 4; 1',
      'correct': '3 non-collinear points',
    },
    {
      'name': 'T1P18',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Which term best describes a flat surface that extends infinitely?',
      'answers': 'Line; Plane; Curve; Angle',
      'correct': 'Plane',
    },
    {
      'name': 'T1P19',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'A segment with endpoints (1,2) and (7,8) has a midpoint of ____.',
      'answers': '(4,5); (3,4); (4,6); (5,5)',
      'correct': '(4,5)',
    },
    {
      'name': 'T1P20',
      'category': 'Geometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'What is the measure of a full rotation?',
      'answers': '180°; 360°; 90°; 270°',
      'correct': '360°',
    },

    // Topic 2: Geometric Reasoning
    {
      'name': 'T2P1',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If ∠A and ∠B are complementary and m∠A = 40°, what is m∠B?',
      'answers': '50°; 55°; 60°; 40°',
      'correct': '50°',
    },
    {
      'name': 'T2P2',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If two lines form a linear pair and one angle is 110°, what is the measure of its adjacent angle?',
      'answers': '70°; 80°; 90°; 110°',
      'correct': '70°',
    },
    {
      'name': 'T2P3',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'If a triangle’s angles are in the ratio 2:3:4, what is the measure of the largest angle?',
      'answers': '80°; 90°; 100°; 120°',
      'correct': '100°',
    },
    {
      'name': 'T2P4',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If two angles are supplementary and one measures 130°, what is the measure of the other?',
      'answers': '50°; 60°; 70°; 80°',
      'correct': '50°',
    },
    {
      'name': 'T2P5',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'If two angles are complementary and one measures 25°, what is the measure of the other?',
      'answers': '65°; 75°; 85°; 95°',
      'correct': '65°',
    },
    {
      'name': 'T2P6',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'A quadrilateral’s interior angles sum to 360°. If three angles are 80°, 110°, and 95°, what is the fourth angle?',
      'answers': '75°; 85°; 90°; 95°',
      'correct': '85°',
    },
    {
      'name': 'T2P7',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'If two lines are complementary and one is 60°, the other is ____.',
      'answers': '30°; 40°; 50°; 60°',
      'correct': '30°',
    },
    {
      'name': 'T2P8',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'A transversal intersects two parallel lines. Which angle pair are congruent?',
      'answers': 'Alternate interior angles; Supplementary angles; Complementary angles; Vertical angles',
      'correct': 'Alternate interior angles',
    },
    {
      'name': 'T2P9',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If two lines are perpendicular, what is the product of their slopes?',
      'answers': '–1; 0; 1; Undefined',
      'correct': '–1',
    },
    {
      'name': 'T2P10',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'If ∠X = 25° and ∠Y = 65°, are these complementary, supplementary, or neither?',
      'answers': 'Complementary; Supplementary; Neither; Both',
      'correct': 'Complementary',
    },
    {
      'name': 'T2P11',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'In a triangle, if one angle is 90° and another is 35°, what is the third angle?',
      'answers': '55°; 65°; 75°; 85°',
      'correct': '55°',
    },
    {
      'name': 'T2P12',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'A parallelogram has one angle of 70°. What is the measure of its adjacent angle?',
      'answers': '110°; 70°; 90°; 100°',
      'correct': '110°',
    },
    {
      'name': 'T2P13',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'If two angles form a linear pair and one is 150°, what is the other?',
      'answers': '30°; 60°; 90°; 150°',
      'correct': '30°',
    },
    {
      'name': 'T2P14',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'Determine the missing angle if a triangle has angles 50° and 60°.',
      'answers': '70°; 80°; 90°; 100°',
      'correct': '70°',
    },
    {
      'name': 'T2P15',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'If two angles are supplementary and one is 95°, the other is ____.',
      'answers': '85°; 75°; 65°; 55°',
      'correct': '85°',
    },
    {
      'name': 'T2P16',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If a rectangle’s angles are 90° each, what can be said about its diagonals?',
      'answers': 'They are congruent; They are perpendicular; They bisect each other; They are equal in length',
      'correct': 'They are congruent',
    },
    {
      'name': 'T2P17',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'Which pair of angles in a transversal intersecting parallel lines are equal?',
      'answers': 'Corresponding angles; Alternate interior angles; Both; None',
      'correct': 'Both (they are equal)',
    },
    {
      'name': 'T2P18',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If two lines intersect, what can be said about the vertical angles?',
      'answers': 'They are congruent; They are supplementary; They are complementary; They are equal to 90°',
      'correct': 'They are congruent',
    },
    {
      'name': 'T2P19',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'In a triangle, if two angles are equal, what type of triangle is it?',
      'answers': 'Isosceles; Equilateral; Scalene; Right',
      'correct': 'Isosceles',
    },
    {
      'name': 'T2P20',
      'category': 'Geometry',
      'topic': 2,
      'difficulty': 3,
      'content': 'If ∠A = 40° and ∠B = 80°, what is ∠C in a triangle?',
      'answers': '60°; 70°; 60°; 100°',
      'correct': '60°',
    },

    // Topic 3: Parallel and Perpendicular Lines
    {
      'name': 'T3P1',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Two lines with slopes 2 and 2 are ______.',
      'answers': 'Parallel; Perpendicular; Neither; Coincident',
      'correct': 'Parallel',
    },
    {
      'name': 'T3P2',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Two lines are perpendicular if the product of their slopes is ____.',
      'answers': '-1; 0; 1; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T3P3',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Find the slope of a line parallel to the line 3x - 4y = 12.',
      'answers': '3/4; -3/4; 4/3; -4/3',
      'correct': '3/4',
    },
    {
      'name': 'T3P4',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Find the slope of a line perpendicular to the line y = (1/2)x + 3.',
      'answers': '-2; 2; -1/2; 1/2',
      'correct': '-2',
    },
    {
      'name': 'T3P5',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'If line L has slope 5, a line parallel to L will have slope ____.',
      'answers': '5; -5; 1/5; -1/5',
      'correct': '5',
    },
    {
      'name': 'T3P6',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'A line with slope -3 is perpendicular to a line with slope ____.',
      'answers': '1/3; -1/3; 3; -3',
      'correct': '1/3',
    },
    {
      'name': 'T3P7',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'The equation y = 2x + 1 has a slope of ____. A line parallel to it will have the same slope.',
      'answers': '2; -2; 1; -1',
      'correct': '2',
    },
    {
      'name': 'T3P8',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Find the slope of the line perpendicular to 4x + 2y = 8.',
      'answers': '-2; 2; -1/2; 1/2',
      'correct': '-2',
    },
    {
      'name': 'T3P9',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Two lines with slopes m₁ and m₂ are perpendicular if m₁·m₂ = ____.',
      'answers': '-1; 0; 1; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T3P10',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'What is the slope of a line parallel to y = -3x + 4?',
      'answers': '-3; 3; 1/3; -1/3',
      'correct': '-3',
    },
    {
      'name': 'T3P11',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'If two lines are perpendicular, one has slope 7. What is the slope of the other?',
      'answers': '-7; 1/7; -1/7; 7',
      'correct': '-1/7',
    },
    {
      'name': 'T3P12',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Find the slope of a line perpendicular to the line 5x - 2y = 10.',
      'answers': '5/2; -5/2; 2/5; -2/5',
      'correct': '2/5', // (Because rewriting gives y = (5/2)x - 5, so perpendicular slope is -2/5)
    },
    {
      'name': 'T3P13',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Which statement is true about parallel lines in a plane?',
      'answers': 'They never intersect; They intersect at one point; They are perpendicular; They intersect infinitely',
      'correct': 'They never intersect',
    },
    {
      'name': 'T3P14',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'What is the slope of a line perpendicular to a horizontal line?',
      'answers': 'Undefined; 0; 1; -1',
      'correct': 'Undefined',
    },
    {
      'name': 'T3P15',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'A vertical line has an undefined slope. True or False?',
      'answers': 'True; False',
      'correct': 'True',
    },
    {
      'name': 'T3P16',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'The slope of the line y = -4 is ____.',
      'answers': '-4; 4; 0; Undefined',
      'correct': '0',
    },
    {
      'name': 'T3P17',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'If a line has slope 1/2, a perpendicular line will have slope ____.',
      'answers': '-2; 2; -1/2; 1/2',
      'correct': '-2',
    },
    {
      'name': 'T3P18',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'A line parallel to y = 3x + 7 must have a slope of ____.',
      'answers': '3; 7; -3; 1/3',
      'correct': '3',
    },
    {
      'name': 'T3P19',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Find the slope of the line: 2x + 3y = 12.',
      'answers': '-2/3; 2/3; 3/2; -3/2',
      'correct': '-2/3',
    },
    {
      'name': 'T3P20',
      'category': 'Geometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Two lines with slopes 4 and m are perpendicular. Find m.',
      'answers': '-1/4; 1/4; -4; 4',
      'correct': '-1/4',
    },

    // Topic 4: Triangle Congruence
    {
      'name': 'T4P1',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Which of the following is a triangle congruence postulate?',
      'answers': 'SSS; SAS; ASA; All of the above',
      'correct': 'All of the above',
    },
    {
      'name': 'T4P2',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'If two triangles have three pairs of congruent sides, they are congruent by the ____ postulate.',
      'answers': 'SSS; SAS; ASA; AAS',
      'correct': 'SSS',
    },
    {
      'name': 'T4P3',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Triangles are congruent if two angles and the included side are congruent. Which postulate is this?',
      'answers': 'ASA; SAS; AAS; HL',
      'correct': 'ASA',
    },
    {
      'name': 'T4P4',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'In right triangles, congruence can be established using which theorem?',
      'answers': 'HL Theorem; SSS; SAS; ASA',
      'correct': 'HL Theorem',
    },
    {
      'name': 'T4P5',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Triangles with two pairs of congruent angles are congruent by the ____ postulate.',
      'answers': 'AAS; ASA; SSS; SAS',
      'correct': 'AAS',
    },
    {
      'name': 'T4P6',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'If two triangles have two sides and the included angle congruent, they are congruent by which postulate?',
      'answers': 'SAS; SSS; ASA; AAS',
      'correct': 'SAS',
    },
    {
      'name': 'T4P7',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Which postulate is used to prove triangle congruence when two angles and a non‐included side are congruent?',
      'answers': 'AAS; SAS; ASA; HL',
      'correct': 'AAS',
    },
    {
      'name': 'T4P8',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'If two triangles have congruent hypotenuses and one leg congruent, they are congruent by ____.',
      'answers': 'HL; ASA; SAS; SSS',
      'correct': 'HL',
    },
    {
      'name': 'T4P9',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'What does the CPCTC acronym stand for in triangle congruence proofs?',
      'answers': 'Corresponding Parts of Congruent Triangles are Congruent; Common Parts are Congruent; Congruent Parts of Certain Triangles are Congruent; None of the above',
      'correct': 'Corresponding Parts of Congruent Triangles are Congruent',
    },
    {
      'name': 'T4P10',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'Which of the following is not a triangle congruence postulate or theorem?',
      'answers': 'SSS; SAS; ASA; RRA',
      'correct': 'RRA',
    },
    {
      'name': 'T4P11',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'If two triangles are congruent, then all of their corresponding ____ are congruent.',
      'answers': 'Sides; Angles; Both; Neither',
      'correct': 'Both',
    },
    {
      'name': 'T4P12',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'Which postulate requires that two angles and a non‐included side be congruent?',
      'answers': 'AAS; ASA; SAS; SSS',
      'correct': 'AAS',
    },
    {
      'name': 'T4P13',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Triangles are congruent if they have all corresponding sides equal. This is the ____ postulate.',
      'answers': 'SSS; SAS; ASA; HL',
      'correct': 'SSS',
    },
    {
      'name': 'T4P14',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'If triangle ABC is congruent to triangle DEF, then which statement is true?',
      'answers': '∠A = ∠D; AB = DE; BC = EF; All of the above',
      'correct': 'All of the above',
    },
    {
      'name': 'T4P15',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Which congruence theorem applies only to right triangles?',
      'answers': 'HL; SAS; SSS; ASA',
      'correct': 'HL',
    },
    {
      'name': 'T4P16',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'If two triangles have two pairs of congruent angles, they are congruent by which postulate?',
      'answers': 'AAS; SAS; ASA; SSS',
      'correct': 'AAS',
    },
    {
      'name': 'T4P17',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Triangle congruence can be used to prove which of the following is true?',
      'answers': 'Corresponding sides are equal; Corresponding angles are equal; Both; Neither',
      'correct': 'Both',
    },
    {
      'name': 'T4P18',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'Which theorem is used to prove that the base angles of an isosceles triangle are congruent?',
      'answers': 'Isosceles Triangle Theorem; CPCTC; Vertical Angles Theorem; Parallel Postulate',
      'correct': 'Isosceles Triangle Theorem',
    },
    {
      'name': 'T4P19',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'If two triangles have two congruent sides and the included angle congruent, they are congruent by the ____ postulate.',
      'answers': 'SAS; SSS; ASA; HL',
      'correct': 'SAS',
    },
    {
      'name': 'T4P20',
      'category': 'Geometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'Which congruence theorem is sometimes abbreviated as "HL"?',
      'answers': 'Hypotenuse-Leg; Half-Length; Height-Line; Horizontal-Line',
      'correct': 'Hypotenuse-Leg',
    },

    // Topic 5: Properties and Attributes of Triangles
    {
      'name': 'T5P1',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'What is the sum of the interior angles of a triangle?',
      'answers': '180°; 360°; 90°; 270°',
      'correct': '180°',
    },
    {
      'name': 'T5P2',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'In an isosceles triangle, the base angles are ____.',
      'answers': 'Congruent; Supplementary; Complementary; Equal to the vertex angle',
      'correct': 'Congruent',
    },
    {
      'name': 'T5P3',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'What is an altitude in a triangle?',
      'answers': 'A segment from a vertex perpendicular to the opposite side; A segment connecting midpoints; The longest side; A bisector of an angle',
      'correct': 'A segment from a vertex perpendicular to the opposite side',
    },
    {
      'name': 'T5P4',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'What is the median of a triangle?',
      'answers': 'A line from a vertex to the midpoint of the opposite side; A line perpendicular to a side; An angle bisector; The longest side',
      'correct': 'A line from a vertex to the midpoint of the opposite side',
    },
    {
      'name': 'T5P5',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'In a triangle, an angle bisector divides the opposite side into segments proportional to ____.',
      'answers': 'Adjacent sides; The angles; The medians; The altitudes',
      'correct': 'Adjacent sides',
    },
    {
      'name': 'T5P6',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Which point of concurrency is found at the intersection of the altitudes of a triangle?',
      'answers': 'Orthocenter; Centroid; Incenter; Circumcenter',
      'correct': 'Orthocenter',
    },
    {
      'name': 'T5P7',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'What is the centroid of a triangle?',
      'answers': 'The point where the medians intersect; The point where the altitudes intersect; The center of the circumscribed circle; The midpoint of a side',
      'correct': 'The point where the medians intersect',
    },
    {
      'name': 'T5P8',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Which point is equidistant from all three sides of a triangle?',
      'answers': 'Incenter; Centroid; Orthocenter; Circumcenter',
      'correct': 'Incenter',
    },
    {
      'name': 'T5P9',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'What is the circumcenter of a triangle?',
      'answers': 'The intersection of the perpendicular bisectors of the sides; The intersection of the medians; The intersection of the altitudes; The center of the inscribed circle',
      'correct': 'The intersection of the perpendicular bisectors of the sides',
    },
    {
      'name': 'T5P10',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Which line divides a triangle into two regions of equal area?',
      'answers': 'Median; Altitude; Angle bisector; Perpendicular bisector',
      'correct': 'Median',
    },
    {
      'name': 'T5P11',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'What is the measure of each angle in an equilateral triangle?',
      'answers': '60°; 90°; 45°; 120°',
      'correct': '60°',
    },
    {
      'name': 'T5P12',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'If the sides of a triangle are 3, 4, and 5, what type of triangle is it?',
      'answers': 'Right; Acute; Obtuse; Equilateral',
      'correct': 'Right',
    },
    {
      'name': 'T5P13',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'Which segment in a triangle is always shorter than the sum of the other two sides?',
      'answers': 'Any side; Only the longest side; Only the shortest side; None',
      'correct': 'Any side',
    },
    {
      'name': 'T5P14',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'What is the area formula for a triangle?',
      'answers': '1/2 * base * height; base * height; base + height; 2 * base * height',
      'correct': '1/2 * base * height',
    },
    {
      'name': 'T5P15',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'The three medians of a triangle intersect at a point called the ____.',
      'answers': 'Centroid; Orthocenter; Incenter; Circumcenter',
      'correct': 'Centroid',
    },
    {
      'name': 'T5P16',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'If the altitude of a triangle divides the base into segments of lengths 3 and 5, what is one possible length of the altitude (given the triangle is right-angled)?',
      'answers': '4; √15; 4√2; 8',
      'correct': '4',
    },
    {
      'name': 'T5P17',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In a triangle, if the medians are 5, 6, and 7, which point is their intersection called?',
      'answers': 'Centroid; Incenter; Circumcenter; Orthocenter',
      'correct': 'Centroid',
    },
    {
      'name': 'T5P18',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'What property do the altitudes of a triangle always share?',
      'answers': 'They are concurrent; They are equal in length; They bisect the sides; They form a right angle',
      'correct': 'They are concurrent',
    },
    {
      'name': 'T5P19',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Which theorem helps prove that the medians of a triangle intersect at a single point?',
      'answers': 'Ceva’s Theorem; Pythagorean Theorem; Triangle Sum Theorem; Angle Bisector Theorem',
      'correct': 'Ceva’s Theorem',
    },
    {
      'name': 'T5P20',
      'category': 'Geometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'What is the significance of the incenter of a triangle?',
      'answers': 'It is equidistant from all sides; It is the midpoint of the base; It is the intersection of medians; It is the farthest point from the vertices',
      'correct': 'It is equidistant from all sides',
    },

    // Topic 6: Polygons and Quadrilaterals
    {
      'name': 'T6P1',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'What is the sum of the interior angles of a quadrilateral?',
      'answers': '360°; 180°; 270°; 540°',
      'correct': '360°',
    },
    {
      'name': 'T6P2',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'A regular pentagon has interior angles measuring ____ each.',
      'answers': '108°; 120°; 90°; 100°',
      'correct': '108°',
    },
    {
      'name': 'T6P3',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'How many sides does a hexagon have?',
      'answers': '5;6;7;8',
      'correct': '6',
    },
    {
      'name': 'T6P4',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'What is the sum of the exterior angles of any convex polygon?',
      'answers': '360°;180°;540°;720°',
      'correct': '360°',
    },
    {
      'name': 'T6P5',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Which quadrilateral has both pairs of opposite sides parallel and equal in length?',
      'answers': 'Rectangle; Rhombus; Parallelogram; All of the above',
      'correct': 'All of the above',
    },
    {
      'name': 'T6P6',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'What is the measure of each interior angle in a regular octagon?',
      'answers': '135°;140°;150°;120°',
      'correct': '135°',
    },
    {
      'name': 'T6P7',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'A trapezoid has one pair of parallel sides. True or False?',
      'answers': 'True;False',
      'correct': 'True',
    },
    {
      'name': 'T6P8',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find the measure of each interior angle of a regular decagon.',
      'answers': '144°;156°;162°;180°',
      'correct': '144°',
    },
    {
      'name': 'T6P9',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'How many diagonals does a pentagon have?',
      'answers': '5;7;10;8',
      'correct': '5',
    },
    {
      'name': 'T6P10',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Which polygon has interior angles summing to 900°?',
      'answers': 'Nonagon; Octagon; Heptagon; Decagon',
      'correct': 'Nonagon',
    },
    {
      'name': 'T6P11',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'What is a regular polygon?',
      'answers': 'All sides and angles are equal; Only sides are equal; Only angles are equal; None of the above',
      'correct': 'All sides and angles are equal',
    },
    {
      'name': 'T6P12',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'In a parallelogram, opposite angles are ____.',
      'answers': 'Congruent; Supplementary; Complementary; Equal to 90°',
      'correct': 'Congruent',
    },
    {
      'name': 'T6P13',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'A rhombus is a quadrilateral with ____.',
      'answers': 'All sides equal; Opposite sides equal; All angles equal; Two pairs of equal sides',
      'correct': 'All sides equal',
    },
    {
      'name': 'T6P14',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'What is the measure of an exterior angle of a regular hexagon?',
      'answers': '60°;90°;120°;180°',
      'correct': '60°',
    },
    {
      'name': 'T6P15',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'A quadrilateral with only one pair of parallel sides is called a ____.',
      'answers': 'Trapezoid; Parallelogram; Kite; Rhombus',
      'correct': 'Trapezoid',
    },
    {
      'name': 'T6P16',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'The sum of the interior angles of an n-sided polygon is given by ____.',
      'answers': '(n-2)*180°; n*180°; (n+2)*180°; (n-1)*180°',
      'correct': '(n-2)*180°',
    },
    {
      'name': 'T6P17',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'A regular quadrilateral is called a ____.',
      'answers': 'Square; Rectangle; Rhombus; Parallelogram',
      'correct': 'Square',
    },
    {
      'name': 'T6P18',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Which quadrilateral has one pair of parallel sides?',
      'answers': 'Trapezoid; Rectangle; Square; Rhombus',
      'correct': 'Trapezoid',
    },
    {
      'name': 'T6P19',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'How many sides does a decagon have?',
      'answers': '8;9;10;11',
      'correct': '10',
    },
    {
      'name': 'T6P20',
      'category': 'Geometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'What is the sum of the interior angles of a regular octagon?',
      'answers': '1080°;108°;720°;900°',
      'correct': '1080°',
    },

    // Topic 7: Similarity
    {
      'name': 'T7P1',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Two figures are similar if their corresponding angles are ____ and corresponding sides are in ____.',
      'answers': 'Congruent; Proportion; Complementary; Equal',
      'correct': 'Congruent; Proportion',
    },
    {
      'name': 'T7P2',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'If two similar triangles have side lengths in the ratio 3:5, the ratio of their areas is ____.',
      'answers': '9:25; 3:5; 5:3; 15:25',
      'correct': '9:25',
    },
    {
      'name': 'T7P3',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'If triangles ABC and DEF are similar and AB = 4, DE = 6, find the scale factor.',
      'answers': '3/2; 2/3; 4/6; 6/4',
      'correct': '3/2',
    },
    {
      'name': 'T7P4',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Similar figures have corresponding sides in ratio 2:3. If a side in the smaller figure is 10, the corresponding side in the larger figure is ____.',
      'answers': '15; 12; 20; 18',
      'correct': '15',
    },
    {
      'name': 'T7P5',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'In similar polygons, the ratio of perimeters equals the ratio of ____.',
      'answers': 'Areas; Side lengths; Angles; Diagonals',
      'correct': 'Side lengths',
    },
    {
      'name': 'T7P6',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'If two similar triangles have areas 18 and 50, the ratio of their corresponding sides is ____ (simplified).',
      'answers': '√(18/50); 18:50; 3:5; 5:3',
      'correct': '√(18/50)',
    },
    {
      'name': 'T7P7',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Two similar figures have a scale factor of 1:4. The area of the smaller figure is 10. What is the area of the larger figure?',
      'answers': '40; 160; 80; 20',
      'correct': '160',
    },
    {
      'name': 'T7P8',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'If two similar rectangles have lengths in the ratio 3:5 and the smaller has an area of 24, the larger has an area of ____.',
      'answers': '40; 48; 66.67; 100',
      'correct': '66.67',
    },
    {
      'name': 'T7P9',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'If two similar triangles have a scale factor of 1:3, the ratio of their perimeters is ____.',
      'answers': '1:3; 1:9; 3:1; 9:1',
      'correct': '1:3',
    },
    {
      'name': 'T7P10',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'If two similar figures have corresponding side lengths 4 and 10, what is the scale factor from the smaller to the larger?',
      'answers': '2.5; 2; 1.5; 3',
      'correct': '2.5',
    },
    {
      'name': 'T7P11',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Two similar triangles have corresponding sides 5 and 15. What is the ratio of their areas?',
      'answers': '1:9; 1:3; 3:1; 1:5',
      'correct': '1:9',
    },
    {
      'name': 'T7P12',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'If two similar polygons have a scale factor of 2:5, the ratio of their areas is ____.',
      'answers': '4:25; 2:5; 5:2; 1:2',
      'correct': '4:25',
    },
    {
      'name': 'T7P13',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'If two similar triangles have corresponding sides 7 and 14, then the scale factor is ____.',
      'answers': '1:2; 2:1; 1:7; 7:14',
      'correct': '1:2',
    },
    {
      'name': 'T7P14',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Two similar figures have a scale factor of 3:4. If the smaller has a perimeter of 18, the larger has a perimeter of ____.',
      'answers': '24; 20; 21; 22',
      'correct': '24',
    },
    {
      'name': 'T7P15',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'If two similar triangles have side ratios of 1:2, the ratio of their areas is ____.',
      'answers': '1:4; 1:2; 2:1; 1:3',
      'correct': '1:4',
    },
    {
      'name': 'T7P16',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'In similar figures, corresponding angles are always ____.',
      'answers': 'Congruent; Supplementary; Equal to 90°; Proportional',
      'correct': 'Congruent',
    },
    {
      'name': 'T7P17',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'If two similar triangles have areas 18 and 50, the ratio of their side lengths is ____.',
      'answers': '√(18/50); 18:50; 3:5; 5:3',
      'correct': '√(18/50)',
    },
    {
      'name': 'T7P18',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Two similar rectangles have a scale factor of 2:3. If the smaller rectangle has an area of 20, the larger has an area of ____.',
      'answers': '30; 40; 45; 50',
      'correct': '45',
    },
    {
      'name': 'T7P19',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'If two similar figures have a scale factor of 1:3, then the ratio of their perimeters is ____.',
      'answers': '1:3; 1:9; 3:1; 9:1',
      'correct': '1:3',
    },
    {
      'name': 'T7P20',
      'category': 'Geometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'If two similar triangles have side lengths in the ratio 4:7, what is the ratio of their areas?',
      'answers': '16:49; 4:7; 7:4; 1:1',
      'correct': '16:49',
    },

    // Topic 8: Right Triangles and Trigonometry
    {
      'name': 'T8P1',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'In a right triangle with legs 3 and 4, what is the length of the hypotenuse?',
      'answers': '5; 6; 7; 4',
      'correct': '5',
    },
    {
      'name': 'T8P2',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Find sin θ for a right triangle where the opposite side is 4 and the hypotenuse is 5.',
      'answers': '0.8; 0.6; 0.75; 1',
      'correct': '0.8',
    },
    {
      'name': 'T8P3',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Find cos θ if the adjacent side is 3 and the hypotenuse is 5.',
      'answers': '0.6; 0.8; 0.75; 1',
      'correct': '0.6',
    },
    {
      'name': 'T8P4',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'If a right triangle has an angle of 30°, what is the ratio of the opposite side to the hypotenuse?',
      'answers': '1:2; √3:2; 2:1; 1:√3',
      'correct': '1:2',
    },
    {
      'name': 'T8P5',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'What is tan θ for a right triangle with opposite side 4 and adjacent side 3?',
      'answers': '4/3; 3/4; 1; 7/3',
      'correct': '4/3',
    },
    {
      'name': 'T8P6',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'In a right triangle, if one acute angle is 60°, what is cos 60°?',
      'answers': '0.5; 0.6; 0.8; 1',
      'correct': '0.5',
    },
    {
      'name': 'T8P7',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Find the missing leg of a right triangle with hypotenuse 13 and one leg 5.',
      'answers': '12; 10; 8; 9',
      'correct': '12',
    },
    {
      'name': 'T8P8',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'What is the Pythagorean Theorem?',
      'answers': 'a² + b² = c²; a + b = c; a² - b² = c²; 2a + 2b = c',
      'correct': 'a² + b² = c²',
    },
    {
      'name': 'T8P9',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'If sin θ = 0.6 and cos θ = 0.8, what is tan θ?',
      'answers': '0.75; 1.33; 1.2; 0.8',
      'correct': '0.75',
    },
    {
      'name': 'T8P10',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Find the length of the hypotenuse of a right triangle with legs 6 and 8.',
      'answers': '10; 12; 14; 16',
      'correct': '10',
    },
    {
      'name': 'T8P11',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'A right triangle has one angle of 45°. What is the ratio of the legs?',
      'answers': '1:1; 1:√2; √2:1; 1:2',
      'correct': '1:1',
    },
    {
      'name': 'T8P12',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'What is the area of a right triangle with legs 5 and 12?',
      'answers': '30; 25; 60; 17.5',
      'correct': '30',
    },
    {
      'name': 'T8P13',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Find sin 30°.',
      'answers': '0.5; 0.6; 0.7; 0.8',
      'correct': '0.5',
    },
    {
      'name': 'T8P14',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Find cos 45°.',
      'answers': '0.71; 0.5; 0.87; 1',
      'correct': '0.71',
    },
    {
      'name': 'T8P15',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Find tan 45°.',
      'answers': '1; 0; 0.5; √2',
      'correct': '1',
    },
    {
      'name': 'T8P16',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'If a right triangle has legs 7 and 24, find the hypotenuse.',
      'answers': '25; 26; 24; 23',
      'correct': '25',
    },
    {
      'name': 'T8P17',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'In a right triangle, if one angle is 30° and the hypotenuse is 10, find the length of the side opposite 30°.',
      'answers': '5; 5.0; 10; 8.66',
      'correct': '5',
    },
    {
      'name': 'T8P18',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'If cos θ = 0.8 in a right triangle, what is sin θ (assume θ is acute)?',
      'answers': '0.6; 0.8; 0.5; 1',
      'correct': '0.6',
    },
    {
      'name': 'T8P19',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Find the area of a right triangle with legs 9 and 12.',
      'answers': '54; 48; 60; 63',
      'correct': '54',
    },
    {
      'name': 'T8P20',
      'category': 'Geometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'If tan θ = 3/4 in a right triangle, find sin θ (assume θ is acute).',
      'answers': '0.6; 0.75; 0.8; 0.5',
      'correct': '0.6',
    },

    // Topic 9: Extending Perimeter, Circumference, and Area
    {
      'name': 'T9P1',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'What is the formula for the perimeter of a rectangle?',
      'answers': '2(l+w); l+w; 2l+2w; l*w',
      'correct': '2l+2w',
    },
    {
      'name': 'T9P2',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find the circumference of a circle with radius 7 (use π = 3.14).',
      'answers': '43.96; 44; 45; 42',
      'correct': '43.96',
    },
    {
      'name': 'T9P3',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Calculate the area of a circle with diameter 10 (use π = 3.14).',
      'answers': '78.5; 80; 75; 90',
      'correct': '78.5',
    },
    {
      'name': 'T9P4',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find the perimeter of a regular hexagon with side length 5.',
      'answers': '30; 25; 35; 40',
      'correct': '30',
    },
    {
      'name': 'T9P5',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'A rectangle has a length of 12 and width of 7. Find its area and perimeter.',
      'answers': 'Area: 84, Perimeter: 38; Area: 84, Perimeter: 40; Area: 84, Perimeter: 36; Area: 80, Perimeter: 38',
      'correct': 'Area: 84, Perimeter: 38',
    },
    {
      'name': 'T9P6',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Find the area of a trapezoid with bases 8 and 12 and height 5.',
      'answers': '50; 40; 45; 55',
      'correct': '50',
    },
    {
      'name': 'T9P7',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'What is the formula for the area of a rectangle?',
      'answers': 'l*w; 2l+2w; (l+w)/2; l+w',
      'correct': 'l*w',
    },
    {
      'name': 'T9P8',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'A circle’s circumference is 31.4. What is its radius? (use π = 3.14)',
      'answers': '5; 4; 6; 7',
      'correct': '5',
    },
    {
      'name': 'T9P9',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'If a square has a side length of 8, what is its area?',
      'answers': '64; 32; 16; 72',
      'correct': '64',
    },
    {
      'name': 'T9P10',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Find the perimeter of a circle with radius 10 (use π = 3.14).',
      'answers': '62.8; 62; 63; 64',
      'correct': '62.8',
    },
    {
      'name': 'T9P11',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'The formula for the area of a circle is ____.',
      'answers': 'πr²; 2πr; πd; 2πr²',
      'correct': 'πr²',
    },
    {
      'name': 'T9P12',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'A rectangle’s length is twice its width. If the perimeter is 36, find the area.',
      'answers': '72; 64; 54; 80',
      'correct': '72',
    },
    {
      'name': 'T9P13',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find the circumference of a circle with diameter 14 (use π = 3.14).',
      'answers': '43.96; 44; 45; 46',
      'correct': '43.96',
    },
    {
      'name': 'T9P14',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'A regular pentagon has a side length of 6. Find its perimeter.',
      'answers': '30; 24; 36; 18',
      'correct': '30',
    },
    {
      'name': 'T9P15',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'If a composite figure consists of a rectangle (l=10, w=5) and a semicircle (diameter=5), find the total perimeter (exclude the common side).',
      'answers': '25 + (5π/2); 25 + (5π); 30 + (5π/2); 30 + (5π)',
      'correct': '25 + (5π/2)',
    },
    {
      'name': 'T9P16',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find the area of a square with side length 9.',
      'answers': '81; 72; 90; 99',
      'correct': '81',
    },
    {
      'name': 'T9P17',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'A rectangle has an area of 50 and a length of 10. What is its width?',
      'answers': '5; 4; 6; 7',
      'correct': '5',
    },
    {
      'name': 'T9P18',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find the perimeter of a triangle with sides 3, 4, and 5.',
      'answers': '12; 11; 10; 9',
      'correct': '12',
    },
    {
      'name': 'T9P19',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'A circle has a circumference of 50.24. What is its area? (use π = 3.14)',
      'answers': '200; 160; 180; 220',
      'correct': '200',
    },
    {
      'name': 'T9P20',
      'category': 'Geometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'If the perimeter of a rectangle is 32 and its length is 10, what is its area?',
      'answers': '60; 80; 100; 120',
      'correct': '60',
    },

    // Topic 10: Spatial Reasoning
    {
      'name': 'T10P1',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'What is the number of faces on a cube?',
      'answers': '4; 6; 8; 12',
      'correct': '6',
    },
    {
      'name': 'T10P2',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'How many edges does a rectangular prism have?',
      'answers': '8; 10; 12; 14',
      'correct': '12',
    },
    {
      'name': 'T10P3',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'How many vertices does a pyramid with a square base have?',
      'answers': '4; 5; 6; 8',
      'correct': '5',
    },
    {
      'name': 'T10P4',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'A net of a cube has 6 congruent squares. How many faces does the cube have?',
      'answers': '5; 6; 7; 8',
      'correct': '6',
    },
    {
      'name': 'T10P5',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'What is the surface area of a cube with side length 3?',
      'answers': '54; 36; 27; 48',
      'correct': '54',
    },
    {
      'name': 'T10P6',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'What is the volume of a rectangular prism with dimensions 4, 5, and 6?',
      'answers': '120; 100; 110; 130',
      'correct': '120',
    },
    {
      'name': 'T10P7',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'A cylinder has a radius of 3 and height of 7. What is its volume? (Use π = 3.14)',
      'answers': '197.82; 188.4; 205.2; 210',
      'correct': '197.82',
    },
    {
      'name': 'T10P8',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'How many faces does a triangular prism have?',
      'answers': '5; 6; 7; 8',
      'correct': '5',
    },
    {
      'name': 'T10P9',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'What is the surface area of a sphere with radius 4? (Use π = 3.14, and 4πr²)',
      'answers': '201.06; 188.96; 201; 210',
      'correct': '201.06',
    },
    {
      'name': 'T10P10',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Find the volume of a cone with radius 3 and height 5. (Use π = 3.14, and V = 1/3πr²h)',
      'answers': '47.1; 45; 50; 40',
      'correct': '47.1',
    },
    {
      'name': 'T10P11',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'A rectangular prism has a length of 8, width of 3, and height of 2. What is its surface area?',
      'correct': '92',
      'answers': '92; 88; 96; 100',
    },
    {
      'name': 'T10P12',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'What is the lateral surface area of a cylinder with radius 5 and height 10? (Use L = 2πrh)',
      'answers': '314; 300; 320; 280',
      'correct': '314',
    },
    {
      'name': 'T10P13',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'How many edges does a cube have?',
      'answers': '8; 10; 12; 14',
      'correct': '12',
    },
    {
      'name': 'T10P14',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'A cylinder has a height of 12 and diameter of 8. Find its total surface area. (Use π = 3.14)',
      'answers': '402.24; 400; 390; 410',
      'correct': '402.24',
    },
    {
      'name': 'T10P15',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'What is the volume of a cube with side length 4?',
      'answers': '64; 48; 32; 16',
      'correct': '64',
    },
    {
      'name': 'T10P16',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Find the number of vertices of a pentagonal prism.',
      'answers': '10; 12; 14; 15',
      'correct': '10',
    },
    {
      'name': 'T10P17',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'What is the formula for the surface area of a cylinder?',
      'answers': '2πr² + 2πrh; πr² + 2πrh; 2πrh; πr²',
      'correct': '2πr² + 2πrh',
    },
    {
      'name': 'T10P18',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'If the volume of a cube is 125, what is the length of its edge?',
      'answers': '5; 6; 7; 8',
      'correct': '5',
    },
    {
      'name': 'T10P19',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'How many faces does a triangular prism have?',
      'answers': '4; 5; 6; 7',
      'correct': '5',
    },
    {
      'name': 'T10P20',
      'category': 'Geometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'A sphere has a volume of 288π. What is its radius? (Use V = 4/3πr³)',
      'answers': '6; 8; 9; 10',
      'correct': '6',
    },

    // Topic 11: Circles
    {
      'name': 'T11P1',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'What is the formula for the circumference of a circle?',
      'answers': '2πr; πr²; 2r; πd',
      'correct': '2πr',
    },
    {
      'name': 'T11P2',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Find the area of a circle with radius 7 (use π = 3.14).',
      'answers': '153.86; 154; 150; 160',
      'correct': '153.86',
    },
    {
      'name': 'T11P3',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'What is the length of an arc of a circle with radius 10 subtended by a 60° central angle? (Use π = 3.14)',
      'answers': '10.47; 10.5; 10.47; 11',
      'correct': '10.47',
    },
    {
      'name': 'T11P4',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Find the area of a sector of a circle with radius 8 and central angle 45° (in degrees).',
      'answers': '12.57; 16.76; 20.11; 10.05',
      'correct': '12.57',
    },
    {
      'name': 'T11P5',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'What is the diameter of a circle with circumference 31.4? (use π = 3.14)',
      'answers': '10; 8; 6; 12',
      'correct': '10',
    },
    {
      'name': 'T11P6',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'If two chords in a circle are congruent, then the arcs they subtend are ____.',
      'answers': 'Congruent; Supplementary; Complementary; None of these',
      'correct': 'Congruent',
    },
    {
      'name': 'T11P7',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Find the radius of a circle if its area is 78.5 (use π = 3.14).',
      'answers': '5; 4; 6; 7',
      'correct': '5',
    },
    {
      'name': 'T11P8',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'What is the measure of a central angle that subtends an arc length equal to the radius of the circle?',
      'answers': '57.3°; 60°; 45°; 90°',
      'correct': '57.3°',
    },
    {
      'name': 'T11P9',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Which of the following is true about a tangent to a circle?',
      'answers': 'It is perpendicular to the radius at the point of tangency; It intersects the circle at two points; It passes through the center; None of the above',
      'correct': 'It is perpendicular to the radius at the point of tangency',
    },
    {
      'name': 'T11P10',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'The measure of an inscribed angle is half the measure of its intercepted arc. True or False?',
      'answers': 'True; False',
      'correct': 'True',
    },
    {
      'name': 'T11P11',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Find the circumference of a circle with diameter 12 (use π = 3.14).',
      'answers': '37.68; 38; 36; 40',
      'correct': '37.68',
    },
    {
      'name': 'T11P12',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'What is the formula for the length of an arc?',
      'answers': 'Arc = (θ/360)*2πr; Arc = πr²; Arc = 2πr; Arc = (θ/180)*πr',
      'correct': 'Arc = (θ/360)*2πr',
    },
    {
      'name': 'T11P13',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Find the area of a circle with radius 5 (use π = 3.14).',
      'answers': '78.5; 75; 80; 85',
      'correct': '78.5',
    },
    {
      'name': 'T11P14',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'A chord of a circle is 8 units long and the radius is 5. Find the distance from the chord to the center.',
      'answers': '3; 4; 2; 1',
      'correct': '3',
    },
    {
      'name': 'T11P15',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'What is the relationship between the central angle and the inscribed angle that intercept the same arc?',
      'answers': 'Central is twice inscribed; Inscribed is twice central; They are equal; They add to 90°',
      'correct': 'Central is twice inscribed',
    },
    {
      'name': 'T11P16',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'If a circle has an area of 50.24, what is its approximate radius? (use π = 3.14)',
      'answers': '4;5;6;7',
      'correct': '4',
    },
    {
      'name': 'T11P17',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'A sector of a circle has an area of 25 and the circle’s radius is 5. Find the measure of the central angle (in degrees).',
      'answers': '90°;120°;150°;180°',
      'correct': '180°',
    },
    {
      'name': 'T11P18',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'What is the formula for the area of a sector?',
      'answers': '(θ/360)*πr²; (θ/180)*πr²; 2πr; πr²',
      'correct': '(θ/360)*πr²',
    },
    {
      'name': 'T11P19',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'A tangent to a circle is perpendicular to the ____ at the point of tangency.',
      'answers': 'Radius; Chord; Diameter; Secant',
      'correct': 'Radius',
    },
    {
      'name': 'T11P20',
      'category': 'Geometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Which of the following is true about inscribed angles?',
      'answers': 'They measure half of their intercepted arcs; They measure twice their intercepted arcs; They are always 90°; None of these',
      'correct': 'They measure half of their intercepted arcs',
    },

    // Topic 12: Transformational Geometry
    {
      'name': 'T12P1',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What is a translation in geometry?',
      'answers': 'A slide; A rotation; A reflection; A dilation',
      'correct': 'A slide',
    },
    {
      'name': 'T12P2',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'A reflection across the y-axis will change the point (3, -4) to ____.',
      'answers': '(-3, -4); (3, 4); (-3, 4); (4, -3)',
      'correct': '(-3, -4)',
    },
    {
      'name': 'T12P3',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'What is a rotation of 90° clockwise about the origin of the point (2,3)?',
      'answers': '(3,-2); (-3,2); (-2,-3); (2,-3)',
      'correct': '(3,-2)',
    },
    {
      'name': 'T12P4',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'A dilation with a scale factor of 2 maps a point (x, y) to ____.',
      'answers': '(2x,2y); (x/2,y/2); (x+2,y+2); (2x,y)',
      'correct': '(2x,2y)',
    },
    {
      'name': 'T12P5',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What does a reflection produce?',
      'answers': 'A mirror image; A rotated image; A translated image; A dilated image',
      'correct': 'A mirror image',
    },
    {
      'name': 'T12P6',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'If a figure is reflected over the line y = x, what happens to the coordinates of a point (a, b)?',
      'answers': '(b, a); (–a, –b); (a, –b); (–b, a)',
      'correct': '(b, a)',
    },
    {
      'name': 'T12P7',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What is the effect of a dilation with a scale factor less than 1?',
      'answers': 'Reduction; Enlargement; Reflection; Translation',
      'correct': 'Reduction',
    },
    {
      'name': 'T12P8',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'A rotation of 180° about the origin will map (x, y) to ____.',
      'answers': '(-x, -y); (x, -y); (-x, y); (y, x)',
      'correct': '(-x, -y)',
    },
    {
      'name': 'T12P9',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'A translation shifts a figure by (3, -2). What happens to each coordinate?',
      'answers': 'Add 3 to x and subtract 2 from y; Add 2 to x and subtract 3 from y; Subtract 3 from x and add 2 to y; None of these',
      'correct': 'Add 3 to x and subtract 2 from y',
    },
    {
      'name': 'T12P10',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'What is the image of the point (4, 5) after a reflection across the x-axis?',
      'answers': '(4, -5); (-4, 5); (-4, -5); (5, 4)',
      'correct': '(4, -5)',
    },
    {
      'name': 'T12P11',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'A rotation of 90° counterclockwise about the origin transforms (1,0) to ____.',
      'answers': '(0,1); (0,-1); (–1,0); (1,0)',
      'correct': '(0,1)',
    },
    {
      'name': 'T12P12',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'What is the effect of reflecting a figure over the line x = 0?',
      'answers': 'It produces a mirror image across the y-axis; It rotates the figure 180°; It translates the figure horizontally; It dilates the figure',
      'correct': 'It produces a mirror image across the y-axis',
    },
    {
      'name': 'T12P13',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'A figure is dilated with a scale factor of 0.5. What happens to its area?',
      'answers': 'It becomes 0.25 times the original; 0.5 times; 2 times; 4 times',
      'correct': 'It becomes 0.25 times the original',
    },
    {
      'name': 'T12P14',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What is a translation?',
      'answers': 'A slide; A flip; A turn; A stretch',
      'correct': 'A slide',
    },
    {
      'name': 'T12P15',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'After a 270° clockwise rotation about the origin, what is the image of (2, -3)?',
      'answers': '(-3, -2); (3, 2); (–2, 3); (3, -2)',
      'correct': '(–2, 3)',
    },
    {
      'name': 'T12P16',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'Which transformation preserves the shape and size of a figure?',
      'answers': 'Translation; Dilation; Rotation; Reflection',
      'correct': 'Translation',
    },
    {
      'name': 'T12P17',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'What does a reflection do to a figure’s orientation?',
      'answers': 'Reverses it; Enlarges it; Shrinks it; Rotates it',
      'correct': 'Reverses it',
    },
    {
      'name': 'T12P18',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'A rotation leaves the size and shape of a figure ____.',
      'answers': 'Unchanged; Changed; Doubled; Halved',
      'correct': 'Unchanged',
    },
    {
      'name': 'T12P19',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'What is the net effect of a reflection followed by a translation?',
      'answers': 'A reflection and slide; A rotation; A dilation; A stretch',
      'correct': 'A reflection and slide',
    },
    {
      'name': 'T12P20',
      'category': 'Geometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Which transformation is defined by a fixed point and a rotation angle?',
      'answers': 'Rotation; Reflection; Translation; Dilation',
      'correct': 'Rotation',
    },
  ];