const List<Map<String, dynamic>> trigProblems = [
    // Topic 1: Right Triangles and Applications (20 problems)
    {
      'name': 'T1P1',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'In a right triangle with legs 3 and 4, find the hypotenuse.',
      'answers': '5;6;7;8',
      'correct': '5',
    },
    {
      'name': 'T1P2',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'In a right triangle with legs 6 and 8, find the hypotenuse.',
      'answers': '10;12;14;16',
      'correct': '10',
    },
    {
      'name': 'T1P3',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'A right triangle has one leg of length 5 and a hypotenuse of 13. Find the other leg.',
      'answers': '12;11;10;9',
      'correct': '12',
    },
    {
      'name': 'T1P4',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Find the area of a right triangle with legs 6 and 8.',
      'answers': '24;26;28;30',
      'correct': '24',
    },
    {
      'name': 'T1P5',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 1,
      'content': 'If one acute angle of a right triangle is 30°, what is the ratio of the side opposite to the hypotenuse?',
      'answers': '1:2; 1:√2; √3:2; 1:1',
      'correct': '1:2',
    },
    {
      'name': 'T1P6',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'A ladder 10 ft long leans against a wall making a 60° angle with the ground. Find the height reached on the wall (approx.).',
      'answers': '8.66 ft; 7.5 ft; 9 ft; 10 ft',
      'correct': '8.66 ft',
    },
    {
      'name': 'T1P7',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Find sinθ in a right triangle with opposite side 4 and hypotenuse 5.',
      'answers': '0.8; 0.6; 0.5; 1',
      'correct': '0.8',
    },
    {
      'name': 'T1P8',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Find cosθ in a right triangle with adjacent side 3 and hypotenuse 5.',
      'answers': '0.6; 0.8; 0.5; 1',
      'correct': '0.6',
    },
    {
      'name': 'T1P9',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Find tanθ in a right triangle with opposite side 3 and adjacent side 4.',
      'answers': '0.75; 1; 0.5; 1.33',
      'correct': '0.75',
    },
    {
      'name': 'T1P10',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Using the Pythagorean Theorem, find the missing leg of a triangle with legs 9 and ? such that the hypotenuse is 15.',
      'answers': '12; 10; 8; 14',
      'correct': '12',
    },
    {
      'name': 'T1P11',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'A right triangle has a hypotenuse of 17 and one leg of 8. Find the other leg.',
      'answers': '15; 12; 10; 9',
      'correct': '15',
    },
    {
      'name': 'T1P12',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Find the perimeter of a right triangle with legs 5, 12 and hypotenuse 13.',
      'answers': '30; 31; 32; 33',
      'correct': '30',
    },
    {
      'name': 'T1P13',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'A right triangle has an angle of 45°. If one leg is 7, find the hypotenuse.',
      'answers': '7√2; 7; 14; 7/√2',
      'correct': '7√2',
    },
    {
      'name': 'T1P14',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'Find the area of a right triangle with legs 10 and 10.',
      'answers': '50; 100; 25; 75',
      'correct': '50',
    },
    {
      'name': 'T1P15',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'In a 30°-60°-90° triangle, if the shortest side is 4, find the hypotenuse.',
      'answers': '8; 6; 4; 10',
      'correct': '8',
    },
    {
      'name': 'T1P16',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 3,
      'content': 'A right triangle has legs in the ratio 3:4. If the hypotenuse is 10, approximate the length of the shorter leg.',
      'answers': '6; 7; 5; 4',
      'correct': '6',
    },
    {
      'name': 'T1P17',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'If one leg is 8 and the angle opposite it is 30°, find the hypotenuse of a right triangle.',
      'answers': '16; 12; 10; 14',
      'correct': '16',
    },
    {
      'name': 'T1P18',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'In a right triangle, if sinθ = 0.6 and the hypotenuse is 10, find the length of the opposite side.',
      'answers': '6; 5; 4; 7',
      'correct': '6',
    },
    {
      'name': 'T1P19',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 2,
      'content': 'A 7-24-25 triangle is a right triangle. If one leg is 7 and the hypotenuse is 25, find the other leg.',
      'answers': '24; 23; 26; 22',
      'correct': '24',
    },
    {
      'name': 'T1P20',
      'category': 'Trigonometry',
      'topic': 1,
      'difficulty': 1,
      'content': 'Find the missing acute angle in a right triangle if one acute angle is 40°.',
      'answers': '50°; 40°; 60°; 55°',
      'correct': '50°',
    },

    // Topic 2: Special Angles (20 problems)
    {
      'name': 'T2P1',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is sin(30°)?',
      'answers': '0.5; 0.866; 0; 1',
      'correct': '0.5',
    },
    {
      'name': 'T2P2',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is cos(30°)?',
      'answers': '√3/2; 0.5; 1; 0',
      'correct': '√3/2',
    },
    {
      'name': 'T2P3',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is tan(30°)?',
      'answers': '√3/3; 1; 0.5; √3',
      'correct': '√3/3',
    },
    {
      'name': 'T2P4',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is sin(45°)?',
      'answers': '√2/2; 0.5; √3/2; 1',
      'correct': '√2/2',
    },
    {
      'name': 'T2P5',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is cos(45°)?',
      'answers': '√2/2; 0.5; 1; √3/2',
      'correct': '√2/2',
    },
    {
      'name': 'T2P6',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is tan(45°)?',
      'answers': '1; 0.5; √2/2; 0',
      'correct': '1',
    },
    {
      'name': 'T2P7',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is sin(60°)?',
      'answers': '√3/2; 0.5; 1; √2/2',
      'correct': '√3/2',
    },
    {
      'name': 'T2P8',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is cos(60°)?',
      'answers': '0.5; √3/2; 1; 0',
      'correct': '0.5',
    },
    {
      'name': 'T2P9',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is tan(60°)?',
      'answers': '√3; 1; √3/2; 0.5',
      'correct': '√3',
    },
    {
      'name': 'T2P10',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'Express sin(π/6) in simplest form.',
      'answers': '0.5; √3/2; 1; 0',
      'correct': '0.5',
    },
    {
      'name': 'T2P11',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'Express cos(π/3) in simplest form.',
      'answers': '0.5; 1; √3/2; 0',
      'correct': '0.5',
    },
    {
      'name': 'T2P12',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is tan(π/4)?',
      'answers': '1; 0.5; 0; √2/2',
      'correct': '1',
    },
    {
      'name': 'T2P13',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'State sin(0°).',
      'answers': '0; 1; Undefined; 0.5',
      'correct': '0',
    },
    {
      'name': 'T2P14',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'State cos(0°).',
      'answers': '1; 0; -1; Undefined',
      'correct': '1',
    },
    {
      'name': 'T2P15',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is tan(0°)?',
      'answers': '0; 1; Undefined; 0.5',
      'correct': '0',
    },
    {
      'name': 'T2P16',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'Express sin(90°) in simplest form.',
      'answers': '1; 0; 0.5; √2/2',
      'correct': '1',
    },
    {
      'name': 'T2P17',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'Express cos(90°) in simplest form.',
      'answers': '0; 1; 0.5; √3/2',
      'correct': '0',
    },
    {
      'name': 'T2P18',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 2,
      'content': 'What is tan(90°)?',
      'answers': 'Undefined; 0; 1; ∞',
      'correct': 'Undefined',
    },
    {
      'name': 'T2P19',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is sin(π/2)?',
      'answers': '1; 0; 0.5; √2/2',
      'correct': '1',
    },
    {
      'name': 'T2P20',
      'category': 'Trigonometry',
      'topic': 2,
      'difficulty': 1,
      'content': 'What is cos(π/2)?',
      'answers': '0; 1; 0.5; √2/2',
      'correct': '0',
    },

    // Topic 3: Fundamental Trigonometric Identities (20 problems)
    {
      'name': 'T3P1',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'State the Pythagorean identity.',
      'answers': 'sin²θ + cos²θ = 1; tan²θ + 1 = sec²θ; 1 + cot²θ = csc²θ; All of the above',
      'correct': 'sin²θ + cos²θ = 1',
    },
    {
      'name': 'T3P2',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Express tan²θ in terms of sec²θ.',
      'answers': 'tan²θ = sec²θ - 1; tan²θ = sec²θ + 1; tan²θ = 1 - sec²θ; tan²θ = 1/ sec²θ',
      'correct': 'tan²θ = sec²θ - 1',
    },
    {
      'name': 'T3P3',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Simplify sin²θ + cos²θ.',
      'answers': '1; sinθ; cosθ; 0',
      'correct': '1',
    },
    {
      'name': 'T3P4',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Express cot²θ + 1 in terms of csc²θ.',
      'answers': 'cot²θ + 1 = csc²θ; cot²θ + 1 = sec²θ; cot²θ + 1 = tan²θ; cot²θ + 1 = 1',
      'correct': 'cot²θ + 1 = csc²θ',
    },
    {
      'name': 'T3P5',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Simplify sin²θ + cos²θ.',
      'answers': '1; sinθ; cosθ; 0',
      'correct': '1',
    },
    {
      'name': 'T3P6',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'State the reciprocal identity for secθ.',
      'answers': 'secθ = 1/cosθ; secθ = cosθ; secθ = 1/sinθ; secθ = sinθ',
      'correct': 'secθ = 1/cosθ',
    },
    {
      'name': 'T3P7',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'State the reciprocal identity for cscθ.',
      'answers': 'cscθ = 1/sinθ; cscθ = sinθ; cscθ = 1/cosθ; cscθ = cosθ',
      'correct': 'cscθ = 1/sinθ',
    },
    {
      'name': 'T3P8',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'State the reciprocal identity for cotθ.',
      'answers': 'cotθ = 1/tanθ; cotθ = tanθ; cotθ = 1/sinθ; cotθ = 1/cosθ',
      'correct': 'cotθ = 1/tanθ',
    },
    {
      'name': 'T3P9',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Express 1 + tan²θ in terms of sec²θ.',
      'answers': 'sec²θ; tan²θ; 1; sin²θ',
      'correct': 'sec²θ',
    },
    {
      'name': 'T3P10',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Express 1 + cot²θ in terms of csc²θ.',
      'answers': 'csc²θ; sec²θ; tan²θ; 1',
      'correct': 'csc²θ',
    },
    {
      'name': 'T3P11',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Simplify 1 - sin²θ.',
      'answers': 'cos²θ; sin²θ; 1; 0',
      'correct': 'cos²θ',
    },
    {
      'name': 'T3P12',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Simplify 1 - cos²θ.',
      'answers': 'sin²θ; cos²θ; 1; 0',
      'correct': 'sin²θ',
    },
    {
      'name': 'T3P13',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'If sinθ = 0.6 and θ is acute, find cosθ.',
      'answers': '0.8; 0.6; 0.5; 1',
      'correct': '0.8',
    },
    {
      'name': 'T3P14',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Express tanθ as sinθ/cosθ.',
      'answers': 'sinθ/cosθ; cosθ/sinθ; 1; tanθ',
      'correct': 'sinθ/cosθ',
    },
    {
      'name': 'T3P15',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'If secθ = 2, find cosθ.',
      'answers': '0.5; 2; 1; 0',
      'correct': '0.5',
    },
    {
      'name': 'T3P16',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'If cscθ = 1.25, find sinθ.',
      'answers': '0.8; 1.25; 0.75; 0.5',
      'correct': '0.8',
    },
    {
      'name': 'T3P17',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Express cotθ as cosθ/sinθ.',
      'answers': 'cosθ/sinθ; sinθ/cosθ; 1; tanθ',
      'correct': 'cosθ/sinθ',
    },
    {
      'name': 'T3P18',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 3,
      'content': 'Simplify (sin²θ)/(1 - cos²θ).',
      'answers': '1; sin²θ; cos²θ; tan²θ',
      'correct': '1',
    },
    {
      'name': 'T3P19',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Express 1/tanθ in terms of cotθ.',
      'answers': 'cotθ; tanθ; sinθ; cosθ',
      'correct': 'cotθ',
    },
    {
      'name': 'T3P20',
      'category': 'Trigonometry',
      'topic': 3,
      'difficulty': 2,
      'content': 'Which identity relates tan²θ and sec²θ?',
      'answers': 'tan²θ + 1 = sec²θ; sin²θ + cos²θ = 1; cot²θ + 1 = csc²θ; None',
      'correct': 'tan²θ + 1 = sec²θ',
    },

    // Topic 4: Evaluating Trigonometric Expressions (20 problems)
    {
      'name': 'T4P1',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate sin(120°).',
      'answers': '√3/2; 0.5; -√3/2; 1',
      'correct': '√3/2',
    },
    {
      'name': 'T4P2',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate cos(150°).',
      'answers': '-√3/2; 0.5; √3/2; 1',
      'correct': '-√3/2',
    },
    {
      'name': 'T4P3',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'Evaluate tan(225°).',
      'answers': '1; -1; 0; Undefined',
      'correct': '1',
    },
    {
      'name': 'T4P4',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate sin(330°).',
      'answers': '-1/2; 1/2; 0; 1',
      'correct': '-1/2',
    },
    {
      'name': 'T4P5',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate cos(270°).',
      'answers': '0; -1; 1; Undefined',
      'correct': '0',
    },
    {
      'name': 'T4P6',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 3,
      'content': 'Evaluate tan(315°).',
      'answers': '-1; 1; 0; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T4P7',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate sin(210°).',
      'answers': '-1/2; 1/2; 0; 1',
      'correct': '-1/2',
    },
    {
      'name': 'T4P8',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate cos(240°).',
      'answers': '-1/2; 1/2; 0; -√3/2',
      'correct': '-1/2',
    },
    {
      'name': 'T4P9',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 1,
      'content': 'Evaluate tan(60°).',
      'answers': '√3; 1; 0; 1/√3',
      'correct': '√3',
    },
    {
      'name': 'T4P10',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 1,
      'content': 'Evaluate sin(π/4).',
      'answers': '√2/2; 0.5; 1; 0',
      'correct': '√2/2',
    },
    {
      'name': 'T4P11',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 1,
      'content': 'Evaluate cos(π/6).',
      'answers': '√3/2; 0.5; 1; 0',
      'correct': '√3/2',
    },
    {
      'name': 'T4P12',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 1,
      'content': 'Evaluate tan(π/3).',
      'answers': '√3; 1; 0; √2/2',
      'correct': '√3',
    },
    {
      'name': 'T4P13',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate sin(2π/3).',
      'answers': '√3/2; 0.5; -√3/2; 1',
      'correct': '√3/2',
    },
    {
      'name': 'T4P14',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate cos(5π/6).',
      'answers': '-√3/2; 0.5; √3/2; -0.5',
      'correct': '-√3/2',
    },
    {
      'name': 'T4P15',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 1,
      'content': 'Evaluate tan(45°).',
      'answers': '1; 0; -1; √2/2',
      'correct': '1',
    },
    {
      'name': 'T4P16',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate sin(3π/2).',
      'answers': '-1; 1; 0; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T4P17',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate cos(π).',
      'answers': '-1; 0; 1; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T4P18',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate tan(π).',
      'answers': '0; 1; -1; Undefined',
      'correct': '0',
    },
    {
      'name': 'T4P19',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate sin(11π/6).',
      'answers': '-1/2; 1/2; 0; 1',
      'correct': '-1/2',
    },
    {
      'name': 'T4P20',
      'category': 'Trigonometry',
      'topic': 4,
      'difficulty': 2,
      'content': 'Evaluate cos(11π/6).',
      'answers': '√3/2; 0.5; -√3/2; 1',
      'correct': '√3/2',
    },

    // Topic 5: Applications using the Laws of Sines and Cosines (20 problems)
    {
      'name': 'T5P1',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, angle A = 30°, angle B = 45°, and side a = 10. Use the Law of Sines to find side b (approx.).',
      'answers': 'Approximately 11.31; 10; 12; 9',
      'correct': 'Approximately 11.31',
    },
    {
      'name': 'T5P2',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, sides a = 7, b = 9, and angle C = 60°. Use the Law of Cosines to find side c (approx.).',
      'answers': 'Approximately 5.29; 7; 8; 9',
      'correct': 'Approximately 5.29',
    },
    {
      'name': 'T5P3',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'In triangle ABC with a = 8, b = 6, and angle C = 90°, find side c using the Law of Cosines.',
      'answers': '10; 8; 6; 12',
      'correct': '10',
    },
    {
      'name': 'T5P4',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Given triangle ABC with a = 5, b = 7, and c = 8, use the Law of Cosines to find angle A (approx.).',
      'answers': 'Approximately 53°; 60°; 45°; 40°',
      'correct': 'Approximately 53°',
    },
    {
      'name': 'T5P5',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, a = 9, b = 12, and angle C = 90°. Use the Law of Cosines to verify the triangle is right.',
      'answers': 'Yes, it is right; No; Cannot determine; Not enough information',
      'correct': 'Yes, it is right',
    },
    {
      'name': 'T5P6',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, if a = 10, b = 14, and angle C = 45°, find side c using the Law of Cosines (approx.).',
      'answers': 'Approximately 7.07; 8; 9; 10',
      'correct': 'Approximately 7.07',
    },
    {
      'name': 'T5P7',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC with angles A = 50°, B = 60° and side a = 12, use the Law of Sines to find side b (approx.).',
      'answers': 'Approximately 14.03; 12; 10; 16',
      'correct': 'Approximately 14.03',
    },
    {
      'name': 'T5P8',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'In triangle ABC, if a = 6, angle A = 40° and angle B = 80°, find side b using the Law of Sines (approx.).',
      'answers': 'Approximately 8.8; 7; 10; 9',
      'correct': 'Approximately 8.8',
    },
    {
      'name': 'T5P9',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Use the Law of Cosines to find the third side of a triangle with sides 7 and 9 and an included angle of 120° (approx.).',
      'answers': 'Approximately 13; 11; 15; 10',
      'correct': 'Approximately 13',
    },
    {
      'name': 'T5P10',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'A triangle has sides 8, 15, and 17. Verify the triangle is right using the Law of Cosines.',
      'answers': 'Yes, it is right; No; Uncertain; Cannot determine',
      'correct': 'Yes, it is right',
    },
    {
      'name': 'T5P11',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, if a = 9, b = 10, and angle C = 30°, find side c using the Law of Cosines (approx.).',
      'answers': 'Approximately 3.53; 5; 7; 9',
      'correct': 'Approximately 3.53',
    },
    {
      'name': 'T5P12',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Given triangle ABC with angles A = 70°, B = 50° and side a = 14, use the Law of Sines to find side b (approx.).',
      'answers': 'Approximately 12.1; 10; 14; 16',
      'correct': 'Approximately 12.1',
    },
    {
      'name': 'T5P13',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, if a = 5, b = 7 and angle A = 40°, find angle B using the Law of Sines (approx.).',
      'answers': 'Approximately 55°; 45°; 65°; 60°',
      'correct': 'Approximately 55°',
    },
    {
      'name': 'T5P14',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'For triangle ABC with sides a = 12, b = 16 and angle C = 90°, find the missing angle using the Law of Sines (approx.).',
      'answers': 'Approximately 36.87°; 45°; 30°; 60°',
      'correct': 'Approximately 36.87°',
    },
    {
      'name': 'T5P15',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, if a = 10, b = 15 and angle A = 60°, find angle B using the Law of Cosines (approx.).',
      'answers': 'Approximately 72°; 60°; 80°; 90°',
      'correct': 'Approximately 72°',
    },
    {
      'name': 'T5P16',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 2,
      'content': 'Solve: In triangle ABC, a = 8, b = 6, and angle A = 30°. Use the Law of Sines to find angle B (approx.).',
      'answers': 'Approximately 50°; 40°; 60°; 70°',
      'correct': 'Approximately 50°',
    },
    {
      'name': 'T5P17',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'A triangle has sides 11, 13, and 15. Use the Law of Cosines to find the angle opposite the side of length 11 (approx.).',
      'answers': 'Approximately 39°; 45°; 30°; 60°',
      'correct': 'Approximately 39°',
    },
    {
      'name': 'T5P18',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, if a = 9, b = 12, and c = 15, find angle C using the Law of Cosines (approx.).',
      'answers': 'Approximately 60°; 45°; 75°; 90°',
      'correct': 'Approximately 60°',
    },
    {
      'name': 'T5P19',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'Given triangle ABC with sides 7, 10, and 12, use the Law of Cosines to find angle A (approx.).',
      'answers': 'Approximately 41°; 50°; 35°; 45°',
      'correct': 'Approximately 41°',
    },
    {
      'name': 'T5P20',
      'category': 'Trigonometry',
      'topic': 5,
      'difficulty': 3,
      'content': 'In triangle ABC, if a = 5, b = 8 and angle C = 100°, find side c using the Law of Cosines (approx.).',
      'answers': 'Approximately 10.3; 9; 11; 8.5',
      'correct': 'Approximately 10.3',
    },

    // Topic 6: Evaluate Trigonometric Functions of Real Numbers (20 problems)
    {
      'name': 'T6P1',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate sin(π).',
      'answers': '0; 1; -1; Undefined',
      'correct': '0',
    },
    {
      'name': 'T6P2',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate cos(2π).',
      'answers': '1; 0; -1; 2',
      'correct': '1',
    },
    {
      'name': 'T6P3',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate tan(π/4).',
      'answers': '1; 0; -1; Undefined',
      'correct': '1',
    },
    {
      'name': 'T6P4',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find sin(5π/3).',
      'answers': '-√3/2; √3/2; 1/2; -1/2',
      'correct': '-√3/2',
    },
    {
      'name': 'T6P5',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Find cos(7π/4).',
      'answers': '√2/2; -√2/2; 0; 1',
      'correct': '√2/2',
    },
    {
      'name': 'T6P6',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate tan(3π/4).',
      'answers': '-1; 1; 0; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T6P7',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Compute sin(–π/6).',
      'answers': '-1/2; 1/2; 0; -√2/2',
      'correct': '-1/2',
    },
    {
      'name': 'T6P8',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Compute cos(–π/3).',
      'answers': '1/2; -1/2; 0; 1',
      'correct': '1/2',
    },
    {
      'name': 'T6P9',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'What is tan(–π/4)?',
      'answers': '-1; 1; 0; Undefined',
      'correct': '-1',
    },
    {
      'name': 'T6P10',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate sin(11π/6).',
      'answers': '-1/2; 1/2; 0; 1',
      'correct': '-1/2',
    },
    {
      'name': 'T6P11',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate cos(11π/6).',
      'answers': '√3/2; -√3/2; 0; 1',
      'correct': '√3/2',
    },
    {
      'name': 'T6P12',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Find tan(11π/6).',
      'answers': '-1/√3; 1/√3; -√3; √3',
      'correct': '-1/√3',
    },
    {
      'name': 'T6P13',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Compute sin(13π/6) by reducing the angle.',
      'answers': '1/2; -1/2; 0; 1',
      'correct': '1/2',
    },
    {
      'name': 'T6P14',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Evaluate cos(13π/6) by reducing the angle.',
      'answers': '√3/2; -√3/2; 0; 1',
      'correct': '√3/2',
    },
    {
      'name': 'T6P15',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'What is tan(13π/6) by reducing the angle?',
      'answers': '1/√3; √3; 0; 1',
      'correct': '1/√3',
    },
    {
      'name': 'T6P16',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Evaluate sin(–7π/6) by reducing the angle.',
      'answers': '-1/2; 1/2; 0; -√3/2',
      'correct': '-1/2',
    },
    {
      'name': 'T6P17',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 3,
      'content': 'Evaluate cos(–7π/6) by reducing the angle.',
      'answers': '-√3/2; √3/2; 0; 1',
      'correct': '-√3/2',
    },
    {
      'name': 'T6P18',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'What is tan(–7π/6)?',
      'answers': '1/√3; -1/√3; 1; -1',
      'correct': '1/√3',
    },
    {
      'name': 'T6P19',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Compute sin(5π/2) by reducing the angle.',
      'answers': '1; 0; -1; Undefined',
      'correct': '1',
    },
    {
      'name': 'T6P20',
      'category': 'Trigonometry',
      'topic': 6,
      'difficulty': 2,
      'content': 'Evaluate cos(5π/2) by reducing the angle.',
      'answers': '0; 1; -1; Undefined',
      'correct': '0',
    },

    // Topic 7: Analyzing and Graphing Trigonometric Functions (20 problems)
    {
      'name': 'T7P1',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'What is the amplitude of y = 3 sin x?',
      'answers': '3; 1; 0; 2',
      'correct': '3',
    },
    {
      'name': 'T7P2',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'What is the period of y = cos(2x)?',
      'answers': 'π; 2π; π/2; 2π/3',
      'correct': 'π',
    },
    {
      'name': 'T7P3',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Find the phase shift of y = sin(x - π/4).',
      'answers': 'π/4 to the right; π/4 to the left; π/2 to the right; No shift',
      'correct': 'π/4 to the right',
    },
    {
      'name': 'T7P4',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'What is the range of y = 2 cos x + 1?',
      'answers': '[-1,3]; [–2,2]; [0,4]; [–3,1]',
      'correct': '[-1,3]',
    },
    {
      'name': 'T7P5',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Determine the domain of y = tan x.',
      'answers': 'x ≠ π/2 + kπ, k∈ℤ; all real numbers; x ≠ kπ; x ≠ π/4 + kπ',
      'correct': 'x ≠ π/2 + kπ, k∈ℤ',
    },
    {
      'name': 'T7P6',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'What is the period of y = 4 tan(3x)?',
      'answers': 'π/3; π; 2π/3; π/2',
      'correct': 'π/3',
    },
    {
      'name': 'T7P7',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Find the amplitude and period of y = 5 sin(½x).',
      'answers': 'Amplitude 5, Period 4π; Amplitude 5, Period 2π; Amplitude 2.5, Period 4π; Amplitude 5, Period 8π',
      'correct': 'Amplitude 5, Period 4π',
    },
    {
      'name': 'T7P8',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 1,
      'content': 'Graph y = cos x. What are its maximum and minimum values?',
      'answers': 'Max 1, Min -1; Max 0, Min -1; Max 1, Min 0; Max 2, Min -2',
      'correct': 'Max 1, Min -1',
    },
    {
      'name': 'T7P9',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Determine the phase shift of y = sin(x + π/6).',
      'answers': 'π/6 to the left; π/6 to the right; No shift; π/3 to the left',
      'correct': 'π/6 to the left',
    },
    {
      'name': 'T7P10',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 1,
      'content': 'What is the vertical shift of y = sin x - 2?',
      'answers': 'Down 2; Up 2; None; Down 1',
      'correct': 'Down 2',
    },
    {
      'name': 'T7P11',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the period of y = sin(4x).',
      'answers': 'π/2; π; 2π; 4π',
      'correct': 'π/2',
    },
    {
      'name': 'T7P12',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Determine the range of y = 2 cos x - 1.',
      'answers': '[-3,1]; [–1,3]; [0,2]; [–2,2]',
      'correct': '[-3,1]',
    },
    {
      'name': 'T7P13',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'What is the amplitude of y = –3 sin x?',
      'answers': '3; -3; 0; 1',
      'correct': '3',
    },
    {
      'name': 'T7P14',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'For y = cos(½x) + 2, what is the midline?',
      'answers': 'y = 2; y = 0; y = 1; y = 2.5',
      'correct': 'y = 2',
    },
    {
      'name': 'T7P15',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Graph y = tan x. Identify its vertical asymptotes.',
      'answers': 'x = π/2 + kπ, k∈ℤ; x = kπ, k∈ℤ; x = π/4 + kπ; x = π/2',
      'correct': 'x = π/2 + kπ, k∈ℤ',
    },
    {
      'name': 'T7P16',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'What is the period of y = cot(2x)?',
      'answers': 'π; π/2; 2π; 2π/3',
      'correct': 'π',
    },
    {
      'name': 'T7P17',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Determine the domain of y = sec x.',
      'answers': 'x ≠ π/2 + kπ; all real; x ≠ kπ; x ≠ π/4',
      'correct': 'x ≠ π/2 + kπ',
    },
    {
      'name': 'T7P18',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 2,
      'content': 'Find the amplitude of y = 4 cos x.',
      'answers': '4; 2; 1; 0',
      'correct': '4',
    },
    {
      'name': 'T7P19',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 1,
      'content': 'What is the period of y = 2 sin x?',
      'answers': '2π; π; π/2; 4π',
      'correct': '2π',
    },
    {
      'name': 'T7P20',
      'category': 'Trigonometry',
      'topic': 7,
      'difficulty': 3,
      'content': 'Determine the phase shift of y = cos(x - π/3).',
      'answers': 'π/3 to the right; π/3 to the left; No shift; π/6 to the right',
      'correct': 'π/3 to the right',
    },

    // Topic 8: Simplify Trigonometric Expressions and Prove Identities (first 10 problems)
    {
      'name': 'T8P1',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: sin²x + cos²x.',
      'answers': '1; sin x; cos x; 0',
      'correct': '1',
    },
    {
      'name': 'T8P2',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: 1 + tan²x.',
      'answers': 'sec²x; tan²x; 1; cos²x',
      'correct': 'sec²x',
    },
    {
      'name': 'T8P3',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Prove: cot²x + 1 = csc²x.',
      'answers': 'Identity holds; False; Depends on x; Not true',
      'correct': 'Identity holds',
    },
    {
      'name': 'T8P4',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (1 - cos²x)/sin²x.',
      'answers': '1; sin²x; cos²x; tan²x',
      'correct': '1',
    },
    {
      'name': 'T8P5',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: sin²x/(1 + cos x).',
      'answers': '1 - cos x; sin x; cos x; 1',
      'correct': '1 - cos x',
    },
    {
      'name': 'T8P6',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (sec x - tan x)(sec x + tan x).',
      'answers': '1; sec²x; tan²x; 0',
      'correct': '1',
    },
    {
      'name': 'T8P7',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: 1 - sin²x.',
      'answers': 'cos²x; sin²x; 1; 0',
      'correct': 'cos²x',
    },
    {
      'name': 'T8P8',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (1 + sin x)/(1 - sin x) by multiplying numerator and denominator by (1 + sin x).',
      'answers': '((1+sin x)²)/(cos²x); 1; tan²x; sec²x',
      'correct': '((1+sin x)²)/(cos²x)',
    },
    {
      'name': 'T8P9',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (tan x)/(sec x).',
      'answers': 'sin x; cos x; tan x; 1',
      'correct': 'sin x',
    },
    {
      'name': 'T8P10',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (1 - cos x)² + sin²x.',
      'answers': '2 - 2cos x; 1; 2; 2cos x',
      'correct': '2 - 2cos x',
    },
    {
      'name': 'T8P11',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (sin x cos x)/(tan x).',
      'answers': 'cos²x; sin²x; sin x; cos x',
      'correct': 'cos²x',
    },
    {
      'name': 'T8P12',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Prove: 1 - sin²x = cos²x.',
      'answers': 'Identity holds; False; Only for x=0; None',
      'correct': 'Identity holds',
    },
    {
      'name': 'T8P13',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (1 - cos²x)/sin x.',
      'answers': 'sin x; cos x; 1; tan x',
      'correct': 'sin x',
    },
    {
      'name': 'T8P14',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (sec x - 1)/(tan x).',
      'answers': 'csc x - cot x; sin x; cos x; 1',
      'correct': 'csc x - cot x',
    },
    {
      'name': 'T8P15',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (1 + cos x)/(1 - cos x).',
      'answers': '((1+cos x)²)/(sin²x); 1; tan²x; sec²x',
      'correct': '((1+cos x)²)/(sin²x)',
    },
    {
      'name': 'T8P16',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: (sin x)/(1 + cos x) + (sin x)/(1 - cos x).',
      'answers': '2tan x; 2sin x/cos x; 2sin x/(sin²x); 2cos x/sin x',
      'correct': '2tan x',
    },
    {
      'name': 'T8P17',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (1 - tan²x)/(1 + tan²x).',
      'answers': 'cos 2x; sin 2x; 1; tan 2x',
      'correct': 'cos 2x',
    },
    {
      'name': 'T8P18',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Prove: sin 2x = 2 sin x cos x.',
      'answers': 'Identity holds; False; Only for special angles; None',
      'correct': 'Identity holds',
    },
    {
      'name': 'T8P19',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 2,
      'content': 'Simplify: (1 - cos x)² + sin²x.',
      'answers': '2 - 2cos x; 1; 2cos x; 2',
      'correct': '2 - 2cos x',
    },
    {
      'name': 'T8P20',
      'category': 'Trigonometry',
      'topic': 8,
      'difficulty': 3,
      'content': 'Simplify: tan x · cot x.',
      'answers': '1; tan x; cot x; 0',
      'correct': '1',
    },

    // Topic 9: Evaluate Inverse Trigonometric Functions (20 problems)
    {
      'name': 'T9P1',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Find sin(arccos(0.6)).',
      'answers': '0.8; 0.6; 0.4; 1',
      'correct': '0.8',
    },
    {
      'name': 'T9P2',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Evaluate arctan(1).',
      'answers': '45° or π/4; 30°; 60°; 90°',
      'correct': '45° or π/4',
    },
    {
      'name': 'T9P3',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'What is arccos(1)?',
      'answers': '0; π/2; π; Undefined',
      'correct': '0',
    },
    {
      'name': 'T9P4',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find arctan(0).',
      'answers': '0; π/4; π/2; 1',
      'correct': '0',
    },
    {
      'name': 'T9P5',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Evaluate arcsin(0.5).',
      'answers': '30° or π/6; 45°; 60°; 90°',
      'correct': '30° or π/6',
    },
    {
      'name': 'T9P6',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'What is arccos(0)?',
      'answers': '90° or π/2; 0; 45°; 180°',
      'correct': '90° or π/2',
    },
    {
      'name': 'T9P7',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find arctan(√3).',
      'answers': '60° or π/3; 45°; 30°; 90°',
      'correct': '60° or π/3',
    },
    {
      'name': 'T9P8',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'If y = arcsin(0.8), find cos y (approx.).',
      'answers': '0.6; 0.8; 0.64; 0.5',
      'correct': '0.6',
    },
    {
      'name': 'T9P9',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find arctan(1/√3).',
      'answers': '30° or π/6; 45°; 60°; 90°',
      'correct': '30° or π/6',
    },
    {
      'name': 'T9P10',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Evaluate arccos(0.5).',
      'answers': '60° or π/3; 45°; 30°; 90°',
      'correct': '60° or π/3',
    },
    {
      'name': 'T9P11',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Express arctan(√3/3) in degrees.',
      'answers': '30°; 45°; 60°; 90°',
      'correct': '30°',
    },
    {
      'name': 'T9P12',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find arcsin(–0.5).',
      'answers': '-30° or -π/6; 30°; -45°; 45°',
      'correct': '-30° or -π/6',
    },
    {
      'name': 'T9P13',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Evaluate arccos(–1).',
      'answers': 'π; 0; π/2; 2π',
      'correct': 'π',
    },
    {
      'name': 'T9P14',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find arctan(0) in radians.',
      'answers': '0; π/4; π/2; 1',
      'correct': '0',
    },
    {
      'name': 'T9P15',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'If y = arctan(2), express y in approximate degrees.',
      'answers': '63.4°; 45°; 30°; 90°',
      'correct': '63.4°',
    },
    {
      'name': 'T9P16',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Evaluate arccos(–0.5).',
      'answers': '120° or 2π/3; 60° or π/3; 90° or π/2; 180°',
      'correct': '120° or 2π/3',
    },
    {
      'name': 'T9P17',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Find arcsin(0.866) in degrees (approx.).',
      'answers': '60°; 45°; 30°; 90°',
      'correct': '60°',
    },
    {
      'name': 'T9P18',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Express arctan(1) in radians.',
      'answers': 'π/4; π/6; π/3; 1',
      'correct': 'π/4',
    },
    {
      'name': 'T9P19',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 2,
      'content': 'Find arccos(0) in degrees.',
      'answers': '90°; 0°; 45°; 180°',
      'correct': '90°',
    },
    {
      'name': 'T9P20',
      'category': 'Trigonometry',
      'topic': 9,
      'difficulty': 3,
      'content': 'Evaluate arcsin(1) in radians.',
      'answers': 'π/2; π; 1; 0',
      'correct': 'π/2',
    },

    // Topic 10: Solve Trigonometric Equations (20 problems)
    {
      'name': 'T10P1',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: sin x = 0.5 in [0, 2π).',
      'answers': 'x = π/6 and 5π/6; x = π/6 and π/3; x = 5π/6 and 7π/6; x = π/4 and 5π/4',
      'correct': 'x = π/6 and 5π/6',
    },
    {
      'name': 'T10P2',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: cos x = -0.5 in [0, 2π).',
      'answers': 'x = 2π/3 and 4π/3; x = π/3 and 2π/3; x = 4π/3 and 5π/3; x = π and 3π/2',
      'correct': 'x = 2π/3 and 4π/3',
    },
    {
      'name': 'T10P3',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: tan x = 1 in [0, 2π).',
      'answers': 'x = π/4 and 5π/4; x = π/4 and 3π/4; x = π/4 and 7π/4; x = 0 and π',
      'correct': 'x = π/4 and 5π/4',
    },
    {
      'name': 'T10P4',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: 2 sin x - 1 = 0 in [0, 2π).',
      'answers': 'x = π/6 and 5π/6; x = π/6 and 7π/6; x = π/6 and 11π/6; x = 7π/6 and 11π/6',
      'correct': 'x = π/6 and 5π/6',
    },
    {
      'name': 'T10P5',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: cos x = 0.5 in [0, 2π).',
      'answers': 'x = π/3 and 5π/3; x = π/3 and 2π/3; x = 2π/3 and 4π/3; x = π/3 and 4π/3',
      'correct': 'x = π/3 and 5π/3',
    },
    {
      'name': 'T10P6',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: sin x = -0.5 in [0, 2π).',
      'answers': 'x = 7π/6 and 11π/6; x = π/6 and 5π/6; x = π/6 and 7π/6; x = 7π/6 and 5π/6',
      'correct': 'x = 7π/6 and 11π/6',
    },
    {
      'name': 'T10P7',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: tan x = √3 in [0, 2π).',
      'answers': 'x = π/3 and 4π/3; x = π/3 and 5π/3; x = 2π/3 and 5π/3; x = π/3 and 2π/3',
      'correct': 'x = π/3 and 4π/3',
    },
    {
      'name': 'T10P8',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: sin x = 0 in [0, 2π).',
      'answers': 'x = 0, π, 2π; x = π/2, 3π/2; x = 0, π/2, π; x = π, 2π',
      'correct': 'x = 0, π, 2π',
    },
    {
      'name': 'T10P9',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve for x: cos x = 0 in [0, 2π).',
      'answers': 'x = π/2 and 3π/2; x = 0, π, 2π; x = π/2 and 5π/2; x = π and 2π',
      'correct': 'x = π/2 and 3π/2',
    },
    {
      'name': 'T10P10',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: 2cos x - 1 = 0 for x in [0, 2π).',
      'answers': 'x = π/3 and 5π/3; x = π/3 and 4π/3; x = π/2 and 3π/2; x = 0 and π',
      'correct': 'x = π/3 and 5π/3',
    },
    {
      'name': 'T10P11',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: sin x = 0.866 in [0, 2π) (approx.).',
      'answers': 'x ≈ 1.047 and 2.094; x ≈ 1.047 and 2.618; x ≈ 1.047 and 5.236; x ≈ 1.047 and 2.094',
      'correct': 'x ≈ 1.047 and 2.094',
    },
    {
      'name': 'T10P12',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve for x: cos x = -0.866 in [0, 2π) (approx.).',
      'answers': 'x ≈ 2.618 and 3.665; x ≈ 2.094 and 4.188; x ≈ 2.618 and 4.188; x ≈ 3.142 and 4.712',
      'correct': 'x ≈ 2.618 and 3.665',
    },
    {
      'name': 'T10P13',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: tan x = -1 in [0, 2π).',
      'answers': 'x = 3π/4 and 7π/4; x = π/4 and 5π/4; x = 2π/3 and 5π/3; x = 3π/4 and 5π/4',
      'correct': 'x = 3π/4 and 7π/4',
    },
    {
      'name': 'T10P14',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve: 2sin x = 1 for x in [0, 2π).',
      'answers': 'x = π/6 and 5π/6; x = π/6 and 7π/6; x = π/6 and 11π/6; x = 5π/6 and 7π/6',
      'correct': 'x = π/6 and 5π/6',
    },
    {
      'name': 'T10P15',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: sin x = -0.5 in [0, 2π).',
      'answers': 'x = 7π/6 and 11π/6; x = 5π/6 and 7π/6; x = 7π/6 and 5π/6; x = π/6 and 11π/6',
      'correct': 'x = 7π/6 and 11π/6',
    },
    {
      'name': 'T10P16',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve: cos x = 0.866 in [0, 2π) (approx.).',
      'answers': 'x ≈ 0.524 and 5.76; x ≈ 0.524 and 1.047; x ≈ 0.524 and 5.76; x ≈ 0.524 and 2.094',
      'correct': 'x ≈ 0.524 and 5.76',
    },
    {
      'name': 'T10P17',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: tan x = 2 in [0, 2π) (approx.).',
      'answers': 'x ≈ 1.107 and 4.249; x ≈ 1.107 and 2.034; x ≈ 1.570 and 4.712; x ≈ 0.785 and 3.926',
      'correct': 'x ≈ 1.107 and 4.249',
    },
    {
      'name': 'T10P18',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve: sin x = 0 in [0, 2π).',
      'answers': 'x = 0, π, 2π; x = π/2, 3π/2; x = 0, π/2, π; x = π, 2π',
      'correct': 'x = 0, π, 2π',
    },
    {
      'name': 'T10P19',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 2,
      'content': 'Solve: cos x = 0 in [0, 2π).',
      'answers': 'x = π/2 and 3π/2; x = 0, π, 2π; x = π/2 and 5π/2; x = π and 2π',
      'correct': 'x = π/2 and 3π/2',
    },
    {
      'name': 'T10P20',
      'category': 'Trigonometry',
      'topic': 10,
      'difficulty': 3,
      'content': 'Solve: 2cos x - 1 = 0 in [0, 2π).',
      'answers': 'x = π/3 and 5π/3; x = π/3 and 4π/3; x = π/2 and 3π/2; x = 0 and π',
      'correct': 'x = π/3 and 5π/3',
    },

    // Topic 11: Identify and Graph Common Polar Equations (20 problems)
    {
      'name': 'T11P1',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Which polar equation represents a circle with radius 4 centered at the origin?',
      'answers': 'r = 4; r = 4cosθ; r = 4sinθ; r = 8',
      'correct': 'r = 4',
    },
    {
      'name': 'T11P2',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Identify the polar equation for a line: r cosθ = 3.',
      'answers': 'r = 3secθ; r = 3cscθ; r = 3; r = 3cosθ',
      'correct': 'r = 3secθ',
    },
    {
      'name': 'T11P3',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Which polar equation represents a cardioid?',
      'answers': 'r = 1 + cosθ; r = 2cosθ; r = cosθ; r = 1 - cosθ',
      'correct': 'r = 1 + cosθ',
    },
    {
      'name': 'T11P4',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Identify the polar equation for a limaçon with an inner loop.',
      'answers': 'r = 1 - 2cosθ; r = 2 + cosθ; r = 1 + 2cosθ; r = 2 - cosθ',
      'correct': 'r = 1 - 2cosθ',
    },
    {
      'name': 'T11P5',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Which polar equation represents a rose curve with 4 petals?',
      'answers': 'r = 3cos(2θ); r = 3sin(2θ); Both; r = 3cosθ',
      'correct': 'Both',
    },
    {
      'name': 'T11P6',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Identify the polar equation of a spiral: r = θ.',
      'answers': 'r = θ; r = 2θ; r = θ/2; r = θ²',
      'correct': 'r = θ',
    },
    {
      'name': 'T11P7',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'What does the polar equation r = 2sinθ represent?',
      'answers': 'A circle; A line; A cardioid; A spiral',
      'correct': 'A circle',
    },
    {
      'name': 'T11P8',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Identify the polar equation for a circle with center at (2,0) and radius 2.',
      'answers': 'r = 2cosθ + 2; r = 2cosθ; r = 2 + 2cosθ; r = 2cosθ + 4',
      'correct': 'r = 2cosθ + 2',
    },
    {
      'name': 'T11P9',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Which polar equation represents a line through the origin?',
      'answers': 'θ = π/4; r = 3; r cosθ = 2; r = 0',
      'correct': 'θ = π/4',
    },
    {
      'name': 'T11P10',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Identify the polar equation for a circle tangent to the pole with radius 3.',
      'answers': 'r = 3cosθ + 3; r = 3; r = 3sinθ + 3; r = 6cosθ',
      'correct': 'r = 3cosθ + 3',
    },
    {
      'name': 'T11P11',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'What is the polar equation for a circle with center at (0, -4) and radius 4?',
      'answers': 'r = 4 - 4sinθ; r = 4 + 4sinθ; r = 4cosθ; r = 4',
      'correct': 'r = 4 - 4sinθ',
    },
    {
      'name': 'T11P12',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Identify the polar equation for a rose curve with 3 petals.',
      'answers': 'r = cos(3θ); r = sin(3θ); Both; r = cos(2θ)',
      'correct': 'Both',
    },
    {
      'name': 'T11P13',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'What does the polar equation r = 2 represent?',
      'answers': 'A circle of radius 2; A line; A cardioid; A spiral',
      'correct': 'A circle of radius 2',
    },
    {
      'name': 'T11P14',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Express the polar equation for a circle centered at (0, 3) with radius 3.',
      'answers': 'r = 3 + 3sinθ; r = 3cosθ + 3; r = 3 + 3cosθ; r = 3sinθ + 3',
      'correct': 'r = 3 + 3sinθ',
    },
    {
      'name': 'T11P15',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Identify the polar equation of a circle with radius 5 centered at the origin.',
      'answers': 'r = 5; r = 5cosθ; r = 5sinθ; r = 10',
      'correct': 'r = 5',
    },
    {
      'name': 'T11P16',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Find the polar equation representing a circle with center (3,0) and radius 3.',
      'answers': 'r = 3 + 3cosθ; r = 3cosθ; r = 3 + 3cosθ; r = 6cosθ',
      'correct': 'r = 3 + 3cosθ',
    },
    {
      'name': 'T11P17',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Which polar equation represents a circle tangent to the pole?',
      'answers': 'r = a ± a sinθ; r = 2a; r = a sinθ; r = a cosθ',
      'correct': 'r = a ± a sinθ',
    },
    {
      'name': 'T11P18',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Identify the polar equation for a circle with center at (2,2) and radius 2.',
      'answers': 'r = 2cosθ + 2sinθ; r = 2cosθ + 2; r = 2 + 2sinθ; r = 2cosθ',
      'correct': 'r = 2cosθ + 2sinθ',
    },
    {
      'name': 'T11P19',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 2,
      'content': 'Find the polar equation for a line through the pole making an angle of 30°.',
      'answers': 'θ = 30°; r = 30; r cosθ = 30; r sinθ = 30',
      'correct': 'θ = 30°',
    },
    {
      'name': 'T11P20',
      'category': 'Trigonometry',
      'topic': 11,
      'difficulty': 3,
      'content': 'Which polar equation represents a rose curve with 5 petals?',
      'answers': 'r = cos(5θ); r = sin(5θ); Both; r = cos(2θ)',
      'correct': 'Both',
    },

    // Topic 12: Common Parametric Curves (20 problems)
    {
      'name': 'T12P1',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'Which parametric equations represent a line through the origin?',
      'answers': 'x = t, y = 2t; x = 2t, y = t; Both; None',
      'correct': 'Both',
    },
    {
      'name': 'T12P2',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Identify the parametric equations for a circle of radius 3.',
      'answers': 'x = 3cos t, y = 3sin t; x = 3cos t, y = 3sin t + 1; x = cos t, y = sin t; x = 3cos t + 1, y = 3sin t',
      'correct': 'x = 3cos t, y = 3sin t',
    },
    {
      'name': 'T12P3',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What are the parametric equations for a line with slope 2 and y-intercept 3?',
      'answers': 'x = t, y = 2t + 3; x = t, y = 2t - 3; x = 2t, y = t + 3; x = 2t, y = 2t + 3',
      'correct': 'x = t, y = 2t + 3',
    },
    {
      'name': 'T12P4',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the parametric equations for an ellipse with semi-major axis 5 and semi-minor axis 3.',
      'answers': 'x = 5cos t, y = 3sin t; x = 3cos t, y = 5sin t; x = 5cos t, y = 5sin t; x = 3cos t, y = 3sin t',
      'correct': 'x = 5cos t, y = 3sin t',
    },
    {
      'name': 'T12P5',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'Parametric equations x = t + 2, y = 3t - 1 represent what kind of curve?',
      'answers': 'A line; A circle; A parabola; An ellipse',
      'correct': 'A line',
    },
    {
      'name': 'T12P6',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Identify the parametric equations for a parabola opening to the right.',
      'answers': 'x = t², y = 2t; x = 2t, y = t²; x = t², y = t; x = 4t², y = 2t',
      'correct': 'x = t², y = 2t',
    },
    {
      'name': 'T12P7',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What parametric equations represent a vertical line x = 4?',
      'answers': 'x = 4, y = t; x = t, y = 4; x = 4t, y = t; x = 4, y = 4t',
      'correct': 'x = 4, y = t',
    },
    {
      'name': 'T12P8',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the parametric equations for a line with slope -1 passing through (2, 3).',
      'answers': 'x = 2 + t, y = 3 - t; x = 2 - t, y = 3 + t; x = 2 + t, y = 3 + t; x = 2 - t, y = 3 - t',
      'correct': 'x = 2 + t, y = 3 - t',
    },
    {
      'name': 'T12P9',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'What are the parametric equations for the line x = 5?',
      'answers': 'x = 5, y = t; x = t, y = 5; x = 5t, y = t; x = 5, y = 5t',
      'correct': 'x = 5, y = t',
    },
    {
      'name': 'T12P10',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Identify the parametric form of the circle x² + y² = 16.',
      'answers': 'x = 4cos t, y = 4sin t; x = 4cos t, y = 4sin t + 1; x = 16cos t, y = 16sin t; x = 4cos t + 1, y = 4sin t',
      'correct': 'x = 4cos t, y = 4sin t',
    },
    {
      'name': 'T12P11',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'Express the parametric equations for a line through the origin with slope 3.',
      'answers': 'x = t, y = 3t; x = 3t, y = t; x = t+3, y = 3t; x = t, y = t+3',
      'correct': 'x = t, y = 3t',
    },
    {
      'name': 'T12P12',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the parametric equations for the parabola y² = 4x.',
      'answers': 'x = t², y = 2t; x = 2t², y = t; x = t, y = 2t²; x = 4t², y = 2t',
      'correct': 'x = t², y = 2t',
    },
    {
      'name': 'T12P13',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'The parametric equations x = 3t + 1, y = 2t - 4 represent what?',
      'answers': 'A line; A circle; A parabola; An ellipse',
      'correct': 'A line',
    },
    {
      'name': 'T12P14',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Find the parametric equations for an ellipse with center at (1,2), semi-major axis 4 and semi-minor axis 3.',
      'answers': 'x = 1 + 4cos t, y = 2 + 3sin t; x = 1 + 3cos t, y = 2 + 4sin t; x = 4cos t, y = 3sin t; x = 1 + 4cos t, y = 2 + 4sin t',
      'correct': 'x = 1 + 4cos t, y = 2 + 3sin t',
    },
    {
      'name': 'T12P15',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'Express the parametric equations for a horizontal line y = 7.',
      'answers': 'x = t, y = 7; x = 7, y = t; x = t+7, y = 7; x = 7, y = t+7',
      'correct': 'x = t, y = 7',
    },
    {
      'name': 'T12P16',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Identify the parametric equations for a line passing through (2, -3) with slope 1/2.',
      'answers': 'x = 2 + t, y = -3 + t/2; x = 2 + 2t, y = -3 + t; x = 2 + t/2, y = -3 + t; x = 2 + t, y = -3 + 2t',
      'correct': 'x = 2 + t, y = -3 + t/2',
    },
    {
      'name': 'T12P17',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'For the parametric equations x = 5, y = t, what curve is represented?',
      'answers': 'Vertical line; Horizontal line; Parabola; Circle',
      'correct': 'Vertical line',
    },
    {
      'name': 'T12P18',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Determine the parametric equations for the line: x - 2 = 3(y + 1).',
      'answers': 'x = 2 + 3t, y = -1 + t; x = 2 + t, y = -1 + 3t; x = t + 2, y = 3t - 1; x = 2 + t, y = -1 + t',
      'correct': 'x = 2 + 3t, y = -1 + t',
    },
    {
      'name': 'T12P19',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 2,
      'content': 'Express the parametric equations for a line through the origin with slope -2.',
      'answers': 'x = t, y = -2t; x = -2t, y = t; x = t, y = 2t; x = -t, y = 2t',
      'correct': 'x = t, y = -2t',
    },
    {
      'name': 'T12P20',
      'category': 'Trigonometry',
      'topic': 12,
      'difficulty': 3,
      'content': 'Identify the parametric form of the line x = 3, y = 2t + 1.',
      'answers': 'A vertical line; A horizontal line; A line with slope 2; None of the above',
      'correct': 'A vertical line',
    },

    // Topic 13: Vector Operations (20 problems)
    {
      'name': 'T13P1',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'If v = (3, 4) and w = (1, 2), what is v + w?',
      'answers': '(4,6); (2,2); (3,4); (1,2)',
      'correct': '(4,6)',
    },
    {
      'name': 'T13P2',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'If v = (2, 5) and w = (3, -1), what is v - w?',
      'answers': '(-1,6); (5,4); (-1,-6); (2,5)',
      'correct': '(-1,6)',
    },
    {
      'name': 'T13P3',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Find the scalar multiple of v = (4, -2) by 3.',
      'answers': '(12, -6); (4, -2); (7, -3.5); (3, -1.5)',
      'correct': '(12, -6)',
    },
    {
      'name': 'T13P4',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'If v = (1, 2) and w = (2, 3), find 2v + 3w.',
      'answers': '(8,13); (7,10); (5,8); (6,9)',
      'correct': '(8,13)',
    },
    {
      'name': 'T13P5',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'Find the negative of vector v = (–3, 4).',
      'answers': '(3, –4); (–3, –4); (3,4); (–3,4)',
      'correct': '(3, –4)',
    },
    {
      'name': 'T13P6',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Compute 3v – 2w for v = (2, 1) and w = (1, 4).',
      'answers': '(4, -7); (4, 7); (5, -7); (4, -6)',
      'correct': '(4, -7)',
    },
    {
      'name': 'T13P7',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'What is the result of multiplying vector v = (3, -1) by -2?',
      'answers': '(-6, 2); (6, -2); (3, -1); (-3, 1)',
      'correct': '(-6, 2)',
    },
    {
      'name': 'T13P8',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'If v = (4, 2) and w = (-1, 3), find v + 2w.',
      'answers': '(2,8); (4,8); (3,8); (2,7)',
      'correct': '(2,8)',
    },
    {
      'name': 'T13P9',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'Find the result of subtracting v = (5,7) from w = (2,3).',
      'answers': '(-3,-4); (3,4); (7,10); (-7,-10)',
      'correct': '(-3,-4)',
    },
    {
      'name': 'T13P10',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Compute: 2(v + w) for v = (1,2) and w = (3,4).',
      'answers': '(8,12); (4,6); (2,4); (10,14)',
      'correct': '(8,12)',
    },
    {
      'name': 'T13P11',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'If v = (3,3) and w = (1, -1), find v – 2w.',
      'answers': '(1,5); (3,3); (1,1); (2,4)',
      'correct': '(1,5)',
    },
    {
      'name': 'T13P12',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Find the result of scaling vector v = (2,-4) by a factor of -3.',
      'answers': '(-6,12); (6,-12); (-6,-12); (6,12)',
      'correct': '(-6,12)',
    },
    {
      'name': 'T13P13',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'What is 0 times any vector v?',
      'answers': '(0,0); v; Undefined; v itself',
      'correct': '(0,0)',
    },
    {
      'name': 'T13P14',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Find the sum: (1,2) + (3,4) + (–2,5).',
      'answers': '(2,11); (2,7); (1,11); (2,9)',
      'correct': '(2,11)',
    },
    {
      'name': 'T13P15',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'Compute: (–4,6) – (1,2).',
      'answers': '(-5,4); (-3,4); (-5,8); (-3,8)',
      'correct': '(-5,4)',
    },
    {
      'name': 'T13P16',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'If v = (2,3) and w = (–1,4), find 3v − w.',
      'answers': '(7,5); (7,5); (6,5); (7,6)',
      'correct': '(7,5)',
    },
    {
      'name': 'T13P17',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'What is the result of adding the zero vector to v = (3,4)?',
      'answers': '(3,4); (0,0); (3,0); (4,3)',
      'correct': '(3,4)',
    },
    {
      'name': 'T13P18',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Compute: (2,-1) + (-3,4).',
      'answers': '(-1,3); (-5,3); (1,3); (2,3)',
      'correct': '(-1,3)',
    },
    {
      'name': 'T13P19',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 2,
      'content': 'If v = (4,0) and w = (0,5), find v + w.',
      'answers': '(4,5); (0,0); (4,0); (0,5)',
      'correct': '(4,5)',
    },
    {
      'name': 'T13P20',
      'category': 'Trigonometry',
      'topic': 13,
      'difficulty': 3,
      'content': 'Compute: 2(3,-2) - (1,4).',
      'answers': '(5,-8); (6,-8); (5,-6); (6,-6)',
      'correct': '(5,-8)',
    },

    // Topic 14: Applied Vector Problems (20 problems)
    {
      'name': 'T14P1',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'A force vector F = (3,4) is applied. Find its magnitude.',
      'answers': '5; 7; 6; 4',
      'correct': '5',
    },
    {
      'name': 'T14P2',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'If two vectors are perpendicular, what is the value of their dot product?',
      'answers': '0; 1; -1; Undefined',
      'correct': '0',
    },
    {
      'name': 'T14P3',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'Given v = (1,2) and w = (3,4), find the dot product v · w.',
      'answers': '11; 10; 12; 9',
      'correct': '11',
    },
    {
      'name': 'T14P4',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'If the angle between vectors v and w is 60°, and |v| = 4, |w| = 5, find their dot product (approx.).',
      'answers': '10; 8; 9; 7',
      'correct': '10',
    },
    {
      'name': 'T14P5',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'A displacement vector has magnitude 10 and direction 30°. Express it in Cartesian form (approx.).',
      'answers': '(8.66, 5); (5,8.66); (8.66,5); (10,30)',
      'correct': '(8.66,5)',
    },
    {
      'name': 'T14P6',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'Find the resultant of vectors (3,0) and (0,4).',
      'answers': '(3,4); (5,0); (0,7); (3,0)',
      'correct': '(3,4)',
    },
    {
      'name': 'T14P7',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'Two forces F₁ = (4,3) and F₂ = (–2,5) act on an object. Find F₁ + F₂.',
      'answers': '(2,8); (6,2); (4,5); (2,2)',
      'correct': '(2,8)',
    },
    {
      'name': 'T14P8',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'If a vector has magnitude 7 and makes an angle of 45° with the x-axis, find its x-component.',
      'answers': '7cos45°; 7sin45°; 7; 3.5',
      'correct': '7cos45°',
    },
    {
      'name': 'T14P9',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'A boat travels with velocity (8,3) mph and a current pushes it with (2,–1) mph. Find the net velocity.',
      'answers': '(10,2); (8,3); (10,4); (6,2)',
      'correct': '(10,2)',
    },
    {
      'name': 'T14P10',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'Solve an applied problem: If a wind of 20 mph blows east and a plane flies north at 150 mph, find the plane’s resultant speed (approx.).',
      'answers': 'Approximately 152 mph; Approximately 150 mph; Approximately 155 mph; Approximately 160 mph',
      'correct': 'Approximately 152 mph',
    },
    {
      'name': 'T14P11',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'Find the angle between vectors v = (3,4) and w = (4,–3) using the dot product.',
      'answers': '90°; 45°; 60°; 120°',
      'correct': '90°',
    },
    {
      'name': 'T14P12',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'If v = (5,0) and w = (0,5), what is the magnitude of v + w?',
      'answers': '√50; 5; 10; 25',
      'correct': '√50',
    },
    {
      'name': 'T14P13',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'Determine the unit vector in the direction of v = (3,4).',
      'answers': '(0.6,0.8); (3,4); (1,1); (0.8,0.6)',
      'correct': '(0.6,0.8)',
    },
    {
      'name': 'T14P14',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'Find the magnitude of the vector 2(–1,3).',
      'answers': '√40; √10; 4; 6',
      'correct': '√40',
    },
    {
      'name': 'T14P15',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'If a force is represented by the vector (7,–24), find its magnitude.',
      'answers': '25; 24; 7; 31',
      'correct': '25',
    },
    {
      'name': 'T14P16',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'Find the result of subtracting vectors (8,3) and (2,5).',
      'answers': '(6,–2); (10,8); (6,8); (8,3)',
      'correct': '(6,–2)',
    },
    {
      'name': 'T14P17',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'Two forces of 10 N and 15 N act at an angle of 60°. Find the magnitude of their resultant (approx.).',
      'answers': 'Approximately 21.65; 20; 25; 30',
      'correct': 'Approximately 21.65',
    },
    {
      'name': 'T14P18',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'If a vector has components (–3,4), what is its direction in degrees (measured from the positive x-axis)?',
      'answers': '126.87°; 53.13°; 90°; 180°',
      'correct': '126.87°',
    },
    {
      'name': 'T14P19',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 2,
      'content': 'Find the sum: (2,3) + (–1,4).',
      'answers': '(1,7); (2,7); (1,4); (0,1)',
      'correct': '(1,7)',
    },
    {
      'name': 'T14P20',
      'category': 'Trigonometry',
      'topic': 14,
      'difficulty': 3,
      'content': 'Compute: 3(2,–1) + 2(–1,3).',
      'answers': '(4,3); (2,4); (4,–3); (2,–3)',
      'correct': '(4,3)',
    },

    // Topic 15: Dot Product and Projections (20 problems)
    {
      'name': 'T15P1',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Compute the dot product of v = (3,4) and w = (5,6).',
      'answers': '39; 42; 38; 36',
      'correct': '39',
    },
    {
      'name': 'T15P2',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'If v = (2,3) and w = (–1,4), find v · w.',
      'answers': '10; 11; 8; 9',
      'correct': '10',
    },
    {
      'name': 'T15P3',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Find the scalar projection of v = (4,0) onto w = (0,5).',
      'answers': '0; 4; 5; Undefined',
      'correct': '0',
    },
    {
      'name': 'T15P4',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Find the vector projection of v = (3,4) onto w = (4,0).',
      'answers': '(3,0); (4,0); (3,4); (0,0)',
      'correct': '(3,0)',
    },
    {
      'name': 'T15P5',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Compute the dot product: (1,2,3) · (4,5,6) for vectors in ℝ³.',
      'answers': '32; 33; 34; 35',
      'correct': '32',
    },
    {
      'name': 'T15P6',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'If v = (3,0) and w = (0,4), what is the vector projection of v onto w?',
      'answers': '(0,0); (3,0); (0,3); (0,4)',
      'correct': '(0,0)',
    },
    {
      'name': 'T15P7',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'Find the dot product of v = (–2,5) and w = (4,–1).',
      'answers': '–13; 13; –9; 9',
      'correct': '–13',
    },
    {
      'name': 'T15P8',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Find the scalar projection of v = (6,8) onto w = (3,4).',
      'answers': '10; 5; 10; 12',
      'correct': '10',
    },
    {
      'name': 'T15P9',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Compute: (3,4) · (–4,3).',
      'answers': '0; –1; 1; 7',
      'correct': '0',
    },
    {
      'name': 'T15P10',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'Find the dot product: (2,2) · (2,2).',
      'answers': '8; 4; 2; 0',
      'correct': '8',
    },
    {
      'name': 'T15P11',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'If v = (1,0) and w = (cosθ, sinθ), express v · w in terms of θ.',
      'answers': 'cosθ; sinθ; 1; 0',
      'correct': 'cosθ',
    },
    {
      'name': 'T15P12',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Find the vector projection of v = (4,3) onto w = (0,5).',
      'answers': '(0,2.4); (2.4,0); (0,3); (4,3)',
      'correct': '(0,2.4)',
    },
    {
      'name': 'T15P13',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'If v = (2, -3) and w = (4,1), find v · w.',
      'answers': '5; 2; -10; 8',
      'correct': '5',
    },
    {
      'name': 'T15P14',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Compute the dot product: (–1,2) · (3,–4).',
      'answers': '–11; 11; –10; 10',
      'correct': '–11',
    },
    {
      'name': 'T15P15',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'Find the scalar projection of v = (5,12) onto itself.',
      'answers': '13; 17; 1; 0',
      'correct': '13',
    },
    {
      'name': 'T15P16',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Express the dot product of v = (a,b) and w = (c,d) in terms of a, b, c, and d.',
      'answers': 'ac + bd; ad + bc; a + c; b + d',
      'correct': 'ac + bd',
    },
    {
      'name': 'T15P17',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'What is the dot product of the zero vector and any vector?',
      'answers': '0; 1; Undefined; The magnitude of the other vector',
      'correct': '0',
    },
    {
      'name': 'T15P18',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'If v = (3,4) and w = (6,8), find the scalar projection of v onto w (approx.).',
      'answers': '0.6; 1.2; 0.5; 1',
      'correct': '0.6',
    },
    {
      'name': 'T15P19',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 2,
      'content': 'Find the dot product: (4,3) · (4,3).',
      'answers': '25; 24; 16; 12',
      'correct': '25',
    },
    {
      'name': 'T15P20',
      'category': 'Trigonometry',
      'topic': 15,
      'difficulty': 3,
      'content': 'Compute the vector projection of v = (2,3) onto w = (1,1) (approx.).',
      'answers': '(2.5,2.5); (2,2); (3,3); (1,1)',
      'correct': '(2.5,2.5)',
    },
  ];